Add details to CONTRIBUTING
fivetran/great_expectations pull request #1071
Opened 2020-02-12 22:33 UTC by spbail

Some fairly big changes to the contribution instructions:
- restructured the sections
- added instructions for docs-only contribution
- added step-by-step instructions for code contributions including forks etc

I tested these with a new github account and I'm pretty confident they make sense, but there's definitely a chance I missed a step. I anticipate iterations on this for both clarity and correctness, but this should be a good starting point for more detailed instructions.

2020-02-13 13:58 UTC, jcampbell requested changes

2020-02-13 13:58 UTC, jcampbell commented on CONTRIBUTING.md
> +- `--no-sqlalchemy` will skip sqlalchemy tests
Two small clarifications here: 
1. even with all of these flags set, the *pandas* backend *will* be tested...it's not currently possible to disable those tests.
2. `no-sqlalchemy` is a superset of `no-postgresql`...if you set no-sqlalchemy then no-postgresql is implied.

2020-02-13 13:58 UTC, jcampbell commented on CONTRIBUTING.md
> +* Second, if you have opinions on the testing framework, we'd love to hear them! Feedback based on your perspective and experience is very welcome.
OBE! We should have removed this...

2020-02-13 13:58 UTC, jcampbell commented on CONTRIBUTING.md
ditto

2020-02-13 13:58 UTC, jcampbell commented on CONTRIBUTING.md
remove, OBE

2020-02-13 14:32 UTC, abegong reviewed
These changes (and James' clarifications) look great to me.

2020-02-13 21:04 UTC, spbail commented
TIL what OBE means.

2020-02-14 16:26 UTC, jcampbell approved these changes

2020-02-14 16:26 UTC, merged