rename cli batch kwarg argument
fivetran/great_expectations pull request #1077
Opened 2020-02-13 18:44 UTC by Aylr

## What's Here

- renamed `--batch-kwargs` to the more correct `--additional-batch-kwargs`
- minor linting
﻿

2020-02-13 18:44 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.

* In the file [`great_expectations/cli/datasource.py`](https://github.com/great-expectations/great_expectations/blob/6be0a50182f21025254a70017478ae25a0d17c28/great_expectations/cli/datasource.py):

> [Line 154:121](https://github.com/great-expectations/great_expectations/blob/6be0a50182f21025254a70017478ae25a0d17c28/great_expectations/cli/datasource.py#L154): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (131 > 120 characters)
> [Line 168:121](https://github.com/great-expectations/great_expectations/blob/6be0a50182f21025254a70017478ae25a0d17c28/great_expectations/cli/datasource.py#L168): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2020-02-14 15:17 UTC, jcampbell requested changes
Can you clarify why additional_batch_kwargs is more correct in this case?

2020-02-14 15:40 UTC, Aylr commented
Because as I understand it this isn't really batch_kwargs. It's additional ones that get added. @eugmandel can explain this better than I can.

2020-02-14 16:25 UTC, jcampbell approved these changes

2020-02-14 16:30 UTC, merged