Feature/citations
fivetran/great_expectations pull request #1113
Opened 2020-03-02 18:27 UTC by Aylr

2020-03-02 18:27 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.



















* In the file [`tests/render/renderer/test_notebook_renderer.py`](https://github.com/great-expectations/great_expectations/blob/84e1eb780ebf655488c5a1e1be880486624f1123/tests/render/renderer/test_notebook_renderer.py):

> [Line 246:121](https://github.com/great-expectations/great_expectations/blob/84e1eb780ebf655488c5a1e1be880486624f1123/tests/render/renderer/test_notebook_renderer.py#L246): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (367 > 120 characters)

2020-03-04 14:26 UTC, jcampbell requested changes
I'd like to change the `get_most_recent_citation_containing_batch_kwargs` to just `get_citations` and have it take several (optional) parameters such as `require_batch_kwargs` and/or `sorted` so that the `ExpectationSuite` interface can be more general. Then the renderer can get the citations, sorted, with batch_kwargs, and only pick off the last one, for example.

2020-03-05 00:09 UTC, Aylr commented
Great calls. Implemented. Please re-review.

2020-03-05 02:13 UTC, jcampbell approved these changes
Love this!

2020-03-05 14:23 UTC, merged