Bugfixes/datadocs ui
fivetran/great_expectations pull request #1116
Opened 2020-03-04 15:45 UTC by roblim

Addresses:
- https://app.asana.com/0/1119694864223484/1162583857360089/f
- https://app.asana.com/0/1119694864223484/1161644922195953/f
- https://app.asana.com/0/1119694864223484/1145663702660542/f
- https://app.asana.com/0/1119694864223484/1133008169429685/f

Before:
<img width="1675" alt="Screenshot 2020-02-18 16 21 48" src="https://user-images.githubusercontent.com/3468435/75896299-bbf03200-5deb-11ea-8979-f11a799b21a9.png">
<img width="498" alt="Screenshot 2020-03-03 23 34 00" src="https://user-images.githubusercontent.com/3468435/75896330-c8748a80-5deb-11ea-8b09-70da30ad3bba.png">
<img width="495" alt="Screenshot 2020-03-03 23 38 14" src="https://user-images.githubusercontent.com/3468435/75896363-d4f8e300-5deb-11ea-9dfe-fac44fbdfb1d.png">

After:
<img width="1584" alt="Screenshot 2020-03-04 07 44 06" src="https://user-images.githubusercontent.com/3468435/75896428-f0fc8480-5deb-11ea-9f21-9fe054310a99.png">
<img width="493" alt="Screenshot 2020-03-03 23 35 13" src="https://user-images.githubusercontent.com/3468435/75896470-ff4aa080-5deb-11ea-9c2a-95a210bd695d.png">
<img width="500" alt="Screenshot 2020-03-03 23 37 37" src="https://user-images.githubusercontent.com/3468435/75896509-0c678f80-5dec-11ea-84d0-508c60790821.png">

2020-03-04 15:45 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.





* In the file [`tests/render/test_default_jinja_view.py`](https://github.com/great-expectations/great_expectations/blob/3faf02c16c7096efa9336da575a236915a3e6d29/tests/render/test_default_jinja_view.py):

> [Line 129:7](https://github.com/great-expectations/great_expectations/blob/3faf02c16c7096efa9336da575a236915a3e6d29/tests/render/test_default_jinja_view.py#L129): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-03-05 14:38 UTC, Aylr requested changes
This looks great - I love the before and after screens! QQ: is the deletion of the scroller gif intentional?

2020-03-05 17:56 UTC, roblim commented
> This looks great - I love the before and after screens! QQ: is the deletion of the scroller gif intentional?

@Aylr - it's still there. Just deleted old version and replaced with new cropped version.

2020-03-05 19:47 UTC, Aylr approved these changes

2020-03-05 19:48 UTC, merged