Bugfix/bad negative result values
fivetran/great_expectations pull request #1152
Opened 2020-03-10 17:33 UTC by roblim

Addresses: https://github.com/great-expectations/great_expectations/issues/1133
- add new InvalidCacheValueError exception class
- validate result dict when instantiating ExpectationValidationResult, raise InvalidCacheValueError if validation fails

2020-03-10 17:33 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.

* In the file [`great_expectations/core/__init__.py`](https://github.com/great-expectations/great_expectations/blob/5fcb1481026e24a0edfc773edca49db3b015ea2e/great_expectations/core/__init__.py):

> [Line 665:121](https://github.com/great-expectations/great_expectations/blob/5fcb1481026e24a0edfc773edca49db3b015ea2e/great_expectations/core/__init__.py#L665): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

* In the file [`great_expectations/exceptions.py`](https://github.com/great-expectations/great_expectations/blob/5fcb1481026e24a0edfc773edca49db3b015ea2e/great_expectations/exceptions.py):

> [Line 117:120](https://github.com/great-expectations/great_expectations/blob/5fcb1481026e24a0edfc773edca49db3b015ea2e/great_expectations/exceptions.py#L117): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

2020-03-10 21:26 UTC, jcampbell requested changes
Love this approach. Will you add a test case both with and without the `catch_exceptions` flags being set to show how this could (not) block an ongoing validation?

2020-03-11 19:41 UTC, roblim commented
@jcampbell - added the test cases

2020-03-17 19:27 UTC, jcampbell approved these changes

2020-03-17 20:10 UTC, merged