Allow UpdateDataDocsAction to also specify data doc sites to build
fivetran/great_expectations pull request #1256
Opened 2020-04-05 00:39 UTC by troxil

### Rationale
* `DataContext` -> `build_data_docs` can support a list of certain sites you want docs written to. This PR enables the same from within the `UpdateDataDocsAction`.

### Changes
* By supplying a new config `target_site_names` which would be a list (I didn't see any typing used so I didn't add in a type check `List[str]`.

Sample `great_expectations.yml`:
```yaml
validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
    - name: update_fun_data_docs
      action:
        class_name: UpdateDataDocsAction
        target_site_names:
          - fun_site
```

2020-04-05 00:41 UTC, troxil commented
@cla-bot check

2020-04-06 15:13 UTC, jcampbell requested changes
Thank you!

Could you please add a note to the changelog and docstring for the action?

Also -- let me know about any questions/issues with the CLA!

2020-04-07 12:03 UTC, troxil commented
@cla-bot check

2020-04-07 12:17 UTC, pep8speaks commented
Thank you for submitting to Great Expectations!

* In the file [`great_expectations/validation_operators/actions.py`](https://github.com/great-expectations/great_expectations/blob/31723ba80ed0ec307b8338f661891b8a3d2378dc/great_expectations/validation_operators/actions.py):

> [Line 252:87](https://github.com/great-expectations/great_expectations/blob/31723ba80ed0ec307b8338f661891b8a3d2378dc/great_expectations/validation_operators/actions.py#L252): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

This linter comment has been updated based on the most recent commit.

2020-04-07 13:38 UTC, jcampbell approved these changes

2020-04-07 13:38 UTC, jcampbell commented
Thank you!

2020-04-07 13:38 UTC, merged