* TupleFilesystemStoreBackend now ignore `.ipynb_checkpoints` directories `#1203 <https://github.com/great-expectations/great_expectations/issues/1203>`_
fivetran/great_expectations pull request #1264
Opened 2020-04-06 23:23 UTC by Aylr

2020-04-07 13:57 UTC, jcampbell requested changes
Two comments here:

1. I think that if we're going to add a mechanism to ignore certain files it should be done via default value and configurability in spirit of others, so that the `IGNORED_FILES` in this PR becomes the default for a configurable status.

2. This default makes sense to me, but with three caveats:
  a) are we protecting against a common misconfiguration, in which case we should try to address the root cause? There "shouldn't" be a case where someone is dropping unexpected files inside the expectation store, so I think this is mostly about a case where someone inadvertently used jupyter notebook to open a suite. In that case, it seems like we should perhaps print a warning about this found key in addition to skipping it.
 b) Current behavior skips the name anywhere in the tuple. Is that always right?
 c) Are there other defaults to drop (.DS_STORE)?

2020-04-07 15:36 UTC, Aylr commented
Good thoughts.
1. I'm trying to be as lightweight as possible here, and we can always change this. I specifically don't want to encourage configuration as this is a sacrosanct folder that should not have junk in it, and configuration might encourage this behavior.
2a. We are protecting against users firing up jupyter in expectations folders. I suspect it will be common given how many of our users use notebooks.
2b. Yes.
2c. Maybe, but again, I don't want to encourage this, so I'd opt to leave it as is.

2020-04-07 20:34 UTC, jcampbell submitted a review, later dismissed

2020-04-07 21:17 UTC, Aylr commented
@jcampbell I want you to look at this again - while using this branch I found and fixed another error.

2020-04-08 19:22 UTC, jcampbell approved these changes

2020-04-08 19:22 UTC, jcampbell commented on great_expectations/data_context/data_context.py
> +                continue
I liked the earlier version that had a warning here. But I think we can include that in updates to the store API later.

2020-04-08 21:22 UTC, Aylr commented
Merging. Required builds passed: https://travis-ci.org/github/great-expectations/great_expectations/builds/672699929

2020-04-08 21:23 UTC, merged