allow ImportError exception to avoid missing boto3 during __init__
fivetran/great_expectations pull request #1288
Opened 2020-04-10 11:40 UTC by syahdeini

I received this error 
![image](https://user-images.githubusercontent.com/5045714/78984517-b4c4ee00-7b26-11ea-8b84-7e839559fd19.png)
The problem is when boto3 is not installed, then it will throw null AttributeError. 
I believe we should allow the ImportError and the try-catch expectation is not really useful therefore I delete it.

2020-04-10 11:42 UTC, syahdeini commented on great_expectations/datasource/generator/s3_generator.py
> -        except TypeError:
It is also possible to use AttributeError here, but this module will need to use boto3 nevertheless so why not make it fail on the first place.

2020-04-10 14:25 UTC, Aylr commented
@syahdeini Thanks for looking at this. In an effort to allow people to run great expectations with as few dependencies as possible, we want to allow this module to at least import without requiring boto3. However you make an excellent point that the `TypeError` should be changed to an `AttributeError`. Would you like to make this change (and leave the try catch around the `import boto3`?

2020-04-10 14:26 UTC, Aylr requested changes
@syahdeini Thanks for looking at this. In an effort to allow people to run great expectations with as few dependencies as possible, we want to allow this module to at least import without requiring boto3. However you make an excellent point that the `TypeError` should be changed to an `AttributeError`. Would you like to make this change (and leave the try catch around the `import boto3`?

2020-04-10 15:29 UTC, syahdeini commented
@Aylr Done, Thanks for the opportunity and the great works!

2020-04-10 18:45 UTC, Aylr approved these changes
Hey, thanks again this was a great catch!

2020-04-10 22:49 UTC, Aylr commented
@kyleaton Can you check out the cla bot issues on this PR?

2020-04-10 23:03 UTC, Aylr commented
@syahdeini Will you please sign our Contributor License Agreement so we can merge this? https://docs.greatexpectations.io/en/latest/contributing/miscellaneous.html#contributor-license-agreement-cla

2020-04-12 16:18 UTC, kyleaton commented
@cla-bot check

2020-04-12 16:19 UTC, kyleaton commented
@cla-bot check

2020-04-12 16:20 UTC, kyleaton commented
@cla-bot check

2020-04-13 16:09 UTC, merged