New Feature for Spark: expect_multicolumn_values_to_be_unique
fivetran/great_expectations pull request #1294
Opened 2020-04-11 03:25 UTC by WilliamWsyHK

Hello, it is my feature implementation time for Spark.

- [X] Test your changes - Total `4` cases about this feature
- [X] Update the documentation.
- [X] Sign the Contributor License Agreement.
- [X] Rebase your changes - Currently latest on `develop` branch

Please feel free to review.

2020-04-11 03:25 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.

* In the file [`great_expectations/dataset/sparkdf_dataset.py`](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py):

> [Line 357:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L357): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (155 > 120 characters)
> [Line 360:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L360): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (154 > 120 characters)
> [Line 401:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L401): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (151 > 120 characters)
> [Line 409:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L409): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 410:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L410): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)
> [Line 411:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L411): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 412:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L412): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)
> [Line 413:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L413): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 414:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L414): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 415:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L415): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 416:121](https://github.com/great-expectations/great_expectations/blob/2f422211a73c692df198672cf3c4fd12828407c8/great_expectations/dataset/sparkdf_dataset.py#L416): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)

2020-05-07 15:14 UTC, jcampbell requested changes
Thank you! This is great. 

I have one small request, one question, and one medium request:

1. Please add a line to the changelog describing the addition: "[FEATURE] add support for expect_multicolumn_values_to_be_unique to spark"

2. In the `boolean_mapped_skip_values` definition, would using the native isNull operation and a basic select be any different? I have a somewhat irrational desire to avoid dynamically generating sql.

3. Can you review the new decorator going into spark to see if there are opportunities to tailor the language in comments to clarify where there are comments that are carry-over (e.g. did you re-run tests for the utility of caching?) and where there are things specific to this decorator? The context here is that we're going to refactor these decorators soon, so I want to avoid having to parse the logic twice for small differences, and would really appreciate to have that called out.

2020-05-09 13:33 UTC, WilliamWsyHK commented
Hi, Thanks for the review.

1. Where can I find the change log?
2. Please review
3. Talking about caching, I have a gut guess that the "persist = false" logic was wrong (currently implemented within `SparkDFDataset`), due to the fact that all current "real" caching logic is implemented within `MetaSparkDFDataset`; and for other discussion I was not aware about, please guide me thru those.

2020-05-11 18:35 UTC, mzjp2 commented
> Hi, Thanks for the review.
> 
> 1. Where can I find the change log?
> 2. Please review
> 3. Talking about caching, I have a gut guess that the "persist = false" logic was wrong (currently implemented within `SparkDFDataset`), due to the fact that all current "real" caching logic is implemented within `MetaSparkDFDataset`; and for other discussion I was not aware about, please guide me thru those.

For 1. `docs/changelog.rst`: https://github.com/great-expectations/great_expectations/blob/develop/docs/changelog.rst

2020-05-18 20:35 UTC, jcampbell approved these changes

2020-05-18 21:33 UTC, merged