[BUGFIX][DOCS] Bugfix: fixed an example in the custom expectations doc
fivetran/great_expectations pull request #1423
Opened 2020-05-12 18:52 UTC by eugmandel

Changes proposed in this pull request:
- Bugfix: fixed an example in the custom expectations docs article - result key was missing in the returned dictionary

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
- No design review required - this was done in an interactive session with @jcampbell 
-
-

Thank you for submitting!

2020-05-12 19:35 UTC, jcampbell requested changes

2020-05-12 19:35 UTC, jcampbell commented on docs/reference/custom_expectations.rst
> +                        'result': {
For consistency --> unindent to match "success" and change ' -> "

2020-05-12 19:35 UTC, jcampbell commented on docs/reference/custom_expectations.rst
> +                        'result': {
For consistency --> unindent to match "success" and change ' -> "

2020-05-12 22:09 UTC, eugmandel commented on docs/reference/custom_expectations.rst
> +                        'result': {
Did not see this - thank you! Fixed.

2020-05-13 15:05 UTC, jcampbell approved these changes

2020-05-13 15:05 UTC, merged