[ENHANCEMENT] Allow config substitutions to be passed to DataContext
fivetran/great_expectations pull request #1430
Opened 2020-05-13 18:23 UTC by balexander

Changes proposed in this pull request:
- Allow a dictionary of config variable substitutions to be passed to the DataContext constructor (`runtime_config_substitutions`). 
- `runtime_config_substitutions` will be used preferentially.  It overrides variables set in config_variables.yml and in the environment.

I have two concrete use cases for this functionality:

* First, I want to be able to specify different slack webhook depending on which validation I'm running, but I don't want to create a bunch of different validation_action configs.
* Second, I'm running expectations on DataBricks and I want to be able to use their secret management. With this, I can pass in a data source config like this:

```python
datasource_config={
  'redshiftCredentials': {
    'password': dbutils.secrets.get('my_scope', 'my_password'),
    'username': dbutils.secrets.get('my_scope', 'my_password'),
    'host' :....
    #... etc ...
  }
}
    
context = DataContext('./great_expectations', runtime_config_substitutions=datasource_config)
```

**Notes:**
* I'm putting up this PR with some tests that fail locally. I think it is specific to my environment but I will fix them if they are real failures
* Please let me know if there are more tests I should add/modify. I couldn't find any that needed to be changed
* Also I've very open to feedback on the name `runtime_config_substitutions`

2020-05-13 18:23 UTC, pep8speaks commented
Hello @balexander! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`great_expectations/data_context/data_context.py`](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py):

> [Line 121:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (95 > 79 characters)
> [Line 127:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L127): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 594:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L594): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> [Line 1884:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L1884): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> [Line 1893:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L1893): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (106 > 79 characters)
> [Line 1938:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/great_expectations/data_context/data_context.py#L1938): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (85 > 79 characters)



* In the file [`tests/data_context/conftest.py`](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py):

> [Line 34:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py#L34): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 40:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py#L40): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 49:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (94 > 79 characters)
> [Line 61:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> [Line 62:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/conftest.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (93 > 79 characters)

* In the file [`tests/data_context/test_data_context_config_variables.py`](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/test_data_context_config_variables.py):

> [Line 103:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/test_data_context_config_variables.py#L103): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 115:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/test_data_context_config_variables.py#L115): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> [Line 119:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/test_data_context_config_variables.py#L119): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> [Line 121:80](https://github.com/great-expectations/great_expectations/blob/d654be557434b81c35f1ce469f807c49bf964131/tests/data_context/test_data_context_config_variables.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)

2020-05-13 18:33 UTC, balexander commented on tests/data_context/conftest.py
> +            "../test_fixtures/great_expectations_basic_without_config_variables_filepath.yml",
PEP8 speaks is complaining about this line. The 80 character limit is tiny!

2020-05-13 18:33 UTC, balexander commented on tests/data_context/conftest.py
> +        "../test_fixtures/expectation_suites/parameterized_expectation_suite_fixture.json",
PEP8 speaks is complaining about this line. The 80 character limit is tiny!

2020-05-14 14:18 UTC, jcampbell requested changes
Thank you!

I'd like to use the name `runtime_environment` as the parameter name instead of `runtime_config_substitutions` to parallel the dictionary used by the plugin system for `instantiate_class_from_config`, but otherwise this design looks great!

(I also could see a good argument for only dropping `_substititions` and going with `runtime_config`, but this feels more like an environment issue to me)

2020-05-14 14:19 UTC, jcampbell commented
Not review related --> I just disabled PEP8 speaks since we're now using `black` for linting. You should be able to use the pre-commit hook or just run black directly to accommodate the linter.

2020-05-14 18:40 UTC, jcampbell approved these changes
Thank you!

2020-05-18 14:37 UTC, balexander commented
@jcampbell I updated the docs if you'd like to review that

2020-05-18 14:40 UTC, jcampbell approved these changes

2020-05-18 15:25 UTC, merged