[DOCS] checkpoint cron howto
fivetran/great_expectations pull request #1490
Opened 2020-05-26 23:52 UTC by Aylr

Changes proposed in this pull request:
- checkpoint cron howto
-
-

Previous Design Review notes:
- 
-
-

Thank you for submitting!

2020-05-28 16:10 UTC, abegong requested changes
The content is great, but it doesn't follow the new structure and template for how-to guides:
* https://docs.greatexpectations.io/en/latest/how_to_guides/miscellaneous/how_to_write_a_how_to_guide.html
* https://docs.greatexpectations.io/en/latest/how_to_guides/miscellaneous/how_to_template.html

Not including numbered steps is an especially big departure.

I want to be rigorous about following a prescribed format, since (1) it'll keep us on the straight and narrow for writing "how-to" guides, and not wandering into reference material, (2) once we hit a rhythm, it'll help us knock out guides faster, and (3) when contributors start writing guides, it'll help us enforce greater consistency.

2020-05-28 16:10 UTC, abegong commented on docs/how_to_guides/validation/how_to_deploy_a_scheduled_checkpoint_with_cron.rst
> +    This article assumes that in your deployment environment you have access to:
Please add the standard blurb about having already configured a working deployment. I want to habituate users to understand that that's the royal road to getting real stuff done in GE.

2020-05-28 16:10 UTC, abegong commented on docs/how_to_guides/validation/how_to_deploy_a_scheduled_checkpoint_with_cron.rst
> +.. admonition:: Prerequisites
Please use the standard header here

2020-05-28 16:10 UTC, abegong commented on docs/how_to_guides/validation/how_to_deploy_a_scheduled_checkpoint_with_cron.rst
> +In this guide you'll learn how to deploy a `Checkpoint <link here>_` on a schedule using cron.
Minor nit, how-tos aren't about teaching or learning. "This guide will show you how to..." "This guide will walk you through the steps..." "To {do X}, follow the steps in this guide..."

2020-05-28 16:45 UTC, Aylr commented on docs/how_to_guides/validation/how_to_deploy_a_scheduled_checkpoint_with_cron.rst
> +.. admonition:: Prerequisites
Ah yep - this PR predates my knowledge of the template. Fixing

2020-05-29 15:03 UTC, abegong commented
Minor changes:
* Capitalized "Checkpoint", since it's a core concept. Ideally, we'd also link on first reference, but that reference article hasn't been written yet.
* Fixed an ungrammatical sentence.

2020-05-29 15:05 UTC, merged