[DOCS] Will/docs/how to/metadata stores/expectation on filesystem
fivetran/great_expectations pull request #1530
Opened 2020-06-02 20:11 UTC by Shinnnyshinshin

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- added documentation to `how_to/metadata_stores/expectation_on_filesystem`

2020-06-03 23:21 UTC, jcampbell requested changes
I think I see two different versions of this in #1530 and #1531...can you clarify which is correct to review (I had already looked at 1531)

2020-06-04 05:19 UTC, Shinnnyshinshin commented
suggested changes from #1531 are reflected in the most recent push

2020-06-04 19:40 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +    - Configured an :ref:`Expectation Suite <_how_to_guides__creating_and_editing_expectations__how_to_create_a_new_expectation_suite_using_the_cli>`.
The statement : Configured an Expectation Suite is currently linked to the How to guide for creating a expectation suite using the CLI 
 https://docs.greatexpectations.io/en/latest/how_to_guides/creating_and_editing_expectations/how_to_create_a_new_expectation_suite_using_the_cli.html


Another option would be the Expectations document under Core Concepts
https://docs.greatexpectations.io/en/latest/reference/core_concepts.html#expectations

2020-06-04 19:40 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +    - Configured a :ref:`Data Context <how_to_guides__configuring_data_contexts__how_to_create_a_new_data_context_with_the_cli>`.
Configured a Data Context currently links to the How_to_guide for creating a new Data Context suite using the CLI.

https://docs.greatexpectations.io/en/latest/how_to_guides/configuring_data_contexts/how_to_create_a_new_data_context_with_the_cli.html

Another option would be to link it to the Core Concepts article
https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_context.html

2020-06-04 19:42 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +    - Configured an :ref:`Expectation Suite <_how_to_guides__creating_and_editing_expectations__how_to_create_a_new_expectation_suite_using_the_cli>`.
Resolved by @abegong. This now points to Tutorial 
https://docs.greatexpectations.io/en/latest/tutorials/getting_started/create_your_first_expectations.html

2020-06-04 19:43 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +    - Configured a :ref:`Data Context <how_to_guides__configuring_data_contexts__how_to_create_a_new_data_context_with_the_cli>`.
resolved by @abegong . Now points to Tutorial 

https://docs.greatexpectations.io/en/latest/tutorials/getting_started/initialize_a_data_context.html

2020-06-10 19:26 UTC, jcampbell commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +    mv expectations/npi_expectations.json /shared_expectations
```suggestion
    mv expectations/npi_expectations.json shared_expectations/
```

2020-06-10 19:27 UTC, jcampbell requested changes
Approved, but note one change that I think needs to be made first.

2020-06-10 22:18 UTC, Shinnnyshinshin commented
ToDo : Section describing how github can be used to store expectations.

2020-06-12 17:34 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_metadata_stores/how_to_configure_an_expectation_store_on_a_filesystem.rst
> +- For best practices, we highly recommend that you store Expectations in a version-control system like Git. The JSON format of Expectations will allow for informative diff-statements and effective tr
This is the blurb that recommends storing Expectations on Git. Does it need a `punchy` conclusion?

2020-06-15 14:52 UTC, jcampbell approved these changes

2020-06-15 14:52 UTC, merged