* [BUGFIX] ProfilerTypeMapping uses lists instead of sets to prevent serialization errors when saving suites created by JsonSchemaProfiler
fivetran/great_expectations pull request #1652
Opened 2020-06-29 20:54 UTC by Aylr

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
* [BUGFIX] ProfilerTypeMapping uses lists instead of sets to prevent serialization errors when saving suites created by JsonSchemaProfiler

Previous Design Review notes:
-
-
-

Thank you for submitting!

2020-06-29 20:55 UTC, Aylr commented on tests/profile/test_jsonschema_profiler.py
> +    context.save_expectation_suite(obs)
All these tests now attempt to save the generated suites thereby catching this bug.

2020-06-30 13:42 UTC, jcampbell requested changes
I think this is a good fix...BUT most expectation configurations accept sets as valid input and serialize to lists via `convert_to_json_serializable`. 

Will you diagnose what's going on in this case that is preventing that and then also address that issue?

2020-06-30 15:31 UTC, Aylr commented
I assumed, perhaps incorrectly, that because I was creating `ExpectationConfiguration`s and `ExpectationKwargs` entirely manually without evaluation (or even a context) that this was my error, not a bug. I can only spend a little time on this and I'll see what I can do!

2020-06-30 16:19 UTC, Aylr commented
Hmm... I'm hitting my timebox on this and am stumped. Here's a chunk of debugging code that so far has not identified the alleged bug that reproduces a few scenarios.

Note I'm only using these sets/lists in a single expectation.

```python
from great_expectations import DataContext
from great_expectations.core import (
    ExpectationConfiguration,
    ExpectationKwargs,
    ExpectationSuite,
    convert_to_json_serializable,
)
from great_expectations.profile.json_schema_profiler import JsonSchemaProfiler

EXPECTATION_TYPE = "expect_column_values_to_be_in_type_list"
context = DataContext("/Users/taylor/Desktop/repro/great_expectations/")
assert isinstance(context, DataContext)


def attempt_each_json_type_individually():
    COLUMN = "foo"
    print(
        "Attempting to save a suite with a single expectation for each json type in both list and set form."
    )
    for json_type in JsonSchemaProfiler.PROFILER_TYPE_LIST_BY_JSON_SCHEMA_TYPE.keys():
        print(f"Attempting json_type {json_type}")
        type_iterable = JsonSchemaProfiler.PROFILER_TYPE_LIST_BY_JSON_SCHEMA_TYPE[
            json_type
        ]

        ### Try as a list
        type_list = list(type_iterable)
        assert isinstance(type_list, list)
        expectation_from_list = ExpectationConfiguration(
            EXPECTATION_TYPE, ExpectationKwargs(column=COLUMN, type_list=type_list),
        )
        list_json = convert_to_json_serializable(expectation_from_list)
        print(list_json)
        list_suite = ExpectationSuite("suite_list", expectations=expectation_from_list)
        assert isinstance(list_suite, ExpectationSuite)
        context.save_expectation_suite(list_suite)

        ### Try as a set
        type_set = set(type_iterable)
        assert isinstance(type_set, set)
        expectation_from_set = ExpectationConfiguration(
            EXPECTATION_TYPE, ExpectationKwargs(column=COLUMN, type_list=type_set),
        )
        set_json = convert_to_json_serializable(expectation_from_set)
        print(set_json)
        set_suite = ExpectationSuite("suite_set", expectations=expectation_from_set)
        assert isinstance(set_suite, ExpectationSuite)
        context.save_expectation_suite(set_suite)

        print(context.list_expectation_suite_names())


def attempt_each_json_type_together():
    print(
        "Attempting to save a suite an expectation for each json type in both list and set form."
    )

    list_expectations = []
    set_expectations = []
    for column in ["a", "b", "c"]:
        for (
            json_type
        ) in JsonSchemaProfiler.PROFILER_TYPE_LIST_BY_JSON_SCHEMA_TYPE.keys():
            print(f"Attempting json_type {json_type}")
            type_iterable = JsonSchemaProfiler.PROFILER_TYPE_LIST_BY_JSON_SCHEMA_TYPE[
                json_type
            ]

            ### Try as a list
            type_list = list(type_iterable)
            assert isinstance(type_list, list)
            expectation_from_list = ExpectationConfiguration(
                EXPECTATION_TYPE, ExpectationKwargs(column=column, type_list=type_list),
            )
            list_expectations.append(expectation_from_list)

            ### Try as a set
            type_set = set(type_iterable)
            assert isinstance(type_set, set)
            expectation_from_set = ExpectationConfiguration(
                EXPECTATION_TYPE, ExpectationKwargs(column=column, type_list=type_set),
            )
            set_expectations.append(expectation_from_set)
    list_suite = ExpectationSuite("suite_list", expectations=expectation_from_list)
    assert isinstance(list_suite, ExpectationSuite)
    context.save_expectation_suite(list_suite)
    set_suite = ExpectationSuite("suite_set", expectations=expectation_from_set)
    assert isinstance(set_suite, ExpectationSuite)
    context.save_expectation_suite(set_suite)

    print(context.list_expectation_suite_names())


if __name__ == "__main__":
    attempt_each_json_type_individually()
    attempt_each_json_type_together()
```

If you have thoughts on this I'm open to them.

2020-06-30 21:37 UTC, jcampbell approved these changes
Got it, that makes sense: normally the `ensure_json_serializable` is triggered during validation. Since there's no dataset at all, validation is never run, even in non-interactive mode, and hence the method is never run.

There is an open PR (@abegong ) that adds add/update methods onto the expectation suite itself, which should become the preferred method for this profiler once it's done. Let's merge this as is!

2020-06-30 21:37 UTC, merged

2020-06-30 22:34 UTC, Aylr commented
Thank you - I very much look forward to a standard API. That will enable some good fast work with profilers.