[ENHANCEMENT] updated default run_name in notebook to be a timestamp
fivetran/great_expectations pull request #1669
Opened 2020-07-07 17:42 UTC by talagluck

Changes proposed in this pull request:
- Changed the default run_name in the suite edit notebook to be a time stamp
- Changed the default run_name in the suite scaffold notebook to be a time stamp

The strftime conversion to string in the notebook feels feels a bit inelegant - I ran into issues with the action list validation operator when just using a datetime object so I went with that, but am open to other suggestions.

2020-07-08 21:57 UTC, Aylr requested changes
While we are here, I'm partial to removing this entire chunk of docs and run id so it gets a run time by default. It's less for the user to read and the point here isn't education.

2020-07-09 14:54 UTC, talagluck commented
@Aylr I removed the run_id, but force-pushed so I missed your other feedback. What else does this PR need?

2020-07-09 15:11 UTC, Aylr approved these changes
I love this. I've seen multiple users get lost in details in the suite edit notebook and this is a big step forward in simplicity!

2020-07-09 15:11 UTC, Aylr commented on great_expectations/render/notebook_assets/suite_edit/footer.py.j2
> -results = context.run_validation_operator("action_list_operator", assets_to_validate=[batch], run_id=run_id)
❤️ ❤️

2020-07-09 16:45 UTC, merged