[DOCS] How to host and share data docs on GCS
fivetran/great_expectations pull request #1674
Opened 2020-07-08 21:36 UTC by anthonyburdi

Changes proposed in this pull request:
- Update: How to host and share data docs on GCS
- Update: Expectation store on GCS warning about using a similar prefix

NOTE: Please make sure to carry the prefix warning over to the `How to configure a validation result store in gcs`

2020-07-08 22:24 UTC, Shinnnyshinshin requested changes
Just wanted to confirm that I'm not misunderstanding the doc. I found a few spots where 'Expectations' might need to be changed to 'DataDocs'.. am I right?

2020-07-08 22:24 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.rst
> +    - Identified the GCP project, GCS bucket, and prefix where Expectations will be stored.
Should this read "prefix where DataDocs will be stored." ?

2020-07-08 22:24 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.rst
> +    Check that your environment is configured with the appropriate authentication credentials needed to connect to the GCS bucket where Expectations will be stored.
Similar point. Expectations --> DataDocs?

2020-07-08 22:24 UTC, Shinnnyshinshin commented on docs/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.rst
> +    In our case, the name is set to ``gcs_site``, but it can be any name you like. We also need to make some changes to the ``store_backend`` settings.  The ``class_name`` will be set to ``TupleGCSSt
Expectations files  --> DataDocs?

2020-07-08 23:20 UTC, Shinnnyshinshin approved these changes

2020-07-09 06:25 UTC, roblim commented
@anthonyburdi - so sorry, I should have caught this sooner! The Data Docs GCS how to is already included in this PR: https://github.com/great-expectations/great_expectations/pull/1607 . I just needed to add a section on how to set up IP-Based access with App Engine, which I tested last Th. Wrapping that up now and saw this PR.

I really like some of the content in your PR though, and will incorporate parts in the other PR.

Again, so sorry you did duplicate work!

2020-07-09 15:25 UTC, anthonyburdi commented
> @anthonyburdi - so sorry, I should have caught this sooner! The Data Docs GCS how to is already included in this PR: #1607 . I just needed to add a section on how to set up IP-Based access with App Engine, which I tested last Th. Wrapping that up now and saw this PR.
> 
> I really like some of the content in your PR though, and will incorporate parts in the other PR.
> 
> Again, so sorry you did duplicate work! (The GCS Expectations Store docs are all good though.)

No worries at all! It was a good learning experience. I'll reassign the asana tasks to you then :)

2020-07-09 15:35 UTC, closed without merging

2020-07-09 15:37 UTC, anthonyburdi commented
@roblim I just closed this PR and leaving the branch for now but please feel free to delete it after you merge #1607