[DOCS] How to add comments to Expectations and display them in Data Docs
fivetran/great_expectations pull request #1682
Opened 2020-07-09 20:48 UTC by anthonyburdi

Changes proposed in this pull request:
- Add new How-to guide "How to add comments to Expectations and display them in Data Docs"

NOTE: I'll update the topic_id shortly
NOTE: I can add images of the examples if it would be helpful, please let me know!

2020-07-09 21:45 UTC, jcampbell requested changes
This looks great! Two changes to request:

1. Can you please put in a screenshot of the resulting beautifully-rendered notes?
2. Can you double-check the topic id in discourse? I get an error:

![image](https://user-images.githubusercontent.com/332575/87093938-035c5400-c20c-11ea-9e16-3f5bc360ce35.png)

2020-07-09 22:56 UTC, jcampbell approved these changes

2020-07-09 23:08 UTC, Shinnnyshinshin approved these changes

2020-07-10 14:13 UTC, anthonyburdi commented
dependabot merge

2020-07-10 15:51 UTC, anthonyburdi commented
@jcampbell [Required builds passed](https://travis-ci.org/github/great-expectations/great_expectations/builds/706895014) and I don't have permissions in TravisCI to re-start the build.

2020-07-10 17:07 UTC, merged