[FEATURE] Slack Messages now have Link to Expectation Suite
fivetran/great_expectations pull request #1707
Opened 2020-07-16 21:48 UTC by Shinnnyshinshin

Changes proposed in this pull request: 
- Add Link to ExpectationSuite in Slack notifications

2020-08-07 20:00 UTC, jcampbell submitted a review, later dismissed
1. Make name of the payload key configurable
2. Add changelog sentences describing payload feature
3. Add description of using payload to validation operators.rst

2020-08-10 23:09 UTC, Shinnnyshinshin commented
> 1. Make name of the payload key configurable
> 2. Add changelog sentences describing payload feature
> 3. Add description of using payload to validation operators.rst

Regarding 1, I tried this alternate approach: 

-  payload contains information about the class of the ValidationAction, and this is used to process the payload, regardless of the name set by user.

2020-08-11 05:04 UTC, roblim requested changes
Looking good! Just had a few comments regarding which URL to include in the Slack notification (validation result vs. index page) and some docs suggestions.

2020-08-11 05:04 UTC, roblim commented on great_expectations/validation_operators/actions.py
> +        return data_docs_index_pages
Since the purpose of the UpdateDataDocs action is to only render new validation results and not the entire Data Docs site(s), I think it makes more sense to return the actual URL of the rendered result, instead of just the index page. This will allow the Slack notification to have a URL that takes users directly to the actual validation result, instead of user having to go to index page first, then figuring out which validation result link to click.

Since you have access to the data_context and the validation_result_identifier here, you can generate the URL to the validation result by using the method `great_expectations.data_context.store.html_site_store.HtmlSiteStore.get_url_for_resource`, which can be called by the HTML site store. 

I think ideally, we probably want to update the return object of data_context.build_data_docs() so that it includes individual URLs if it was called with resource identifiers, which we can then use in UpdateDataDocsAction.

2020-08-11 05:04 UTC, roblim commented on great_expectations/render/renderer/slack_renderer.py
> +
Looks good. See my other comments regarding using validation result URL instead of index page URL here.

2020-08-11 05:04 UTC, roblim commented on great_expectations/validation_operators/validation_operators.py
> +
We should make it clear somewhere in docs that the order of actions is important, as the payload will only have the output payloads of previous actions.

2020-08-11 05:04 UTC, roblim commented on docs/reference/core_concepts/validation_operators_and_actions.rst
> +The only requirement from an action is for it to have a `run` method.  The `run` method will consume and return a `payload`, which can be used to pass information from one ValidationAction to another
Would be nice to have example input and output payloads or a worked out example

2020-08-12 05:55 UTC, roblim approved these changes
LGTM!

2020-08-12 16:00 UTC, merged