Alexsherstinsky/ms sql server support 07 07 2020
fivetran/great_expectations pull request #1717
Opened 2020-07-22 01:51 UTC by alexsherstinsky

- Microsoft SQL Server SQLLite Connection String
- Work around via temporary table for "Error 130: Cannot perform an aggregate function on an expression containing an aggregate or a subquery" -- this is a safe (single-table) and transactional (create and populate) implementation.
- Using "LIKE" and "NOT LIKE" pattern matching (since there is no Regular Expressions capability in Microsoft SQL Server; this requires further discussion (e.g., allow the same "expect_column_values_to__regex<_type>" expectation to remain, but document the API to explain how it will behave in the special case of the Microsoft SQL Server).
- Introducing docker-compose.yml in order to be able to test against a local instance of Microsoft SQL Server
- Solutions for schema differences:
   - "BOOLEAN" --> "BIT"
   - Stings with NULL values -> "NVARCHAR"
   - Floating point "Infinity" -> 1.79e308
- Tests have been updated and pass.

Notable Omission: No CLI yet; it will be added upon the merging of the present pull request. In the mean time, use the current CLI interface and enter the connection string at the prompt for the "Other SQLAlchemy Engine" option:

```
"mssql+pyodbc://user:password@host:port/database?driver=ODBC Driver 17 for SQL Server&charset=utf8&autocommit=true"
```

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. closes #123).
After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

2020-07-22 14:04 UTC, Aylr commented
This is an exciting and big PR! To split up the work of reviewing this PR, I’m going to do a thorough test of this PR branch on a real dataset in the wild and will leave a detailed code review for someone else.

I’ll verify use of everything in the description and these open MSSQL issues: https://github.com/great-expectations/great_expectations/issues?q=is%3Aissue+is%3Aopen+mssql+

2020-07-24 22:27 UTC, Aylr commented on .travis.yml
> +#        - black --check --exclude docs/ .
Is this intentional?

2020-07-24 22:28 UTC, alexsherstinsky commented on .travis.yml
> +#        - black --check --exclude docs/ .
Yes -- per @jcampbell

2020-07-24 23:21 UTC, Aylr requested changes
Pending another acceptance test for latest temp table error. We are getting so close!

2020-07-24 23:21 UTC, Aylr commented on requirements-dev-build.txt
> +# Otherwise (i.e., if/when you are not concerned with running tests), please ignore these comments.
❤️ ❤️

2020-07-24 23:21 UTC, Aylr commented on tests/test_utils.py
> +        if not create_engine:
❤️

2020-07-24 23:21 UTC, Aylr commented on .travis.yml
> +#        - black --check --exclude docs/ .
Answered: Yes.

2020-07-27 16:02 UTC, Aylr commented
FYI I'm actively giving this another round of acceptance testing on a big MSSQL server this morning.

2020-07-27 23:18 UTC, Aylr approved these changes

2020-07-27 23:24 UTC, merged