[FEATURE] Add PagerdutyAlertAction
fivetran/great_expectations pull request #1955
Opened 2020-10-05 11:44 UTC by NiallRees

Changes proposed in this pull request:
- Add a PagerdutyAlertAction

I've just made this custom alert for my instance of great expectations, and thought it might be valuable to others. Happy to write some docs for this, but thought it would be good to get general feedback first.

2020-10-05 21:25 UTC, eugmandel commented
@NiallRees I am so happy to see this PR - love the idea of the community contributing more notification mechanisms. 

Will give it a thorough review later today.

2020-10-06 00:28 UTC, eugmandel requested changes
@NiallRees Can't wait to get this one merged! My only change request is to make pypd an optional dependency - please see my comment and edit suggestions.

2020-10-06 00:28 UTC, eugmandel commented on great_expectations/validation_operators/actions.py
> +
```suggestion
try:
    import pypd
except ImportError as e:
    pypd = None

```

2020-10-06 00:28 UTC, eugmandel commented on great_expectations/validation_operators/actions.py
> +        super().__init__(data_context)
```suggestion
        super().__init__(data_context)
        if not pypd:
            raise DataContextError(
                "ModuleNotFoundError: No module named 'pypd'"
            )
```

2020-10-06 00:28 UTC, eugmandel commented on requirements.txt
> +pypd==1.1.0  # package
Let's not make pypd a requirement for all the users who are not PagerDuty customers. Please move this line from `requirements.txt` to `requirements-dev.txt` that are required for the tests to pass. Also, see my edit suggestions in the action implementation that make sure that the pypd module is optional.

2020-10-06 12:17 UTC, NiallRees commented
Nice solution on the dependency. I was wondering how best to handle that

2020-10-06 15:21 UTC, eugmandel approved these changes
@NiallRees Thank you for making the changes - approving and merging!

2020-10-06 15:21 UTC, merged