[ENHANCEMENT] [DOCS] Updating requirementstxt
fivetran/great_expectations pull request #2052
Opened 2020-11-17 02:00 UTC by shapiroj18

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Updated requirements-dev-test.txt to not include black, which avoids error when pip installing requirements-dev.txt. 
- Added instructions in docs to manually import black if only installing requirements-dev-test.txt.'

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

2020-11-17 02:01 UTC, shapiroj18 commented
Fixes https://github.com/great-expectations/great_expectations/issues/2028. I thought this approach worked slightly better.

2020-11-17 02:02 UTC, shapiroj18 commented
@cla-bot check

2020-11-17 17:29 UTC, eugmandel commented
@shapiroj18 Thank you for submitting! We will review this week.

2020-12-17 23:06 UTC, anthonyburdi requested changes
Hi @shapiroj18 !!
My sincere apologies at not seeing your PR before upgrading black in #2183. I saw the issue and just missed the link to the PR. It looks like you came to the same conclusion to remove it from the `requirements-dev-test.txt` file. I love the addition of the note to manually install in the docs.
I would still love to merge your PR including the docs update, would you mind addressing my comments and merging in the `develop` branch or the `anthony/bugfix/user-dev-env-issues` if it hasn't been merged in yet?
Thank you for the contribution!

2020-12-17 23:06 UTC, anthonyburdi commented on docs/contributing/setting_up_your_dev_environment.rst
> +      * Note that you can also substitute ``requirements-dev-test.txt`` to only install requirements required for testing all backends (please also manually ``pip install black==19.10b0``), and ``req
```suggestion
      * Note that you can also substitute ``requirements-dev-test.txt`` to only install requirements required for testing all backends (please also manually ``pip install black==20.8b1``), and ``requirements-dev-spark.txt`` or ``requirements-dev-sqlalchemy.txt`` if you would like to add support for spark or sqlalchemy tests, respectively. For some database backends, such as MSSQL additional driver installation may required in your environment; see below for more information.
```

2020-12-17 23:06 UTC, anthonyburdi commented on docs/changelog.rst
> +* [BUGFIX] Updated develop environment requirements
```suggestion
* [BUGFIX] Updated development environment requirements (Thanks @shapiroj18!)
```

2020-12-17 23:06 UTC, anthonyburdi commented on requirements-dev.txt
> +--requirement requirements-dev-publish.txt
This is strange, I don't see a change here. Would you mind terribly removing this to avoid confusion later?

2020-12-17 23:06 UTC, anthonyburdi commented on requirements-dev-test.txt
> -black==19.10b0  # lint
👍 👍 👍  I came to the same conclusion in #2183 Apologies that I missed your PR before creating it.

2020-12-18 15:43 UTC, anthonyburdi commented
@shapiroj18 after further consideration and input from @jcampbell, I've removed `black` from `requirements.txt` and made import optional in #2183. I've replaced it in `requirements-dev-test.txt` so that it is available to contributors for pre-commit hooks and running local tests.
I hope that makes sense. I really appreciate your contribution (this one and others you've made!) so I am hesitant to close this pr without merging but I think it is the right move.

2020-12-18 15:43 UTC, closed without merging

2020-12-18 15:49 UTC, shapiroj18 commented
@anthonyburdi thanks for reaching out! All makes sense to me, let me know if you need anything else.