[ENHANCEMENT] Add an 'allow_extra' argument to ignore additional colu…
fivetran/great_expectations pull request #2200
Opened 2020-12-20 20:15 UTC by colmsnowplow

…mns in expect_table_columns_to_match_ordered_list

Adds an optional argument to expect_table_columns_to_match_ordered_list, which allows the target table to have additional columns to those speicified in the expectation list.

If this is set to True, the expectation will pass validation if the first n columns of the table (where n is the length of the provided list) passes the validation.

Changes proposed in this pull request:
- Adds 'allow_extra' to ignore additional columns for expect_table_columns_to_match_ordered_list

Previous Design Review notes:
- Slack: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1607956485121300
- Discuss: https://discuss.greatexpectations.io/t/can-i-validate-a-list-of-predefined-columns-and-ignore-the-rest/563/2

2020-12-20 20:43 UTC, colmsnowplow commented
Not sure what to make of those failing CI tests... Would appreciate some guidance (if the approach seems sensible of course).

2020-12-20 23:28 UTC, eugmandel commented
@colmsnowplow Thank you for opening this PR! I recognize the Slack conversation this is based on. We will review the PR next week.

2020-12-21 21:29 UTC, eugmandel requested changes
@colmsnowplow Seeing users of Great Expectations create PRs that enrich the library of expectations is one of the most rewarding experiences for the core contributors!

We noticed that adding extra arguments to a particular expectation can be somewhat of an anti-pattern. Here is why - the vision for Great Expectations is to be a language system where any statement about data, stated in a natural language, can be translated into a formal, machine-verifiable statement. Having expectations with very constrained meaning makes it easier. Extra arguments increase the expressivity of an expectation, while removing its constrained property.

Specifically, instead of adding the `allow_extra` argument to `expect_table_columns_to_match_ordered_list`, I would prefer a new expectation that expresses exactly your use case - something like expect_table_columns__to_be_at_certain_positiions. The argument would likely be a list of column names and their expected location (index).

Would you be interested to create this expectation?

2020-12-29 19:20 UTC, colmsnowplow commented
Hey @eugmandel, thanks for the feedback! Hope you're enjoying the holidays (am responding now as I have spare time, happy to wait for responses).

That all sounds sensible to me, I can play around with creating a distinct expectation for this (without making any promises on promptness - am just chipping away in my few spare moments). Will probably close this PR and open a new one to do so but can use this convo to check assumptions.

Off the top of my head here's what instrumentation of a `expect_table_column_names_to_be_at_positions` probably looks like in pseudo-python:


Input:

```python
input_list = [
  {
    "position": 1,
    "name": "first_column"
  },
  {
    "position": 3,
    "name": "third_column"
  }
]

expected_namelist = [i["name"] for i in sorted(input_list, key = lambda i: i['position'])]

# Not sure how clear this is - the idea is to produce a list of the values for "name", ordered by the values for "position"

["first_column", "third_column"]


expected_indices = [i["position"] for i in input_list]

# (Produce list of just values for 'position')

[1, 3]


columns_at_positions = [get_table_columns()[i - 1] for i in expected_indices] 

# (index is i - 1 assuming input isn't zero-based positions - see below)

# Using existing get_table_columns() method as instrumenting a new method to get only the columns we care about seems like overkill for this?
```

Then it passes if `expected_namelist === columns_at_positions`.


---

If anything seems off about this let me know. Input feels clunky but at least is declarative of what it is.

If that all does seem reasonable, then I'm unsure if it makes most sense for the positions to begin at 1 or 0. For a SQL table, intuitively it's 1-based but for a python object it's 0-based.

2021-02-04 16:56 UTC, spbail commented
Hi @colmsnowplow! We'd love to follow up on this! I just want to make sure I understand your pass/fail cases - super pseudo code:
table: [col_a, col_b, col_c, col_d, col_e)
* my_expectation([col_a, col_b, col_c, col_d, col_e): passes because exact match
* my_expectation([col_a, col_b, col_c): passes because the table column list starts with this and has extra columns
* my_expectation([col_a, col_b, col_d, col_e): fails because it's not an exact sublist? (could you clarify?)
* my_expectation([col_a, col_x, col_b, col_c): also fails because it's not an exact sublist?

2021-03-09 16:18 UTC, colmsnowplow commented
Hey @spbail - apologies for the long delay, I got super busy and lost sight of this. If you're still interested in the answer:

> my_expectation([col_a, col_b, col_c, col_d, col_e): passes because exact match

Correct

> my_expectation([col_a, col_b, col_c): passes because the table column list starts with this and has extra columns

Correct

> my_expectation([col_a, col_b, col_d, col_e): fails because it's not an exact sublist? (could you clarify?)

Fails because the list provided is expected to match in order. Since there's a col_c in the table at position 3, it doesn't match.

> my_expectation([col_a, col_x, col_b, col_c): also fails because it's not an exact sublist?

Fails because col_x doesn't exist in the table.


I think overall I agree with the sentiments of the previous comments from Eugene - what I've specified here isn't necessarily intuitive, and actually the better definition of the expectation is probably that we explicitly expect columns at given positions to have specified names. So I'm not tied to what I've done here by any means :)

2021-03-16 21:56 UTC, spbail commented
@colmsnowplow Thanks for the response! I think your use case makes sense, and I agree with Eugene that might be better suited for a new expectation. I'll close this PR, but feel free to keep working on the expectation!

2021-03-16 21:56 UTC, closed without merging