[DOCS] Add a Spark DataFrame example
fivetran/great_expectations pull request #2204
Opened 2020-12-21 18:03 UTC by chengyineng38

Changes proposed in this pull request:
- Add a Spark DataFrame example. This brings visibility to the SparkDFDataset API.

2020-12-21 23:56 UTC, eugmandel commented
@chengyineng38 Thank you for submitting! Will review in the next day or so.

2020-12-22 18:36 UTC, eugmandel requested changes, later dismissed
Great edit, @chengyineng38 ! Please accept my suggestion edit, and we will get the PR in.

2020-12-22 18:36 UTC, eugmandel commented on docs/guides/tutorials/explore_expectations_in_a_notebook.rst
> +    This method will convert your ``Spark DataFrame`` into a class with access to Great Expectations' methods, such as ``ProfilingResultsPageRenderer``.
```suggestion
    This method will create an object with access to Great Expectations' methods, such as ``ProfilingResultsPageRenderer``.
```

2020-12-22 18:36 UTC, eugmandel commented on docs/guides/tutorials/explore_expectations_in_a_notebook.rst
> +    This method will convert your ``Spark DataFrame`` into a class with access to Great Expectations' methods, such as ``ProfilingResultsPageRenderer``.
The "convert" language is correct for Pandas, but not precise for Spark DataFrames.

2020-12-22 19:18 UTC, chengyineng38 commented
Great suggestion. Just accepted the edit suggestion.

2020-12-22 19:54 UTC, chengyineng38 commented
> Great edit, @chengyineng38 ! Please accept my suggestion edit, and we will get the PR in.

@eugmandel hmm not sure why your suggestion edit resulted in assertion error?

2020-12-22 21:25 UTC, eugmandel commented
> > Great edit, @chengyineng38 ! Please accept my suggestion edit, and we will get the PR in.
> 
> @eugmandel hmm not sure why your suggestion edit resulted in assertion error?

@chengyineng38 This looks like an intermittent failure of the Azure pipeline CI - no action is required on your part.

2021-02-02 21:32 UTC, spbail approved these changes
lgtm

2021-02-02 21:33 UTC, merged