[ENHANCEMENT] Add timestamp tests for ExpectColumnValuesToBeBetween.
fivetran/great_expectations pull request #2419
Opened 2021-02-09 05:31 UTC by victorwyee

Changes proposed in this pull request:
- Refactors `ExpectColumnValuesToBeBetween` to use config validation code from grandparent `TableExpectation` class.
- Adds two unit tests for `ExpectColumnValuesToBeBetween` with `parse_strings_as_datetimes=true`.
- Attempts to reproduce #2341

2021-02-09 06:09 UTC, victorwyee commented
Well, `pytest tests/test_definitions/test_expectations.py` passed fine, but upon inspection of the build failures here, I see that running `pytest --no-postgresql --no-spark --no-sqlalchemy` also produces the same errors

Namely

```
>           raise InvalidExpectationConfigurationError(str(e))
E           great_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: Provided min threshold must be a number

/opt/projects/great_expectations/great_expectations/expectations/expectation.py:1106: InvalidExpectationConfigurationError
```

and

```
>           raise InvalidExpectationConfigurationError(str(e))
E           great_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: min_value and max_value cannot both be None
```

2021-02-09 06:10 UTC, victorwyee commented on great_expectations/expectations/expectation.py
> +            assert (
I wasn't expecting this to break a bunch of stuff. This seems like a reasonable assertion.

2021-02-09 08:16 UTC, victorwyee commented on great_expectations/util.py
> +        parsed_date: datetime = parse(value, fuzzy=fuzzy)
I'm not sure if how well strings that `datetime.parse` can parse will align with the various engines that the datetime string will be fit into. But this seems to work for pandas.

2021-02-10 06:18 UTC, victorwyee commented
`pytest --no-postgresql --no-spark --no-sqlalchemy tests/test_definitions/test_expectations_cfe.py` passes locally, so I suspect at least one engine is returning dates in a different format and/or causing the comparison(s) to fail. Planning on installing the other backends soon to try to reproduce locally and get a fix in.

2021-02-10 16:11 UTC, spbail commented
@victorwyee Howdy! Thanks for the contribution! Mind marking this as draft while you're still working on it? Also, feel free to ping us in Slack if you'd like some help with the failing tests. (We're doing an all-hands this week so might be a little less responsive though.)

2021-02-11 08:01 UTC, victorwyee commented
Was able to repro the failing test after installing Spark locally and running `pytest tests/test_definitions/test_expectations_cfe.py`. Tests pass with pandas, postgres, and sqlalchemy/mysql backends.

2021-02-17 19:05 UTC, Shinnnyshinshin commented
HI @victorwyee. First, thank you for putting together this elegant PR. Your solution that uses `datetime.parse` seems to work well for all the backends that GE currently supports. There is only test that seems to be failing only for the `spark` backend, and it can (AFIK) be addressed by adding the `parse_strings_as_datetimes` logic to to the `_spark` fixture in the `column_values_between.py` metric. 

Let me know the following works for you 

`@column_condition_partial(engine=SparkDFExecutionEngine)
    def _spark(
        cls,
        column,
        min_value=None,
        max_value=None,
        strict_min=None,
        strict_max=None,
        parse_strings_as_datetimes=None,
        **kwargs
    ):
        if parse_strings_as_datetimes:
            if min_value:
                min_value = parse(min_value)
            if max_value:
                max_value = parse(max_value)`

2021-02-17 21:18 UTC, Shinnnyshinshin requested changes
Once we get the test passing for spark I think we should be good to go

2021-02-18 04:47 UTC, victorwyee commented
> HI @victorwyee. First, thank you for putting together this elegant PR. Your solution that uses `datetime.parse` seems to work well for all the backends that GE currently supports. There is only test that currently fails for the `spark` backend, and it can (AFIK) be addressed by adding the `parse_strings_as_datetimes` logic to to the `_spark` fixture in the `column_values_between.py` metric.
> 
> Let me know the following works for you
> 
> ```
> @column_condition_partial(engine=SparkDFExecutionEngine)
>     def _spark(
>         cls,
>         column,
>         min_value=None,
>         max_value=None,
>         strict_min=None,
>         strict_max=None,
>         parse_strings_as_datetimes=None,
>         **kwargs
>     ):
>         if parse_strings_as_datetimes:
>             if min_value:
>                 min_value = parse(min_value)
>             if max_value:
>                 max_value = parse(max_value)
> ```

Thanks! I decided to take the `datetime.parse` approach partly because it's already used in many other places in `great_expectations`, and I generally prioritize consistency in a codebase. It helps that it works well for all supported engines too.

On adding the support for Spark, the solution is obvious now, but I couldn't find it at first glance. Thanks for the pointer! All tests pass on my local now for all engines. :)

2021-02-18 04:56 UTC, victorwyee commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> -                min_val is not None or max_val is not None
I couldn't get this assertion to work for `tests/test_definitions/test_expectations_cfe.py`. There're several cases where the test runner thinks that `min_val` and `max_val` are both None.

2021-02-18 18:01 UTC, Shinnnyshinshin commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> -                min_val is not None or max_val is not None
Hi @victorwyee I'm actually having some trouble re-creating this error on my end. Does the error persist with the following code? (they should be testing the same condition)

`
assert any([min_val, max_val]), "min_value and max_value cannot both be None"
`

2021-02-18 18:54 UTC, victorwyee commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> -                min_val is not None or max_val is not None
Yes, adding this assertion still fails on my end. Note that this wasn't in the original configuration validation function before -- just in this specific expectation (which I've refactored).

This is what I get

```
=============================================== short test summary info ================================================
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_map_expectations/expect_column_values_to_be_between:missing_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_map_expectations/expect_column_values_to_be_between:null_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_map_expectations/expect_column_values_to_be_between:missing_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_map_expectations/expect_column_values_to_be_between:null_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_map_expectations/expect_column_values_to_be_between:missing_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_map_expectations/expect_column_values_to_be_between:null_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[postgresql/column_map_expectations/expect_column_values_to_be_between:missing_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[postgresql/column_map_expectations/expect_column_values_to_be_between:null_max_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_stdev_to_be_between:vacuously_true]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_stdev_to_be_between:positive_zero_stdev_exact_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_max_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_mean_to_be_between:simple_mean_includes_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_mean_to_be_between:vacuously_true_missing_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_mean_to_be_between:type_mismatch_null_observed_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_unique_value_count_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_median_to_be_between:vacuously_true_both_min_and_max_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_median_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_min_to_be_between:negative_test_case_with_only_a_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[pandas/column_aggregate_expectations/expect_column_proportion_of_unique_values_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_stdev_to_be_between:vacuously_true]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_stdev_to_be_between:positive_zero_stdev_exact_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_max_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_mean_to_be_between:simple_mean_includes_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_mean_to_be_between:vacuously_true_missing_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_mean_to_be_between:type_mismatch_null_observed_value]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_unique_value_count_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_median_to_be_between:vacuously_true_both_min_and_max_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_median_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_min_to_be_between:negative_test_case_with_only_a_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[spark/column_aggregate_expectations/expect_column_proportion_of_unique_values_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_max_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_mean_to_be_between:simple_mean_includes_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_mean_to_be_between:vacuously_true_missing_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_unique_value_count_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_median_to_be_between:vacuously_true_both_min_and_max_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_median_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_min_to_be_between:negative_test_case_with_only_a_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[sqlite/column_aggregate_expectations/expect_column_proportion_of_unique_values_to_be_between:vacuously_true_null_min_and_max]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[postgresql/column_aggregate_expectations/expect_column_max_to_be_between:test_empty_column_should_be_false_no_observed_value_with_which_to_compare]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[postgresql/column_aggregate_expectations/expect_column_mean_to_be_between:simple_mean_includes_null]
FAILED tests/test_definitions/test_expectations_cfe.py::test_case_runner_cfe[postgresql/column_aggregate_expectations/expect_column_mean_to_be_between:vacuously_true_missing_min_and_max]
FAILED tests/test_defini [...]

2021-02-18 23:19 UTC, Shinnnyshinshin commented on tests/test_definitions/column_map_expectations/expect_column_values_to_be_between.json
> +      {
```suggestion
        {
        "title" : "null_min_max_value",
        "exact_match_out": false,
        "out": {
          "traceback_substring": "min_value and max_value cannot both be None"
        },
        "in": {
          "column": "x",
          "min_value": null,
          "max_value": null,
          "catch_exceptions": true
        }
      },
      {
```

2021-02-18 23:20 UTC, Shinnnyshinshin commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> -
`      if configuration is None:
            configuration = self.configuration

        min_val = None
        max_val = None
        # Setting these values if they are available
        if "min_value" in configuration.kwargs:
            min_val = configuration.kwargs["min_value"]

        if "max_value" in configuration.kwargs:
            max_val = configuration.kwargs["max_value"]
        try:
            # Ensuring Proper interval has been provided
            assert (
                min_val is not None or max_val is not None
            ), "min_value and max_value cannot both be None"
        except AssertionError as e:
            raise InvalidExpectationConfigurationError(str(e))
`

2021-02-18 23:46 UTC, Shinnnyshinshin commented
hi @victorwyee I got a chance to do some digging this afternoon and (I think) figured out why the assertion was failing. 

The expectation `ExpectColumnValuesToBeBetween ` behaves a little differently from other expectations that use the `validate_metric_value_between_configuration()` function.  Other expectations of this type include `expect_column_mean_to_be_between` and `expect_column_median_to_be_between`,  and they support a `vacuously_true` condition, which means the expectation will pass if the min/max values not set `null`. These were the tests that were failing when we added the assertion to  `validate_metric_value_between_configuration()`

In the case of this PR I think we can try the following 2 thing to ensure `ExpectColumnValuesToBeBetween` behaves consistently with the existing code.

1) re-add the following assertion to `great_expectations/expectations/core/expect_column_values_to_be_between.py`

```
 assert (
            min_val is not None or max_val is not None
        ), "min_value and max_value cannot both be None"
```

2) adding a test for the situation where both the min_value and max_value are `None` to `expect_column_values_to_be_between.json`

I've added 2 suggestions for the changes.  Could you have a look and let me know what you think?  I was able to get the tests to pass locally.

2021-02-22 20:53 UTC, Shinnnyshinshin commented
Hi @victorwyee I just wanted to follow up on this PR. This is a great fix for the issue, and we're excited to have it be part of the codebase. If you're not able to able to get to the remaining suggestions in the next few days (let's say 2/24/21?) would it be ok if I got it over the line?  You've basically done 90% of the work, so it would be a minor tweak on my end.

2021-02-22 22:38 UTC, victorwyee commented
Oh definitely planning on closing this out today or tomorrow. Sorry I
didn't get to this at the end of last week! Will work on this in a few
hours 😄

On Mon, Feb 22, 2021, 12:53 PM William Shin <notifications@github.com>
wrote:

> Hi @victorwyee <https://github.com/victorwyee> I just wanted to follow up
> on this PR. This is a great fix for the issue, and we're excited to have it
> be part of the codebase. If you're not able to able to get to the remaining
> suggestions in the next few days (let's say 2/24/21?) would it be ok if I
> got it over the line? You've basically done 90% of the work, so it would be
> a minor tweak on my end.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/great-expectations/great_expectations/pull/2419#issuecomment-783667602>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHZEL26OXPKMWLIO54K2R3TAK74RANCNFSM4XKKJ3FA>
> .
>

2021-02-23 20:41 UTC, Shinnnyshinshin approved these changes
Thank you very much 🚀 LGTM

2021-02-23 20:42 UTC, Shinnnyshinshin commented
@victorwyee I just approved, and will merge once tests pass. Thank you very much for your contribution here, and I hope we get to work again in the future :) have a great one!

2021-02-24 01:17 UTC, Shinnnyshinshin commented
A small update : currently our CI pipelines are failing for reasons that are un-related to your PR. We'll merge as soon as it gets cleared up :)

2021-02-24 01:33 UTC, victorwyee commented
> A small update : currently our CI pipelines are failing for reasons that are un-related to your PR. We'll merge as soon as it gets cleared up :)

Yeah, I took a look and saw the timeouts earlier. Thanks for the update!

2021-02-24 19:28 UTC, merged