[ENHANCEMENT]+[BUGFIX] added support for databricks dialect if using databricks-dbapi sqlalchemy
fivetran/great_expectations pull request #2436
Opened 2021-02-13 20:12 UTC by utkarshshukla2912

Changes proposed in this pull request:
- While using custom sql for databricks through databricks-dbapi sqlalchemy, a temporary table is created which leads to an error since temporary table is not supported by spark, context around it [here](https://issues.apache.org/jira/browse/SPARK-14651), but temporary view is. Hence have added dialect support for databricks which works on temporary views rather than temporary tables.

- Added the below code since when using databricks `self.sql_engine_dialect.name.lower()` a byte string was being returned. 
```
engine_dialect = self.sql_engine_dialect.name.lower()
        if type(engine_dialect) != str:
            engine_dialect = str(engine_dialect, "utf-8")
```

2021-03-08 04:44 UTC, eugmandel commented
@utkarshshukla2912 The PR is in review and @roblim is handling it.

2021-03-09 02:38 UTC, roblim requested changes
Looks good to me. Just had one stylistic suggestion. Thanks so much for your contribution!

2021-03-09 02:38 UTC, roblim commented on great_expectations/dataset/sqlalchemy_dataset.py
> +        if engine_dialect == "bigquery":
```suggestion
        engine_dialect = self.sql_engine_dialect.name.lower()
        # handle cases where dialect.name.lower() returns a byte string (e.g. databricks)
        if isinstance(engine_dialect, bytes):
            engine_dialect = str(engine_dialect, "utf-8")

        if engine_dialect == "bigquery":
```

Stylistically, we prefer using `isinstance` to check types, vs. the `type(x) == y` or `type(x) != y` pattern.

2021-03-09 02:38 UTC, roblim commented on great_expectations/dataset/sqlalchemy_dataset.py
> +        if engine_dialect == "bigquery":
Also suggest adding comment for clarity.

2021-03-10 13:31 UTC, utkarshshukla2912 commented
@roblim have added your suggestions, and updated with the latest develop branch.

2021-03-11 19:58 UTC, roblim approved these changes

2021-03-11 19:58 UTC, merged