[ENHANCEMENT] Allows gzipped files and other encodings to be read from S3
fivetran/great_expectations pull request #2440
Opened 2021-02-15 16:31 UTC by luke321321

Changes proposed in this pull request:
- Allow gzipped files (and other encodings) to be read from S3 using pandas.  Instead of decoding directly to `StringIO` we let pandas to do the decoding implicitly for us.
- Refactored some S3 pandas tests & added test for the above
- Removed redundant S3 pandas test - the test was a duplicate (this can be added back or fixed but I'm unsure how this part of the GE API works.  Should be quick for someone familiar to correct this test & add back in now)

Note for some reason using the `pd.testing.assert_frame_equals` wasn't working for me and I'm not sure why.  I've just left the test and checking the shapes are equal but this can be improved some what.

2021-02-17 15:37 UTC, eugmandel commented
This looks like a great enhancement, @luke321321 ! Adding the review queue - we will get to this within a couple of days.

2021-02-17 16:14 UTC, luke321321 commented
Note happy to refactor `sniff_s3_compression()` to use a dictionary instead like:
```python
def sniff_s3_compression(s3_url: S3Url) -> str:
    """Attempts to get read_csv compression from s3_url"""
    suffix = s3_url.suffix
    suffix_to_kwarg = {"gz" : "gzip", ... }
    return suffix_to_kwarg.get(suffix, "infer")
```

2021-02-17 16:41 UTC, luke321321 commented
i've actually refactored for the above as I think it's easier to read, test & extend.  Functionality is identical.

2021-02-17 20:09 UTC, luke321321 commented
☝️  note test failure comes from a different part of the repo from a flakey test (`test_send_malformed_data`)

2021-02-19 22:12 UTC, roblim requested changes
Looks awesome @luke321321! Turns out the duplicate test was meant to be filled out but wasn't - great catch! I went ahead and added the completed test back inline with my review. 

Would you mind just taking care of the new merge conflicts? Once the checks are passing again, we can approve/merge. Thanks so much!

2021-02-19 22:12 UTC, roblim commented on tests/execution_engine/test_pandas_execution_engine.py
```suggestion
from botocore.errorfactory import ClientError
from moto import mock_s3

```

2021-02-19 22:12 UTC, roblim commented on tests/execution_engine/test_pandas_execution_engine.py
>  import great_expectations.exceptions.exceptions as ge_exceptions
```suggestion
import great_expectations.exceptions.exceptions as ge_exceptions
from great_expectations.core.batch import BatchDefinition
```

2021-02-19 22:12 UTC, roblim commented on tests/execution_engine/test_pandas_execution_engine.py
>  from great_expectations.datasource.types.batch_spec import (
```suggestion
from great_expectations.core.id_dict import PartitionDefinition
from great_expectations.datasource.types.batch_spec import (
```

2021-02-19 22:12 UTC, roblim commented on tests/execution_engine/test_pandas_execution_engine.py
>          "directory/B-2.csv",
```suggestion
        "directory/B-2.csv",
        "alpha-1.csv",
        "alpha-2.csv",
```

2021-02-19 22:12 UTC, roblim commented on tests/execution_engine/test_pandas_execution_engine.py
> +@pytest.fixture
```suggestion
            batch_spec=batch_with_split_on_whole_table_s3
        )


def test_get_batch_with_split_on_whole_table_s3_with_configured_asset_s3_data_connector(test_s3_files, test_df_small):
    bucket, _keys = test_s3_files
    expected_df = test_df_small

    my_data_connector = ConfiguredAssetS3DataConnector(
        name="my_data_connector",
        datasource_name="FAKE_DATASOURCE_NAME",
        default_regex={
            "pattern": "alpha-(.*)\\.csv",
            "group_names": ["index"],
        },
        bucket=bucket,
        prefix="",
        assets={"alpha": {}},
    )
    batch_def = BatchDefinition(
        datasource_name="FAKE_DATASOURCE_NAME",
        data_asset_name="alpha",
        data_connector_name="my_data_connector",
        partition_definition=PartitionDefinition(index=1),
        batch_spec_passthrough={
            "reader_method": "read_csv",
            "splitter_method": "_split_on_whole_table",
        },
    )
    test_df = PandasExecutionEngine().get_batch_data(
        batch_spec=my_data_connector.build_batch_spec(batch_definition=batch_def)
    )
    assert test_df.dataframe.shape == expected_df.shape

    # if key does not exist
    batch_def_no_key = BatchDefinition(
        datasource_name="FAKE_DATASOURCE_NAME",
        data_asset_name="alpha",
        data_connector_name="my_data_connector",
        partition_definition=PartitionDefinition(index=9),
        batch_spec_passthrough={
            "reader_method": "read_csv",
            "splitter_method": "_split_on_whole_table",
        },
    )
    with pytest.raises(ClientError):
        PandasExecutionEngine().get_batch_data(
            batch_spec=my_data_connector.build_batch_spec(
                batch_definition=batch_def_no_key
            )
        )


@pytest.fixture
```

2021-02-22 14:22 UTC, luke321321 commented
Hi @roblim thanks for adding that test back in.  I've fixed the merge conflicts.

2021-02-22 17:27 UTC, roblim approved these changes
Thanks @luke321321 - looks great!

2021-02-22 17:27 UTC, merged