[BUGFIX] Display run time in ISO datetime format. Fixes #2475
fivetran/great_expectations pull request #2476
Opened 2021-02-25 10:40 UTC by miike

Changes proposed in this pull request:
- Modify run time from US date format to ISO date format

Related conversation in Slack: https://greatexpectationstalk.slack.com/archives/CUW3WD6PK/p1614037781005900

2021-03-02 17:33 UTC, eugmandel requested changes
@miike Thank you for spotting this inconsistency! One change request - could you please use this ISO format: "%Y%m%dT%H%M%S.%fZ"? We are using it in all other cases.

2021-03-02 23:22 UTC, miike commented
> "%Y%m%dT%H%M%S.%fZ"

Although this is consistent with the rest of the codebase I'm a little hesitant to use the basic format at the moment. The main reasons being:
- It's less readable than ISO8601 extended (i.e., with delimiters) and the ISO standard recommends against it
>The basic format should be avoided in plain text
- UTC is useful, and probably the most appropriate timezone to use here but I suspect the user may prefer / expect to see their local time zone here

I think a compromise might be to instead of a single column to add two columns here, one with run time in ISO8601 basic format for debugging purposes and another that localises the run time and renders as the extended format with the local timezone.

2021-03-03 21:31 UTC, eugmandel commented
> > "%Y%m%dT%H%M%S.%fZ"
> 
> Although this is consistent with the rest of the codebase I'm a little hesitant to use the basic format at the moment. The main reasons being:
> 
> * It's less readable than ISO8601 extended (i.e., with delimiters) and the ISO standard recommends against it
> 
> > The basic format should be avoided in plain text
> 
> * UTC is useful, and probably the most appropriate timezone to use here but I suspect the user may prefer / expect to see their local time zone here
> 
> I think a compromise might be to instead of a single column to add two columns here, one with run time in ISO8601 basic format for debugging purposes and another that localises the run time and renders as the extended format with the local timezone.

@miike Good point - will approve and merge.

2021-03-03 21:32 UTC, eugmandel approved these changes

2021-03-04 04:21 UTC, merged