[FEATURE] Added support for references to secret managers (AWS Secrets Manager, GCP Secret Manager, Azure Key Vault)
fivetran/great_expectations pull request #2485
Opened 2021-03-01 00:39 UTC by Cedric-Magnan

Changes proposed in this pull request:
- Added secrets store reference substitution in `great_expectations.yml` file after all other variable substitutions
- Added documentation on how to reference the secrets for each secret store
- Added unit tests on the secret store methods

Here is an example on how to reference the secrets on AWS Secrets Manager :
![image](https://user-images.githubusercontent.com/43343135/109439484-c5c46980-7a2e-11eb-9586-01fcd80b221b.png)

2021-03-02 00:56 UTC, eugmandel commented
Thank you for submitting this PR, @Cedric-Magnan ! We will review it this week.

2021-03-17 22:52 UTC, Shinnnyshinshin requested changes
@Cedric-Magnan Overall this is a wonderful feature that we're excited to include in GE. Thank you also for including the (very thorough) how-to-doc, which is going to be a great resource 👍🏼 

After a few tweaks (which I've left as suggestions above), I was able to get GE to use the substituted values to connect to a datasource (I used `great_expectations suite new`). One question I had was regarding the time it takes to create a new suite. Running a local postgres database, I found that `great_expectations suite new` would take around ~5 min to run. Is this expected? I just wanted to check if it was something specific to my setup.

2021-03-17 22:52 UTC, Shinnnyshinshin commented on great_expectations/data_context/util.py
> +    )
```suggestion

    if secret_version:
        secret_response = client.get_secret_value(SecretId=secret_name, VersionId=secret_version)
    else:
        secret_response = client.get_secret_value(SecretId=secret_name)
```

-  I was getting an error in situations when `secret_name` is `None`

2021-03-17 22:52 UTC, Shinnnyshinshin commented on great_expectations/data_context/util.py
> +    name = f"projects/{project_id}/secrets/{secret_id}/version/{secret_version}"
```suggestion
    name = f"projects/{project_id}/secrets/{secret_id}/versions/{secret_version}"
```

- Should this be `versions`?

2021-03-17 22:52 UTC, Shinnnyshinshin commented on docs/guides/how_to_guides/configuring_data_contexts/how_to_populate_credentials_from_a_secrets_store.rst
> +    - :ref:`Set up a working deployment of Great Expectations <tutorials__getting_started>`
First I wanted to thank you for putting together the how-to-guide for this PR. It's really well-documented and going to be a very important resource for those who want to use this feature.  Since the doc contains information for 3 backends, I was wondering if you could try out `content-tabs`, which is a pattern we have been following in other docs (  https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_pandas_dataframe_as_a_batch.html) is one example. 

```

.. content-tabs::

    .. tab-container:: tab0
        :title: Show Docs for V2 (Batch Kwargs) API

        .. admonition:: Prerequisites: This how-to guide assumes you have already:
     
       - :ref:`Set up a working deployment of Great Expectations <tutorials__getting_started>`
            - :ref:`Configured and loaded a DataContext <how_to_guides__configuring_data_contexts>`
            - Configured a :ref:`Pandas/filesystem Datasource <how_to_guides__configuring_datasources>`
            - Identified a Pandas DataFrame that you would like to use as the data to validate.
```

Since this is more of a stylistic decision, I don't want to be too opinionated on this. Could you try it out and see what you think?

2021-03-18 08:45 UTC, Cedric-Magnan commented on great_expectations/data_context/util.py
> +    name = f"projects/{project_id}/secrets/{secret_id}/version/{secret_version}"
Indeed, it should be versions, well spotted !

2021-03-18 09:25 UTC, Cedric-Magnan commented on docs/guides/how_to_guides/configuring_data_contexts/how_to_populate_credentials_from_a_secrets_store.rst
> +    - :ref:`Set up a working deployment of Great Expectations <tutorials__getting_started>`
I have updated the documentation to use content-tabs

2021-03-18 10:00 UTC, Cedric-Magnan commented
> @Cedric-Magnan Overall this is a wonderful feature that we're excited to include in GE. Thank you also for including the (very thorough) how-to-doc, which is going to be a great resource 👍🏼
> 
> After a few tweaks (which I've left as suggestions above), I was able to get GE to use the substituted values to connect to a datasource (I used `great_expectations suite new`). One question I had was regarding the time it takes to create a new suite. Running a local postgres database, I found that `great_expectations suite new` would take around ~5 min to run. Is this expected? I just wanted to check if it was something specific to my setup.

@Shinnnyshinshin , I have also used a local postgres database and ran the `great_expectations suite new` command.
It took me 1 minute and 19 seconds to have the notebook fully displayed in my browser by applying the parameter substitution to the credentials of my postgres database.
Without the parameters substitution in the YAML config but with the current code, it only took 27 seconds.
By commenting the part that checks whether or not the "secret|" keyword is at the start of any value, it took only 24 seconds.

I imagine the queries to the secret manager slows down the process of fetching the credentials compared to having the secrets already available locally (in the uncommitted/config_variables.yaml file or in the environment variables).

I would say it is up to you to decide whether or not having this feature is worth the loading time.

2021-03-19 21:05 UTC, Shinnnyshinshin commented
Hi @Cedric-Magnan, thank you again for this PR. We looked a bit into the issue of the workload 
taking a lot of time, and it appears to be coming from our CLI code. In other words, the issue appears to be on us, and not you :) We have added a task to the queue and we should be seeing improvements soon. 

I also wanted to thank you once again regarding the documentation.. it's already been a great resource for me during the review process, and will certainly be one for GE users who use this feature. There are some very minor things like linking to Discuss that we will be making on our end. We may also tweak the formatting in the process as well, so please don't be surprised. 

LGTM, and I hope we get to work together again soon

2021-03-19 21:05 UTC, Shinnnyshinshin approved these changes

2021-03-19 21:33 UTC, merged