[ENHANCEMENT] Detect and Properly Handle Wrong Column Names and Other Failures in MapMetric and ColumnAggregateMetric
fivetran/great_expectations pull request #2493
Opened 2021-03-02 20:06 UTC by alexsherstinsky

### Scope
If an execution engine is asked to resolve a metric with a non-existent column, errors are either not reported till very late in the execution (e.g., Spark, due to lazy execution; also SQL) or reported in an obscure, almost hidden fashion (e.g., Pandas).  

When this happens in the context of Checkpoints and other higher-level execution contexts, reporting meaningful messages to the user is impossible.

* Detect missing columns for Pandas and Spark in `MapMetric` and `ColumnMapMetric`;
* Detect SQLAlchemy OperationalError when `execute()` fails;
* Tests for the three execution engines' use cases for both types of metric.

### Follow On Work
In the CLI pod, insure that the above error reporting is executed for all execution engines (currently it is done only for Pandas), with meaningful and consistent error messages reported to the user in the terminal screen.

### Acknowledgments
Many thanks to @gilpasternak35 and @roblim for informative discussions.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [ENHANCEMENT], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

Thank you for submitting!

2021-03-02 20:27 UTC, gilpasternak35 requested changes
tests such as tests.expectations.metrics.test_core.test_sparkdf_batch_aggregate_metrics are failing - let's review this!

2021-03-03 20:30 UTC, gilpasternak35 approved these changes
Looks great!

2021-03-05 19:14 UTC, jcampbell requested changes
I think these changes are correct, but something is wrong with the git history here; can you please clean this up into a single commit?

2021-03-05 19:16 UTC, alexsherstinsky commented
> I think these changes are correct, but something is wrong with the git history here; can you please clean this up into a single commit?

I will certainly give it a try!  Thanks, @jcampbell !

2021-03-05 19:38 UTC, alexsherstinsky commented
> > I think these changes are correct, but something is wrong with the git history here; can you please clean this up into a single commit?
> 
> I will certainly give it a try! Thanks, @jcampbell !

Done -- 1 commit now.

2021-03-05 19:59 UTC, jcampbell approved these changes

2021-03-05 19:59 UTC, merged