[BUGFIX] Fix issue for read_method on missing compression param for r…
fivetran/great_expectations pull request #2557
Opened 2021-03-16 21:57 UTC by sfrancavilla

2021-03-20 15:58 UTC, sfrancavilla commented
@cla-bot check

2021-03-22 03:45 UTC, eugmandel commented
@sfrancavilla Thank you for making this PR! A reviewer will take it on after tomorrow's triage.

2021-03-22 15:16 UTC, eugmandel commented
@sfrancavilla Triaged today - @jcampbell will review. Thank you again!

2021-03-22 17:45 UTC, jcampbell requested changes
Thanks -- this looks great.

I made a couple small change requests. Could you please also include in your test an example of the filtering behavior (i.e. surplus key included in the `reader_options`, and the resulting warning?)

2021-03-22 17:45 UTC, jcampbell commented on great_expectations/execution_engine/pandas_execution_engine.py
> +            }
Is this equivalent to using `get_full_argspec`?

2021-03-22 17:45 UTC, jcampbell commented on great_expectations/execution_engine/pandas_execution_engine.py
> +            }
Could you add a `logger.warning` message notifying the user of which option keys were dropped at this point?

2021-03-22 17:45 UTC, jcampbell commented on great_expectations/execution_engine/pandas_execution_engine.py
> +            }
(no change needed; just curious)

2021-03-23 17:46 UTC, sfrancavilla commented on great_expectations/execution_engine/pandas_execution_engine.py
> +            }
it's basically similar, I think the only difference is `co_varnames` prints local vars too (just a few for the methods we're using). I was thinking about using `getfullargspec` actually but I believe it required to import the `inspect` library and I thought to use just `co_varnames` with no import.

2021-03-23 18:00 UTC, sfrancavilla commented on great_expectations/execution_engine/pandas_execution_engine.py
> +            reader_options = self._drop_unsupported_option_keys_for_reader(
@jcampbell I revised a bit the code and added a separate private method instead. I thought this would've been a better choice.

2021-03-29 12:28 UTC, luke321321 commented
FYI there is a different PR & approach to fix this: https://github.com/great-expectations/great_expectations/pull/2506

2021-03-29 17:32 UTC, sfrancavilla commented
@luke321321 yes, I've left a comment [here](https://github.com/great-expectations/great_expectations/issues/2484) to James letting him know I was working on this PR and considering another approach (he has reviewed this one). But, it's ok for me to close my PR.

2021-07-05 00:09 UTC, closed without merging