[BUGFIX] Handle limit for oracle with rownum
fivetran/great_expectations pull request #2691
Opened 2021-04-16 17:52 UTC by NathanFarmer

This is a bugfix commit that should have been included with PR #[2609](https://github.com/great-expectations/great_expectations/pull/2609).

Oracle does not support the LIMIT keyword. This workaround is the same one used in [sqlalchemy_datasource.py](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/datasource/sqlalchemy_datasource.py#L426) starting on line 426.

2021-04-19 14:42 UTC, eugmandel commented
@NathanFarmer Thank you for fixing this! @Shinnnyshinshin will review the PR.

2021-04-20 02:03 UTC, Shinnnyshinshin commented
@NathanFarmer  Thank you for submitting this PR :) 

One ask is that a similar fix be added for the V3 API which would go here:
https://github.com/great-expectations/great_expectations/blob/3b5426d305f1945726d27ddfdf71a300a1306208/great_expectations/execution_engine/sqlalchemy_execution_engine.py#L790

Would you be willing to port the change, test it with your code snippet and create a PR? Please let me know.

2021-04-20 02:04 UTC, Shinnnyshinshin requested changes
@NathanFarmer Thank you for submitting this PR :)

One ask is that a similar fix be added for the V3 API which would go here:

https://github.com/great-expectations/great_expectations/blob/3b5426d305f1945726d27ddfdf71a300a1306208/great_expectations/execution_engine/sqlalchemy_execution_engine.py#L790

Would you be willing to port the change, test it with your code snippet and update this PR? Please let me know.

2021-04-20 13:34 UTC, NathanFarmer commented
@Shinnnyshinshin I can make the changes and test. When you say "create a PR" are you asking me to create a separate PR from this one?

2021-04-20 18:26 UTC, Shinnnyshinshin commented
Thanks, and thanks for checking @NathanFarmer. That was a typo on my end 😓  "update this PR" is what I meant

2021-04-21 19:53 UTC, Shinnnyshinshin commented
Hi @NathanFarmer Thanks for your continued work with this. We noticed that mssql tests were failing with the most recent version of sqlalchemy 1.4.10.  PR #2708 should fix that.

2021-04-21 20:21 UTC, NathanFarmer commented
Hi @Shinnnyshinshin I suspected the mssql tests were failing due to some other piece of the codebase which is why I merged multiple times above. I will try again now.

2021-04-21 21:40 UTC, Shinnnyshinshin approved these changes
Looks wonderful :) thank you very much for submitting. This should be part of a release that is going out today @NathanFarmer

2021-04-21 21:40 UTC, Shinnnyshinshin commented on great_expectations/execution_engine/sqlalchemy_execution_engine.py
Thank you very much for this too.. the type hinting reveals a subtlety that could be easily overlooked :)

2021-04-21 21:40 UTC, Shinnnyshinshin commented on great_expectations/execution_engine/sqlalchemy_execution_engine.py
> +                    return query
Thank you!

2021-04-21 21:40 UTC, merged