Add new expect_column_values_to_not_match_regex_list expectation (#277)
fivetran/great_expectations pull request #279
Opened 2018-04-20 01:41 UTC by jpcampb2

Create new expectation `expect_column_values_to_not_match_regex_list`

Note that currently the regex expectations are not consistent in use of match vs. findall. I chose match (it seems clearer and more in line with the wording of the expectation), but the non list variants both use `findall` Should that be a separate issue?

2018-04-20 14:11 UTC, abegong requested changes
`re.match` only matches at the beginning of strings.

```
In [7]: print(re.match("b", "aaaaaabbbbb"))
None

In [6]: print(re.match("a", "aaaaaabbbbb"))
<_sre.SRE_Match object; span=(0, 1), match='a'>
```

To make regex Expectations as flexible as possible, I think we want to use `findall` or `search`. (For our purposes here, they're functionally equivalent)

```

In [8]: print(re.search("b", "aaaaaabbbbb"))
<_sre.SRE_Match object; span=(6, 7), match='b'>

In [9]: print(re.findall("b", "aaaaaabbbbb"))
['b', 'b', 'b', 'b', 'b']
```

Propose we switch to `search` and add a test case to pick up matches that aren't at the beginning of the string.

2018-04-20 14:22 UTC, jpcampb2 commented
I think either way lets us have the same amount of flexibility--if we use findall, one could use `^` to get the match-like behavior, and if we use `match` one could add `.*` to get the findall-like behavior.

I agree that findall is more intuitive behavior, though, and had originally written this that way before changing it to match when I realized that's how the current regex_list expectation works. I'll change them both in the revision to this PR.

Re: test--the current test is sensitive to this change, it is just written to expect the current behavior. I'll change it back.

2018-04-20 14:28 UTC, abegong commented
+10

2018-04-20 23:51 UTC, jpcampb2 commented
I added even more explicit documentation. The sqlalchemy adaptation will not be immediate, so I'm not going to tie it to this PR (it's still in the "open for others contribution" category in my view).

2018-04-21 13:49 UTC, abegong approved these changes
💯

2018-04-22 01:14 UTC, merged