[BUGFIX] Temp table creation fix
fivetran/great_expectations pull request #2859
Opened 2021-06-03 16:11 UTC by shpolina

Changes proposed in this pull request:
* Fixed `_sqlalchemy_map_condition_unexpected_count_value()` to create temp table instead of permanent one.
The intent of the method was to create temp table for condition calculation but the `TEMPORARY` keyword got omitted from the query causing it to create a permanent table.
* Fixed `_sqlalchemy_map_condition_unexpected_count_value()` to properly check engine dialect

Closes #2843

2021-06-04 00:30 UTC, eugmandel requested changes
@shpolina Thank you for submitting the PR! As I was reviewing it, I looked a little bit deeper into the original issue and now I get it. The entire logic of creating a temporary table was a workaround that was done specifically for mssql. The original reason was that a certain subquery logic was not possible otherwise. It looks like what happened that the "try" block in map_metric.py that starts at (originally) line 857 was unintented by mistake and now it applies to ALL database engines, not just to mssql. In this case, all you have to do is to indent this block. There is no reason to create these temp tables in any other database engine.

Please update and I will approve/merge the PR.

Again, really appreciate you finding this issue and following through with the PR.

2021-06-04 00:30 UTC, eugmandel commented on great_expectations/expectations/metrics/map_metric.py
>      try:
This entire try block should be indented inside by one level.

2021-06-04 17:55 UTC, shpolina commented
@eugmandel thank you very much for the review and for providing the context. I rewroked the fix to use the temp table for mssql only and to construct a query without temp table for all other engines. Hope the function does the right thing now.

2021-06-04 19:19 UTC, shpolina commented
Now that I better understand the issue, I am pretty sure this also fixes #2837. It is a slightly different use case and the issue presents itself differently, but looks like it was happening due to the same reason - the temp table code was invoked for non-mssql engine.

2021-06-17 20:42 UTC, eugmandel approved these changes
LGTM!

2021-06-21 13:47 UTC, merged