[DOCS] How to connect to your data in BigQuery
fivetran/great_expectations pull request #2902
Opened 2021-06-14 05:04 UTC by Shinnnyshinshin

Changes proposed in this pull request:
- How-to-guide for BigQuery
- Associated test scripts for `python` and `yaml` configuration.
- **Note** : The integration tests for BigQuery only run locally. Azure integration is a next step

Checklist
- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have run any local integration tests and made sure that nothing is broken.

2021-06-15 18:07 UTC, Shinnnyshinshin commented on tests/integration/test_script_runner.py
> +    # {
These will be re-enabled once Azure pipelines are connected with GGS

2021-06-15 18:21 UTC, Shinnnyshinshin commented on great_expectations/execution_engine/sqlalchemy_batch_data.py
> -                    )
This error was preventing GE from creating bigquery tables without specifying `batch_spec_passthrough`.  Removing this error allows for `sqlalchemy_batch_data.py` to behave in the same way as CLI

Please see `great_expectations/cli/batch_request` line 268-274

2021-06-15 18:27 UTC, Shinnnyshinshin commented on tests/integration/test_script_runner.py
> +    # {
in order to run the tests locally, un-comment these lines

2021-06-15 18:54 UTC, Shinnnyshinshin commented on docs/guides/connecting_to_your_data/database/bigquery.md
> +
This is the section where both "versions" of the `batch_spec` (with and without the `batch_spec_passthrough`) are described.  Requesting feedback on how this part looks and flows

2021-06-17 20:38 UTC, Aylr requested changes
Change request as we discussed.

2021-06-17 20:38 UTC, Aylr commented on tests/integration/docusaurus/connecting_to_your_data/database/bigquery_python_example.py
> +)
Please remove this in favor of a ticket in JIRA.

2021-06-17 20:38 UTC, Aylr commented on tests/integration/docusaurus/connecting_to_your_data/database/bigquery_python_example.py
> +)
Please remove this in favor of a ticket in JIRA.

2021-06-17 20:38 UTC, Aylr commented on tests/integration/docusaurus/connecting_to_your_data/database/bigquery_yaml_example.py
> +)
Please remove this in favor of a ticket in JIRA.

2021-06-17 20:38 UTC, Aylr commented on tests/integration/docusaurus/connecting_to_your_data/database/bigquery_yaml_example.py
> +)
Please remove this in favor of a ticket in JIRA.

2021-06-17 20:50 UTC, Aylr commented on docs/guides/connecting_to_your_data/database/bigquery.md
> +:::
Also take this note out as discussed.

2021-06-18 18:46 UTC, Shinnnyshinshin commented
Hi @Aylr thanks for the review. I wanted to check what you thought of a simplified note to the user.  I feel like there would be a benefit to explaining why this parameter exists and how it should be used.  Here is a "simplified" version. 

![Screen Shot 2021-06-18 at 11 29 34 AM](https://user-images.githubusercontent.com/25670697/122604325-9f046000-d02a-11eb-970b-583f2b3b3950.png)

2021-06-18 20:00 UTC, Aylr approved these changes
LGTM

2021-06-18 20:09 UTC, merged