[BUGFIX] Fix error when `batch_request` is passed to `SimpleCheckpoint`
fivetran/great_expectations pull request #3152
Opened 2021-07-30 20:03 UTC by cdkini

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @tiny-tim-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2021-07-30 22:51 UTC, cdkini commented
While we've determine the appropriate change to get things working, I want to do the following:
* Understand the circumstances around why this failed (`RuntimeDataConnector, `SimpleCheckpoint`, etc ?)
* Write tests to cover these circumstances to prevent future issues

2021-08-02 15:19 UTC, alexsherstinsky commented on great_expectations/data_context/types/base.py
> +                # Necessary when using RuntimeDataConnector with SimpleCheckpoint
@cdkini I agree with the logic of this change.  It seems to me that its place should be in the caller.  Based on my experience and understanding, all arguments to the constructors of "config" objects (such as `CheckpointConfig`) in `base.py` are already expected to be basic types (i.e., not typed objects, such as `BatchRequest` types).

2021-08-02 15:20 UTC, alexsherstinsky requested changes
Very nice direction.  Please see comment.  Thank you!

2021-08-02 18:38 UTC, alexsherstinsky approved these changes
LGTM

2021-08-02 19:19 UTC, merged