[WIP] [FEATURE] Add InferredAssetAzureDataConnector
fivetran/great_expectations pull request #3211
Opened 2021-08-10 18:01 UTC by fjork3

Changes proposed in this pull request:
- https://superconductive.atlassian.net/browse/GREAT-76
- Implement `InferredAssetAzureDataConnector` class and related methods
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

2021-08-10 18:57 UTC, cdkini requested changes
Thanks for writing this up! Almost at the finish line 🎉 

I've requested some changes to the primary implementation; please take a look and let me know your thoughts.

Additionally, please add unit tests so we gain coverage over the changes made here. I very much modeled mine after the S3 ones (using `unitest.mock` to cover external dependencies like the anonymizer and Azure connection object). Happy to discuss live if that would be beneficial 😄

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +logger = logging.getLogger(__name__)
Please add the `try/except` clause we have for cloud provider connection objects (see S3 or ConfiguredAssetAzure imports)

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +    Extension of InferredAssetFilePathDataConnector used to connect to Azure blob store
Please change all instances to Azure Blob Storage to align with official name

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +
`prefix` should be `name_starts_with` to be in alignment with SDK

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +            azure_options = {}
Please add comment and assertion from L94-101 of ConfiguredAssetAzureDataConnector

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +            )
Please follow the `try/except` logic from the ConfiguredAssetAzureDataConnector; we require regex to parse our `self._account_name` (which is used in `_get_full_file_path()`)

2021-08-10 18:57 UTC, cdkini commented on great_expectations/datasource/data_connector/inferred_asset_azure_data_connector.py
> +        # data_assert_name isn't used in this method.
Please fix typo to `asset`

2021-09-09 00:24 UTC, closed without merging

2021-09-09 00:25 UTC, alexsherstinsky commented
Replaced by PR #3372