[MAINTENANCE] parse_strings_as_datetimes V3 deprecation
fivetran/great_expectations pull request #3310
Opened 2021-08-25 02:11 UTC by NathanFarmer

Changes proposed in this pull request:
- JIRA: GREAT-56/GREAT-176

### Definition of Done
Please delete options that are not relevant.

- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

2021-08-27 17:50 UTC, cdkini commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
Do we know the type annotation for this yet? If so, could we please add it? `Optional[something]`?

2021-08-27 17:53 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
Yes, would `Optional[Boolean]` default to `None`?

2021-08-27 17:53 UTC, cdkini commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
That looks good!

2021-08-30 13:23 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
I made these changes @cdkini

2021-08-30 13:41 UTC, cdkini commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
Sorry @NathanFarmer I think my previous answer was misleading.

I think it should be `parse_strings_as_datetimes: Optional[bool] = None`. The current assignment here is to the actual type "`typing.Union[bool, NoneType]`" when we want to set it to `None`.

If these type annotations are hindering your workflow at all, I'm happy to just revert the changes and review the previous version!

2021-08-30 13:48 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_map_metrics/column_values_increasing.py
> +        parse_strings_as_datetimes=None,
@cdkini Yeah I picked up on that and already made the changes! Thanks.

2021-08-30 14:15 UTC, cdkini approved these changes
Took a second to wrap my head around everything but this actually makes a lot of sense!

LGTM 🎉

2021-08-30 19:17 UTC, alexsherstinsky commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +        if parse_strings_as_datetimes:
@NathanFarmer Without a nice warning message?

2021-08-30 19:18 UTC, alexsherstinsky commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +            raise NotImplementedError
@NathanFarmer Without a nice warning message?

2021-08-30 19:18 UTC, alexsherstinsky commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +            raise NotImplementedError
@NathanFarmer Without a nice warning message?

2021-08-30 19:18 UTC, alexsherstinsky commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_min.py
> +            raise NotImplementedError
Same as above -- @NathanFarmer Without a nice warning message?

2021-08-30 19:21 UTC, alexsherstinsky commented
@NathanFarmer I noticed that in a number of classes we do not issue the `DeprecationWarning` message, while in many others we do.  What is the reason for this difference?  Thanks!

2021-08-30 19:21 UTC, alexsherstinsky requested changes
@NathanFarmer I had a question (corresponds to several of my identical comments).  Thanks!

2021-08-30 20:25 UTC, NathanFarmer commented
> @NathanFarmer I noticed that in a number of classes we do not issue the `DeprecationWarning` message, while in many others we do. What is the reason for this difference? Thanks!

@alexsherstinsky I experienced that some of the expectations follow a different pattern than others. One of the ways this is seen is if the expectation (as opposed to the metric) has the `_validate` function. For example, the `DeprecationMessage` for expectations `expect_column_min_to_be_between` and `expect_column_max_to_be_between` is found in the `_validate` function of `expect_column_min_to_be_between.py` and `expect_column_max_to_be_between.py`. This allows one to add the message only once for a given expectation instead of multiple times for each `ExecutionEngine` handled by the metrics `column_min.py` and `column_max.py`. Furthermore, I believe this would suppress the message in cases where a different expectation uses metrics `column_min.py` and `column_max.py`, but does not explicitly support parameter `parse_strings_as_datetimes`. If you disagree with this approach I am happy to take another look.

2021-08-30 20:36 UTC, alexsherstinsky commented
> > @NathanFarmer I noticed that in a number of classes we do not issue the `DeprecationWarning` message, while in many others we do. What is the reason for this difference? Thanks!
> 
> @alexsherstinsky I experienced that some of the expectations follow a different pattern than others. One of the ways this is seen is if the expectation (as opposed to the metric) has the `_validate` function. For example, the `DeprecationMessage` for expectations `expect_column_min_to_be_between` and `expect_column_max_to_be_between` is found in the `_validate` function of `expect_column_min_to_be_between.py` and `expect_column_max_to_be_between.py`. This allows one to add the message only once for a given expectation instead of multiple times for each `ExecutionEngine` handled by the metrics `column_min.py` and `column_max.py`. Furthermore, I believe this would suppress the message in cases where a different expectation uses metrics `column_min.py` and `column_max.py`, but does not explicitly support parameter `parse_strings_as_datetimes`. If you disagree with this approach I am happy to take another look.

@NathanFarmer I would be happy to discuss, only because returning the `NotImplementedException` without a message does not feel right.  I could be mistaken here, so would be delighted to talk about it.  Thanks!

2021-08-30 20:46 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +        if parse_strings_as_datetimes:
https://github.com/great-expectations/great_expectations/pull/3310#issuecomment-908668590

2021-08-30 20:46 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +            raise NotImplementedError
https://github.com/great-expectations/great_expectations/pull/3310#issuecomment-908668590

2021-08-30 20:46 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_max.py
> +            raise NotImplementedError
https://github.com/great-expectations/great_expectations/pull/3310#issuecomment-908668590

2021-08-30 20:46 UTC, NathanFarmer commented on great_expectations/expectations/metrics/column_aggregate_metrics/column_min.py
> +            raise NotImplementedError
https://github.com/great-expectations/great_expectations/pull/3310#issuecomment-908668590

2021-08-30 21:00 UTC, NathanFarmer commented
> @NathanFarmer I would be happy to discuss, only because returning the `NotImplementedException` without a message does not feel right. I could be mistaken here, so would be delighted to talk about it. Thanks!

In the cases you outlined the message IS presented. It comes from the expectation (e.g. `expect_column_max_to_be_between.py`), not the metric (e.g. `column_max.py`). Other cases where the metric may utilized do not currently support `parse_strings_as_datetimes` and therefore `DeprecationMessage` is not applicable. What if I created a different message to display alongside `NotImplementedError`?

2021-10-13 06:45 UTC, alexsherstinsky commented
The scope of this PR is being reflected by PR #3539

2021-10-13 06:45 UTC, closed without merging