SA expect_column_values_to_be_unique
fivetran/great_expectations pull request #352
Opened 2018-08-30 14:01 UTC by ccnobbli

I think this one is pretty close (silent call for help). I had one test failing locally and I couldn't figure out why.

This implementation finds `duplicate_values` using a `GROUP BY value` and `HAVING count(value) > 1`.
It then maps the column values to the `.notin_( duplicated_values )` method.

Where it is going wrong:

- Column `[1, "2", 2]`
- This expectation should pass because `"2"` and `2` are different types (true for pandas implementation)
- ... but flags `"2"` as a dupe

So close! I think the type mismatch might not be a consideration of the SA engine. Imo it is a fair assumption that a column would have values of the same type, what do y'all think?

2018-09-06 03:54 UTC, abegong commented
This is cool. Can you add a (failing) test case that demonstrates the 1,"2",2 problem you describe above?

2018-09-06 15:38 UTC, ccnobbli commented
@abegong, At this point, I think we have to agree upon the expected behavior of the `[1,"2",2]` test case.

Currently, this test is already implemented and expected to pass for pandas data.
However, this test cannot pass for SA data (at least with this implementation of the expectation).

2018-09-06 15:42 UTC, ccnobbli commented
So, in effect, we have to change the expected behavior for pandas for this SA implementation to work. I'm not seeing a way around that, without having disparate behavior between Pandas/SA expectations, which seems bad.

2018-09-07 14:05 UTC, abegong commented
Hm. My read is that both expectations are doing the right thing---the problem is some unspoken (and in this case, incorrect) magic in our test framework.

I suspect that when sqlite creates a column to hold [1, "2", 2], it creates a text or varchar column. So it would interpret the column values as equivalent to ["1", "2", "2"].

Does that sound right?

Assuming that's true, your SA expectation is doing the right thing. So is the pandas expectation. The problem is that there's slippage in the way the test case is instantiated in the two different environments.

I think the simplest thing to do would be to explicitly suppress this test case for SA. What if we add an optional `suppress_test_for` field, like so?:

```
      {
        "title": "Basic positive test case",
        "exact_match_out": false,
        "suppress_test_for": ["SqlAlchemyDataset"]
        "in": {
          "column": "b"
        },
        "out": {
          "success": true,
          "unexpected_list": [],
          "unexpected_index_list": []
        }
      }
```

Also, this is kind of a weird test for a "Basic positive test case." Can we add something like ["A", "B", "C"] for the basic positive case, and give the cross-type test a different name?

2018-09-15 16:03 UTC, ccnobbli commented
Agreed - this needs a universal, and typical, positive case. I'll also add tests for Pandas/SQLAlchemy once #358 has been approved and pulled.

2018-09-17 13:29 UTC, jpcampb2 commented
I just merged #358, so this one should be ready to revisit.

2018-09-17 18:24 UTC, jpcampb2 commented on great_expectations/dataset/sqlalchemy_dataset.py
> +        return sa.column(column).notin_(dup_query)
This logic seems to have two problems to me:

1. you're only grabbing a single duplicate value, which means the expectation would not return any except the first-returned duplicate among the unexpected values, and that mostly would fail to work properly in cases where there are multiple duplicates. I'd recommend adding a test case with a column like: [1,1,2,2,3] expect_column_values_to_be_unique, mostly=0.5

2. To address (1) you'd have to return all duplicate values to the client before issuing the second query. Wouldn't it make more sense to not make this a column_map_expectation by decorator, and handle the entire check as a single query?

2018-09-17 18:25 UTC, jpcampb2 requested changes
Inline comment--I'm not sure the logic is right as I read it, so please check and potentially document more clearly.

2018-09-19 15:45 UTC, jpcampb2 approved these changes

2018-09-19 15:45 UTC, jpcampb2 commented on great_expectations/dataset/sqlalchemy_dataset.py
> +        return sa.column(column).notin_(dup_query)
This seems like a great resolution--much cleaner!

2018-09-20 21:22 UTC, merged