[FEATURE] Extract validation result failures
fivetran/great_expectations pull request #3552
Opened 2021-10-15 20:41 UTC by BenGale93

Changes proposed in this pull request:
- Added get_failed method onto ExpectationSuiteValidationResult.
- Dealt with the TODO found in data_context.py

### Note

To create the new ExpectationSuiteValidationResult in get_failed I recalculated the statistics attribute using a function from data_asset, namely the _calc_validation_statistics function. Ideally I would just directly use this function but given it is marked as private I chose not to.

I feel though that this function could be an internal method of ExpectationSuiteValidationResult which computes the statistics during initialisation, based on what results are passed in. That way the statistics are never out of line with the results found in the instance. Happy to open a pull request to implement this if you would like?

### Definition of Done

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.

2021-10-18 13:43 UTC, talagluck commented
Thanks for submitting, @BenGale93! We will review and be in touch in the next couple of days.

2021-12-01 17:44 UTC, cdkini requested changes
Requesting a very minor change but this all looks great to me! Once you make the minor updates, I'll approve and merge

2021-12-01 17:44 UTC, cdkini commented on great_expectations/core/expectation_validation_result.py
> +    def get_failed(self):
Could we perhaps rename this to `get_failed_validation_results` just to be very explicit?

Additionally, could we add `ExpectationSuiteValidationResult` as a return type? We're trying to make a more conscious effort to type hint so any additions are greatly appreciated!

2021-12-01 19:11 UTC, cdkini commented on great_expectations/data_context/data_context.py
> +        return results_dict.get_failed() if failed_only else results_dict
I think this usage needs to be fixed before we get it all working?

2021-12-01 19:27 UTC, cdkini commented on great_expectations/data_context/data_context.py
> +        return results_dict.get_failed() if failed_only else results_dict
```suggestion
        return results_dict.get_failed_validation_results() if failed_only else results_dict
```

2021-12-01 19:28 UTC, cdkini approved these changes

2021-12-01 19:29 UTC, cdkini commented
@BenGale93 decided to just make the quick update. As long as tests pass this time around, the changes will be merged. Thanks so much!

2021-12-01 23:15 UTC, merged