[DOCS] How to pass an in-memory DataFrame to a Checkpoint
fivetran/great_expectations pull request #3756
Opened 2021-11-29 21:30 UTC by NathanFarmer

Changes proposed in this pull request:
- GREAT-356/GREAT-378
- Documentation for passing in a DataFrame to a Checkpoint using a RuntimeBatchRequest

Out of scope:
- Checkpoint configuration precedence behavior when yaml configuration conflicts with runtime configuration

### Definition of Done
- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

2021-11-29 22:40 UTC, alexsherstinsky approved these changes
LGTM

2021-11-29 23:21 UTC, Shinnnyshinshin commented on great_expectations/data_context/data_context.py
> +            expectation_suite_ge_cloud_id: Great Expectations Cloud id for the expectation suite
❤️

2021-11-29 23:23 UTC, Shinnnyshinshin approved these changes
Looks wonderful to me too. Before you merge, could I ask that a link to the script be added to the bottom of the Doc? It's usually placed under **Additional Notes**, and you should be able to find plenty of examples in the `Connect to your Data` section

https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/pandas

2021-11-29 23:24 UTC, Shinnnyshinshin requested changes
Looks wonderful to me too. Before you merge, could I ask that a link to the script be added to the bottom of the Doc? It's usually placed under **Additional Notes**, and you should be able to find plenty of examples in the `Connect to your Data` section

https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/filesystem/pandas

2021-11-29 23:54 UTC, NathanFarmer commented
@Shinnnyshinshin 
> Looks wonderful to me too. Before you merge, could I ask that a link to the script be added to the bottom of the Doc?

✅ You will not have to ask me to do this a 3rd time 😄

2021-11-29 23:57 UTC, Shinnnyshinshin approved these changes
Looks great :)

2021-11-30 20:24 UTC, anthonyburdi approved these changes
LGTM! (pending resolution of the integration test failure)

2021-12-01 13:57 UTC, donaldheppner approved these changes
sidebar looks good

2021-12-01 15:47 UTC, merged