[FEATURE] Add github action to build and push release docker image
fivetran/great_expectations pull request #3792
Opened 2021-12-03 17:18 UTC by cedric-orange

Changes proposed in this pull request:
- add github action to automate container image build

closes #2495

### Definition of Done
Please delete options that are not relevant.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2021-12-03 17:22 UTC, cedric-orange commented
@cla-bot check

2021-12-08 16:43 UTC, cdkini commented
Hey @cedric-orange! Thank you so much for opening up this PR. Let me bring these proposed changes to our next triage meeting so I can determine next steps.

2021-12-09 08:04 UTC, cedric-orange commented
Note that dockerfile should be upgraded also

2022-03-08 23:13 UTC, joshua-stauffer requested changes
Thanks for this contribution, @cedric-orange -- I left some thoughts, primarily around supporting multiple architectures.

2022-03-08 23:13 UTC, joshua-stauffer commented on .github/workflows/docker-image.yml
> +          build-args: PYTHON_DOCKER_TAG=3.7-buster
I suggest we use Python 3.9-buster as a base image

2022-03-08 23:13 UTC, joshua-stauffer commented on .github/workflows/docker-image.yml
> +          file: ./docker/Dockerfile
add multi-arch build support here: `platforms: linux/amd64,linux/arm64`

2022-03-08 23:13 UTC, joshua-stauffer commented on .github/workflows/docker-image.yml
> +
To support multi-arch builds we'll need to add a QEMU step:
```yaml
- name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
```

2022-03-08 23:13 UTC, joshua-stauffer commented on .github/workflows/docker-image.yml
> +          file: ./docker/Dockerfile
these are the two i'm primarily familiar with, to support intel and apple silicon -- haven't tried to support windows natively, so unclear if there's a straightforward way to add that here.

2022-03-08 23:13 UTC, joshua-stauffer commented on .github/workflows/docker-image.yml
> +        uses: docker/setup-buildx-action@v1
add `install: true` to the buildx step to alias `docker build` to `docker buildx` -- in my experience, this was necessary to get my multi-arch builds to be successful.

2023-03-27 14:34 UTC, anthonyburdi commented
Thank you so much for this contribution! We are planning to work on a strategy for our docker presence and this is a great start. We'll close this PR for now and @talagluck will add this work to our internal work tracking system and we may reopen this PR in the future as part of that effort.

2023-03-27 14:34 UTC, closed without merging