[DOCS] GCP Deployment Pattern
fivetran/great_expectations pull request #3926
Opened 2021-12-31 20:22 UTC by Shinnnyshinshin

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-01-03 00:18 UTC, Shinnnyshinshin commented on docs/deployment_patterns/how_to_use_great_expectations_in_databricks.md
> -  - If you already have a spark dataframe loaded, select one of the "Dataframe" tabs below.
This file had some minor formatting changes that were introduced as part of `lint`.

2022-01-03 00:19 UTC, Shinnnyshinshin commented on docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.md
> +    ```yaml file=../../../../tests/integration/docusaurus/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.py#L54-L56
This file also had some minor line-number changes introduced as part of `lint`

2022-01-03 00:19 UTC, Shinnnyshinshin commented on sidebars.js
> +        'deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery',
Please let me know if this should be introduced as part of a separate PR

2022-01-03 17:00 UTC, NathanFarmer requested changes
I left a few comments in my friction log that will need to be addressed and I am currently performing part 2 of the friction logging.

2022-01-04 23:44 UTC, NathanFarmer approved these changes
This is one of the most detailed docs we have! Great work!

2022-01-04 23:44 UTC, NathanFarmer commented on docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
> +:::note Note on Trailing Slashes in Metadata Store prefixes
❤️

2022-01-04 23:44 UTC, NathanFarmer commented on docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
> +For our example, we are going to use the `bash operator` to run the Checkpoint. This portion of the guide can also be found in the following [Walkthrough Video](https://drive.google.com/file/d/1YhEMq
This video is very helpful thank you 🙇🏻

2022-01-04 23:44 UTC, NathanFarmer commented on docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery.md
> +If you run into trouble while installing Great Expectations in Cloud Composer, the [official Google Cloud documentation offers the following guide on troubleshooting PyPI package installations.](http
Thank you for this link

2022-01-05 13:38 UTC, donaldheppner approved these changes

2022-01-05 19:20 UTC, merged