Feature/refactor and type expectation diagnostic report
fivetran/great_expectations pull request #3929
Opened 2022-01-01 17:13 UTC by abegong

WIP. Not yet ready for review.

2022-01-07 15:33 UTC, donaldheppner requested changes

2022-01-07 15:33 UTC, donaldheppner commented on great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
> +from great_expectations.core.expectation_diagnostics.supporting_types import (
Remove the supporting_types package

2022-01-07 15:33 UTC, donaldheppner commented on great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
> +from great_expectations.types import SerializableDictDot
modules should be semantic, not reflecting the nature of the code in the module

2022-01-07 15:33 UTC, donaldheppner commented on great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
> +            **{
use dot notation

2022-01-07 15:33 UTC, donaldheppner commented on great_expectations/core/expectation_diagnostics/expectation_diagnostics.py
> +                    "message": message,
use dot notation

2022-01-07 15:33 UTC, donaldheppner commented on tests/expectations/test_expectation_diagnostics.py
> +    print(expectation_test_data_case)
please remove

2022-01-13 04:42 UTC, abegong commented on tests/expectations/test_expectation_diagnostics.py
> +    print(expectation_test_data_case)
```suggestion
```

2022-01-24 21:44 UTC, merged