[BUGFIX] Provide ability to capture schema_name for SQL-based datasources; fix method usage bugs.
fivetran/great_expectations pull request #3938
Opened 2022-01-04 16:35 UTC by alexsherstinsky

### Scope
* CLI Datasource approach had a superfluous `name` field for the `InferredAssetSqlDataConnector` -- instead, it needs the directive `"include_schema_name": True,` in order for the data assets to be qualified by the schema name and enable users to choose the `data_asset` unambiguously.
* Bug fixes, whereby certain methods were using an incorrect (old) signature.

### Note
Documentation has to be updated to reflect the first point above (in a separate upcoming pull request).

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/en/latest/contributing/style_guide.html?highlight=style%20guide)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html?highlight=checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/en/latest/contributing/testing.html#contributing-testing-writing-unit-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-01-04 19:44 UTC, Shinnnyshinshin requested changes
Thank you very much for this work. I may be missing something, the tests that were changed in `tests/cli` seem to either test the schema or signature. 

Would it be possible to include examples of the Introspection and Configured Data Asset (in the PR description) that now work as the result of this fix?

2022-01-04 20:26 UTC, talagluck commented
Seconding @Shinnnyshinshin . It would also be great to see some examples that you use dot notation (i.e. a BatchRequest with `schema_name.table_name`)

2022-01-05 02:00 UTC, alexsherstinsky commented
@talagluck @Shinnnyshinshin -- I added tests -- please re-review.  Thanks!

2022-01-05 02:10 UTC, Shinnnyshinshin approved these changes
Love the tests that you added, how you structured the fixture, and helpful comments throughout :) Thank you @alexsherstinsky

2022-01-05 02:10 UTC, Shinnnyshinshin commented on tests/conftest.py
> +        pytest.skip("SQL Database tests require sqlalchemy to be installed.")
love the `try-except` here :)

2022-01-05 02:10 UTC, Shinnnyshinshin commented on tests/datasource/test_new_datasource_with_sql_data_connector.py
> +    # Exercise InferredAssetSqlDataConnector using data_asset_name introspected with schema from table, named "table_1".
Comments are very helpful here. Thank you very much @alexsherstinsky

2022-01-05 07:19 UTC, merged