Add dataset_class argument to from_pandas
fivetran/great_expectations pull request #404
Opened 2018-12-11 20:45 UTC by jtilly

I added the `dataset_class` argument to `from_pandas` to make it easier to use custom expectations.

2018-12-11 22:02 UTC, abegong requested changes
This is great!

One request: can you add a test or two to exercise the new `dataset_class` parameter?

2018-12-11 22:02 UTC, abegong commented on great_expectations/util.py
> +def from_pandas(pandas_df,
This docstring is a thing of beauty!

2018-12-12 13:26 UTC, abegong approved these changes
Thanks for adding tests. Merging now.

2018-12-12 13:26 UTC, merged

2018-12-12 13:35 UTC, jtilly commented
Awesome, thanks for including this.