[BUGFIX] Add support for SqlAlchemyQueryStore connection_string credentials
fivetran/great_expectations pull request #4224
Opened 2022-02-16 23:42 UTC by davidvanrooij

Changes proposed in this pull request:
- Add support for SqlAlchemyQueryStore connection_string credentials

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-02-16 23:45 UTC, davidvanrooij commented
@cla-bot check

2022-02-18 15:46 UTC, AFineDayFor requested changes

2022-02-18 15:46 UTC, AFineDayFor commented on great_expectations/data_context/store/query_store.py
> +        elif "connection_string" in credentials:
Could benefit from tests as we go forward, ref a similar [here](https://github.com/davidvanrooij/great_expectations/blob/develop/tests/data_context/store/test_query_store.py)

2022-02-22 20:42 UTC, davidvanrooij commented
@AFineDayFor I've added a some tests, let me know if there is anything else needed.

2022-02-23 16:45 UTC, AFineDayFor approved these changes

2022-02-23 17:54 UTC, merged