Docs/doc 95/doc 119/technical terms batch and request
fivetran/great_expectations pull request #4227
Opened 2022-02-17 17:06 UTC by Rachel-Reverie

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- Update technical term page for Batches
- Add technical term page for Batch Requests

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

### Definition of Done
Please delete options that are not relevant.

- [X] I have made corresponding changes to the documentation

Thank you for submitting!

2022-02-17 22:26 UTC, joshua-stauffer requested changes
This is great! While reviewing, I uncovered some issues with the batch request diagram, so reworked and created PR to incorporate.

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/batch.md
Consider adding a line about how a Batch interacts with a Validator, since Metrics, Validation, and Profiling are mentioned above, but only Metrics and Profiling are mentioned here.

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/batch.md
>  Instantiating a Batch does not necessarily “fetch” the data by immediately running a query or pulling data into memory. Instead, think of a Batch as a wrapper that includes the information that you w
not sure why, but this note is not rendering correctly for me

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/batch.md
>  - *Batch Definition* - A generic description of the Batch built directly from the Batch Request. It is not directly tied to the language of the source system, but it includes the specific parameters
These three definitions are useful and informative, but feel redundant with the Design Motivations section below. Consider combining?

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/batch.md
>  Consequently, the best way to understand what "makes a batch a batch" is the act of attending to it. The batch is the fundamental unit that Great Expectations will validate and about which it will co
What's "the act of attending to.." a batch? creating it? using it? It might just be me, but I find this a bit difficult to parse. That being said, I'm unable to come up with a better alternative!

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +Definition includes the Data Connector Name and Execution Environment Name, choosing a unique Data Asset name makes it
Execution Environment Name looks like it's a technical term, but I can't find it anywhere in the code. Should this be Datasource Name?

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +    * The BatchRequest can also include a section called `batch_spec_passthrough` to make it easy to directly
Love this! would recommend being consistent with formatting --  BatchRequest, BatchDefinition, and Batch are mostly formatted as code, but in lines 43, 44, 46, and 48 are not.

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +      communicate parameters to a specific ExecutionEngine.
Execution Engine is generally written as two words, but here and in line 74 and 91 it's combined.

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +![Image](https://lucid.app/publicSegments/view/429a4083-ad56-477c-907a-671df36e3346/image.png)
I've found this image to be super useful, but am wondering if it is still accurate. To me, it looks like the `get_batch_list_from_batch_request` contains the logic we're concerned with, and it makes two subcalls -- first, to `data_connector.get_batch_definition_list_from_batch_request` (as indicated), and then `data_connector.get_batch_data_and_metadata`, which returns `batch_data`, `batch_spec`, and `batch_markers` . Inside `get_batch_data_and_metadata`, the Data Connector builds the batch spec, and obtains the `batch_spec` and `batch_markers` from the Execution Engine, before returning it all to the Datasource.

If this is correct, we should probably update the image -- it's already complex enough, no need to confuse folks further :smile:

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +    * When resolved, the `BatchRequest` may point to many `BatchDefinitions` and Batches.
I would consider moving the batch request code example from line 52 to here -- something like
```python
batch_request={
     "datasource": "myds",
     "data_connector": "pipeline",
     "in_memory_dataset": df,
     "data_connector_query" : {
       "batch_filter_parameters" : {
           "airflow_run_id": my_run_id,
           "other_key": my_other_key
       }
       "custom_filter_function": my_filter_fn,
       "limit": 10,
       "index": Optional[Union[int, list, tuple, slice, str]],  # examples: 0; "-1"; [3:7]; "[2:4]"
     },
     "sampling": {
         "limit": 1000,
         "sample": 0.1
     }
 }
```

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +DataSource.get_batch_list_from_batch_request(batch_request={
If `batch_request` is defined above, this could be updated to be something like:
```python
batch_request_list = Datasource.get_batch_list_from_batch_request(batch_request=batch_request)
```

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +    * When resolved, the `BatchRequest` may point to many `BatchDefinitions` and Batches.
might be nice to indicate that a batch request can be defined as a dict or as an object:
```python
batch_request = BatchRequest(
    datasource_name="myds",
    # etc
)
```

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +![Image](https://lucid.app/publicSegments/view/429a4083-ad56-477c-907a-671df36e3346/image.png)
update: after a deep dive this afternoon, I rebuilt the diagram, and reworked this section to reflect in [PR 4233](https://github.com/great-expectations/great_expectations/pull/4233)

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +    * The BatchRequest can also include a section called `batch_spec_passthrough` to make it easy to directly
incorporated in [pr 4233](https://github.com/great-expectations/great_expectations/pull/4233)

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +      communicate parameters to a specific ExecutionEngine.
incorporated in [pr 4233](https://github.com/great-expectations/great_expectations/pull/4233)

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +    * When resolved, the `BatchRequest` may point to many `BatchDefinitions` and Batches.
incorporated in [pr 4233](https://github.com/great-expectations/great_expectations/pull/4233)

2022-02-17 22:26 UTC, joshua-stauffer commented on docs/terms/_batches_and_batch_requests.mdx
> +DataSource.get_batch_list_from_batch_request(batch_request={
incorporated in [pr 4233](https://github.com/great-expectations/great_expectations/pull/4233)

2022-02-22 19:52 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +DataSource.get_batch_list_from_batch_request(batch_request={
PR #4233 has been merged.

2022-02-22 19:52 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +    * When resolved, the `BatchRequest` may point to many `BatchDefinitions` and Batches.
PR #4233 has been merged.

2022-02-22 19:52 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +![Image](https://lucid.app/publicSegments/view/429a4083-ad56-477c-907a-671df36e3346/image.png)
PR #4233 has been merged.

2022-02-22 19:53 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +      communicate parameters to a specific ExecutionEngine.
PR #4233 has been merged.

2022-02-22 19:53 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +    * The BatchRequest can also include a section called `batch_spec_passthrough` to make it easy to directly
PR #4233 has been merged.

2022-02-23 19:44 UTC, Rachel-Reverie commented on docs/terms/batch.md
Line added.

2022-02-23 19:48 UTC, Rachel-Reverie commented on docs/terms/batch.md
>  Instantiating a Batch does not necessarily “fetch” the data by immediately running a query or pulling data into memory. Instead, think of a Batch as a wrapper that includes the information that you w
Fixed. (The tag "Note" should have been "note")

2022-02-23 19:52 UTC, Rachel-Reverie commented on docs/terms/batch.md
>  - *Batch Definition* - A generic description of the Batch built directly from the Batch Request. It is not directly tied to the language of the source system, but it includes the specific parameters
I've consolidated the sections.

2022-02-23 20:03 UTC, Rachel-Reverie commented on docs/terms/_batches_and_batch_requests.mdx
> +Definition includes the Data Connector Name and Execution Environment Name, choosing a unique Data Asset name makes it
After digging around in the code, I think that's the case.  I've updated it accordingly.

2022-02-23 20:08 UTC, Rachel-Reverie commented on docs/terms/batch.md
>  Consequently, the best way to understand what "makes a batch a batch" is the act of attending to it. The batch is the fundamental unit that Great Expectations will validate and about which it will co
I added a clarifying line based on my understanding.  Basically: The act of defining how a Datasource's data is sliced (even if that means defining it as a single slice containing all data) is in and of itself the act of determining what makes those defined slices "a Batch."

2022-02-24 17:04 UTC, joshua-stauffer commented on docs/terms/batch.md
>  Consequently, the best way to understand what "makes a batch a batch" is the act of attending to it. The batch is the fundamental unit that Great Expectations will validate and about which it will co
sounds good, thanks for the response 👍

2022-02-24 17:06 UTC, joshua-stauffer approved these changes
Thanks for incorporating those changes -- this looks great!

2022-02-24 20:17 UTC, merged