[FEATURE] Update usage stats schema to account for RBP's run() payload
fivetran/great_expectations pull request #4266
Opened 2022-02-23 21:02 UTC by cdkini

Changes proposed in this pull request:
- Update JSON schema to account for new payload corresponding to `RBP.run()`
- Tests to validate schema changes

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

2022-03-01 21:45 UTC, cdkini commented on great_expectations/core/usage_statistics/schemas.py
> +        "anonymized_datasource_name": anonymized_datasource_name_schema,
No such luck narrowing this down @anthonyburdi @alexsherstinsky - if the definition is used anywhere in the hierarchy of the given object, it must be included in the definitions keys.

I'll keep reading the JSON Schema guide to see if we have a better solution but this seems to track with the rest of the schemas noted herein.

2022-03-02 06:30 UTC, alexsherstinsky commented
@cdkini Everything looks good -- I just think that the reason that the usage statistics messages tests are failing is because they run against the QA environment.  So for that you actually have to do the following:
1) Get the schema into DEV environment;
2) Implement the messages tests and run them (be sure to turn off `aws` by commenting out the decorator `@pytest.mark.aws_integration` in `tests/integration/usage_statistics/test_usage_statistics_messages.py`) and setting the URL to `dev` (in `tests/integration/usage_statistics/test_integration_usage_statistics.py` on line 13);
3) Issue pull request from the internal repository with the JSON schema update;
4) Once all tests pass in `dev`, deploy to `QA` -- and now this PR should get all tests passing -- you may want to ask @anthonyburdi and me to re-review this PR when the messages tests are in it (just in case).
5) Once this PR is merged, deploy the JSON schema to the `PROD` environment.

@anthonyburdi Did I miss anything or give incorrect pointers?  Thanks!

2022-03-02 06:31 UTC, alexsherstinsky requested changes
@cdkini Please see comments -- getting close -- happy to discuss.  Thanks!

2022-03-02 16:29 UTC, anthonyburdi commented
> @cdkini Everything looks good -- I just think that the reason that the usage statistics messages tests are failing is because they run against the QA environment. So for that you actually have to do the following:
> 
> 1. Get the schema into DEV environment;
> 2. Implement the messages tests and run them (be sure to turn off `aws` by commenting out the decorator `@pytest.mark.aws_integration` in `tests/integration/usage_statistics/test_usage_statistics_messages.py`) and setting the URL to `dev` (in `tests/integration/usage_statistics/test_integration_usage_statistics.py` on line 13);
> 3. Issue pull request from the internal repository with the JSON schema update;
> 4. Once all tests pass in `dev`, deploy to `QA` -- and now this PR should get all tests passing -- you may want to ask @anthonyburdi and me to re-review this PR when the messages tests are in it (just in case).
> 5. Once this PR is merged, deploy the JSON schema to the `PROD` environment.
> 
> @anthonyburdi Did I miss anything or give incorrect pointers? Thanks!

@alexsherstinsky You said it perfectly! We just did step 4, ready to merge this PR!

2022-03-02 16:45 UTC, anthonyburdi approved these changes
Approving to not slow you down but I would like to see one more example event using custom classes. Otherwise all looks great, love the handling of "required" fields.

2022-03-02 16:45 UTC, anthonyburdi commented on great_expectations/core/usage_statistics/schemas.py
> +        "anonymized_datasource_name": anonymized_datasource_name_schema,
All good, thanks for checking!

2022-03-02 16:45 UTC, anthonyburdi commented on tests/integration/usage_statistics/test_usage_statistics_messages.py
> +        {
I would like to see one more example event message here with custom classes.

2022-03-02 17:27 UTC, cdkini commented on tests/integration/usage_statistics/test_usage_statistics_messages.py
> +                "anonymized_rules": [
@anthonyburdi here's the additional test case with 2 rules. The first has recognized parents and the second does not.

2022-03-02 20:23 UTC, alexsherstinsky approved these changes
LGTM

2022-03-02 20:26 UTC, merged