[MAINTENANCE] Enable "rule_based_profiler.run()" Method to Accept Batch Data Arguments Directly
fivetran/great_expectations pull request #4409
Opened 2022-03-14 18:56 UTC by alexsherstinsky

### Scope
The logic of running profiler with data has to change in a way that reconciles the configuration first and then applies `Batch` data (as either list of `Batch` objects or `batch_request`, but not both) second.  This is important, because configuration has to be serializable, while `Batch` objects and/or `batch_request` are generally not.  However, the Rule-Based Profiler architecture mandates that all `Batch` objects and/or full `batch_request` is passed to all relevant `Builder` components (each of which contains internal logic for selecting `Batch` objects of interest).  This provides flexibility in running profiler.

### Notes
* Existing unit tests have been updated, changing the `Mock` points where necessary.
* Existing `profiler.add_rule()` tests have been updated, requiring the dictionary version of `batch_request` to be passed.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
- JIRA: GREAT-464/GREAT-498/GREAT-666
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-03-14 20:15 UTC, cdkini commented on great_expectations/validator/validator.py
> +        )[0]
Nitpick - could we split out the creation of the list and the retrieval of the first element into separate lines?

2022-03-14 20:15 UTC, cdkini commented on great_expectations/validator/validator.py
> +            pass  # No action is needed.
logging?

2022-03-14 20:15 UTC, cdkini commented on great_expectations/validator/validator.py
> +        expectation_suite = copy.deepcopy(self.expectation_suite)
When working with a class internals, should we be using getters/setters? I think the private variable is totally fine here and is actually the better practice.

2022-03-14 20:15 UTC, cdkini commented on tests/rule_based_profiler/test_rule_based_profiler.py
> +)
wow that's a **lot** of mocking - is there a better way to do this?

2022-03-14 20:15 UTC, cdkini commented on great_expectations/rule_based_profiler/rule_based_profiler.py
> +                    match_type="domain",
Enum?

2022-03-14 20:15 UTC, cdkini commented on great_expectations/rule_based_profiler/rule_based_profiler.py
> +                )
noooooo can we avoid setattr at all?

2022-03-14 20:15 UTC, cdkini commented on great_expectations/rule_based_profiler/rule_based_profiler.py
> +    def self_check(self, pretty_print=True) -> dict:
please annotate the boolean value

2022-03-14 20:18 UTC, Shinnnyshinshin requested changes
Thank you Alex this looks great. My request is that `BatchRequest` be allowed to be passed in a `Union[RuntimeBatchRequest, BatchRequest, dict]`, as we do in other parts of the codebase.  This would allow for the behavior to be consistent with other GE machinery.

2022-03-14 20:19 UTC, cdkini commented on great_expectations/validator/validator.py
> +            pass  # No action is needed.
Please raise Exception

2022-03-14 20:21 UTC, cdkini commented on tests/rule_based_profiler/test_rule_based_profiler.py
> +)
try mocking ParameterBuilder?

2022-03-15 00:19 UTC, Shinnnyshinshin commented on great_expectations/data_context/data_context.py
> +        batch_request: Optional[Union[BatchRequest, RuntimeBatchRequest, dict]] = None,
❤️

2022-03-15 00:24 UTC, Shinnnyshinshin approved these changes
LGTM @alexsherstinsky thank you very very much

2022-03-15 00:24 UTC, Shinnnyshinshin commented on great_expectations/rule_based_profiler/expectation_configuration_builder/default_expectation_configuration_builder.py
> +    ) -> Optional[ExpectationConfiguration]:
Thank you for catching stuff like this @alexsherstinsky

2022-03-15 00:24 UTC, Shinnnyshinshin commented on great_expectations/rule_based_profiler/types/builder.py
> +
In `builder.py`! Thank you for making this move @alexsherstinsky 

cc @cdkini

2022-03-15 00:24 UTC, Shinnnyshinshin commented on great_expectations/validator/validator.py
> +        )[0]
I really like this approach @alexsherstinsky thank you

2022-03-15 00:24 UTC, Shinnnyshinshin commented on great_expectations/validator/validator.py
> +            )
❤️

2022-03-15 01:48 UTC, merged