Maintenance/improve get validator functionality
fivetran/great_expectations pull request #4661
Opened 2022-04-04 14:15 UTC by abegong

Changes proposed in this pull request:
- Makes it possible to use `context.get_validator` without specifying an `ExpectationSuite` (by name, id, or otherwise.) This behavior was already supported by `Validator.__init__`. It just hadn't been enabled for `DataContext.get_validator`.
- Makes it possible to pass a single `Batch` to `context.get_validator`

Both of these additions will improve usability of the top-level API in DataContext.

Both are tested with a single unit test.

2022-04-04 16:02 UTC, cdkini commented on tests/data_context/test_data_context.py
> +    empty_data_context, tmp_path_factory
`tmp_path_factory` is session-scoped, which can cause state to bleed into other tests when the whole suite is run. I think we've been making a move to `tmp_path` for that reason.

2022-04-04 16:02 UTC, cdkini commented on tests/data_context/test_data_context.py
> +    empty_data_context_stats_enabled, tmp_path_factory
do we want stats enabled here? I think we should refrain from using this fixture here since we don't test analytics.

2022-04-04 16:02 UTC, cdkini commented on tests/data_context/test_data_context.py
> +    context: DataContext = empty_data_context_stats_enabled
Instead of using a context and updating the filesystem, could we instantiate a `BaseDataContext` like we do here: https://github.com/great-expectations/great_expectations/blob/develop/tests/expectations/test_expectation_arguments.py#L39-L86

An approach like this would remove the need for I/O and improve performance. We might need to do some mocking though happy to dig in further as needed.

2022-04-04 16:02 UTC, cdkini commented on tests/data_context/test_data_context.py
> +    assert type(my_validator.get_expectation_suite()) == ExpectationSuite
Nitpick - Could we use `isinstance` just to be consistent? This method accounts for things like inheritance hierarchies and is a bit safer.

2022-04-04 16:02 UTC, cdkini commented on tests/data_context/test_data_context.py
> +    context = empty_data_context
Same general note about context - I think we could probably use `BaseDataContext` and mock any I/O.

2022-04-04 17:05 UTC, alexsherstinsky commented on great_expectations/data_context/data_context.py
> +        batch: Optional[Batch] = None,
@abegong I believe that this should be `batch_list: List[Batch]` -- do you agree?  At least some way to accept list of `Batch` objects, even if we must support the passing of a single `Batch` object.  Thanks

2022-04-04 17:06 UTC, alexsherstinsky requested changes
@abegong Small change requested (happy to discuss) -- I really like what this PR will provide (I believe that we even had a JIRA item for it in the Backlog)!  Thanks!

2022-04-04 20:01 UTC, abegong commented on great_expectations/data_context/data_context.py
> +        batch: Optional[Batch] = None,
For usability sake I think it's important to take a single `Batch` as an argument.

We could also add the option to pass a `batch_list`.

2022-04-04 20:16 UTC, alexsherstinsky commented on great_expectations/data_context/data_context.py
> +        batch: Optional[Batch] = None,
@abegong I agree -- and, if possible, would prefer for both to be supported in the same pull request.  Thanks!

2022-04-06 02:26 UTC, abegong commented on great_expectations/data_context/data_context.py
> +        batch: Optional[Batch] = None,
I've made this change

2022-04-06 02:26 UTC, abegong commented on tests/data_context/test_data_context.py
> +    assert type(my_validator.get_expectation_suite()) == ExpectationSuite
```suggestion
    assert isinstance(my_validator.get_expectation_suite(), ExpectationSuite)
```

2022-04-06 02:28 UTC, abegong commented
@cdkini , @alexsherstinsky , I've responded to all comments.

2022-04-06 05:03 UTC, alexsherstinsky approved these changes
LGTM!

2022-04-06 11:52 UTC, merged