[FEATURE] Enable self-initializing capabilities for `ExpectColumnProportionOfUniqueValuesToBeBetween`
fivetran/great_expectations pull request #4929
Opened 2022-04-22 15:13 UTC by cdkini

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/en/latest/contributing/contribution_checklist.html).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @ge-cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-04-25 14:44 UTC, cdkini commented on great_expectations/expectations/core/expect_column_proportion_of_unique_values_to_be_between.py
> +                        "max_value": 1.0,
Values are always consistent so didn't see a need to reference through variables here - @alexsherstinsky this resolved the issue we were seeing with both min_value and max_value being `0.0` but let me know if you'd like to discuss.

2022-04-25 14:44 UTC, cdkini commented on great_expectations/validator/validator.py
> -        auto: Optional[bool] = expectation_kwargs.get("auto")
When possible, let's avoid nullable values. This is only ever used in a boolean context so I've changed this.

2022-04-25 14:45 UTC, cdkini commented on tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
> +) -> None:
Test follows same convention as prior self-initializing expectations - we should eventually refactor or parameterize since this is getting a little overly verbose.

Don't think this PR is the right place for it but I can follow up after the remaining self-initializing expectations.

2022-04-25 22:09 UTC, alexsherstinsky commented on tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
> +        suite = context.get_expectation_suite(
@cdkini Could you please look into the viability of using `get_validator_with_expectation_suite()` (and/or `get_or_create_expectation_suite()` which it utilizes) -- examples are in the same module.  Thanks!

2022-04-25 22:10 UTC, alexsherstinsky requested changes
@cdkini Small change request in favor of a canned utility method.  Thanks!

2022-04-26 13:16 UTC, alexsherstinsky approved these changes
LGTM!

2022-04-26 15:25 UTC, merged