[MAINTENANCE] Splitter cleanup and enhancements
fivetran/great_expectations pull request #4984
Opened 2022-04-28 21:44 UTC by anthonyburdi

Changes proposed in this pull request:
- [Use 'multi' method in to_sql for redshift](https://github.com/great-expectations/great_expectations/commit/43d6afe48bf0cb2063932a826a9e46397a3aab84)
- [Move sqlalchemy_data_splitter.py into execution_engine/split_and_samp…](https://github.com/great-expectations/great_expectations/commit/c0e7a477cf5fb101f6386a77b22cb5183c2730a7) 
- [Remove underscore prefix from examples](https://github.com/great-expectations/great_expectations/commit/1dbaff75d92b7408175205276f212d08d4c6b344)

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-04-28 22:08 UTC, Shinnnyshinshin commented on tests/integration/db/test_sql_data_splitting.py
> +        if dialect in dialects_supporting_multiple_values_in_single_insert_clause
❤️

2022-04-28 22:08 UTC, Shinnnyshinshin commented on tests/integration/db/test_sql_data_splitting.py
> +        if dialect in dialects_supporting_multiple_values_in_single_insert_clause
I thought this was a really elegant solution to the issue. Thank you @anthonyburdi

2022-04-28 22:09 UTC, alexsherstinsky approved these changes
LGTM

2022-04-28 22:09 UTC, Shinnnyshinshin commented
I see one failing test for `docs-integration`. Maybe a attribute name needs to be adjusted from private to public? 

`great_expectations.exceptions.exceptions.DatasourceInitializationError: Cannot initialize datasource taxi_datasource, error: 'InferredAssetSqlDataConnector' object has no attribute 'split_on_converted_datetime'`

2022-04-28 22:10 UTC, Shinnnyshinshin requested changes
Very close. One failing integration test I believe. Otherwise looks great :)

2022-04-29 00:18 UTC, cdkini approved these changes
LGTM!

2022-04-29 21:58 UTC, Shinnnyshinshin approved these changes
LGTM @anthonyburdi thank you !

2022-04-29 21:58 UTC, Shinnnyshinshin commented on great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py
>                      table_name, splitter_method_name, splitter_kwargs
❤️

2022-04-29 21:58 UTC, Shinnnyshinshin commented on tests/datasource/data_connector/test_sql_data_connector.py
> +            splitter_method: {splitter_method_name_prefix}split_on_column_value
super interesting and elegant way to deal with this @anthonyburdi . Love what you're doing with introducing parameterized tests.

2022-04-29 21:58 UTC, merged