[FEATURE] Enable self-initializing `ExpectColumnMedianToBeBetween`
fivetran/great_expectations pull request #4987
Opened 2022-04-28 23:38 UTC by cdkini

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-04-29 22:02 UTC, Shinnnyshinshin commented on tests/integration/profiling/rule_based_profilers/test_profiler_user_workflows.py
> +@freeze_time(TIMESTAMP)
❤️

2022-04-29 22:02 UTC, Shinnnyshinshin approved these changes
This looks great too @cdkini Thank you

2022-04-29 23:32 UTC, alexsherstinsky requested changes
@cdkini This will need to be updated once #4997 is merged (please use the same order of arguments).  Thank you!

2022-05-02 13:48 UTC, alexsherstinsky approved these changes
LGTM

2022-05-02 14:14 UTC, merged