[BUGFIX] Increase precision from 4 to 5 for `numeric_columns_high_precision_rule` in `OnboardingDataAssistant`
fivetran/great_expectations pull request #5296
Opened 2022-06-10 19:54 UTC by NathanFarmer

Changes proposed in this pull request:
- All Getting Started Guide expectations should be passing

### Definition of Done
- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

2022-06-11 02:05 UTC, alexsherstinsky commented on great_expectations/render/renderer/v3/suite_profile_notebook_renderer.py
> +    #     "round_decimals": None,   # parameters will be rounded to the maximum number of decimal places for metrics that increase precision
@NathanFarmer No, please let us leave it at 4 -- that was a good approach, meaningful for high precision.  Thank you.

2022-06-11 02:05 UTC, alexsherstinsky commented on great_expectations/rule_based_profiler/data_assistant/onboarding_data_assistant.py
> +            "quantile_statistic_interpolation_method": "linear",
@NathanFarmer This feels like it might break other rules.

2022-06-11 02:06 UTC, alexsherstinsky commented on great_expectations/rule_based_profiler/parameter_builder/numeric_metric_range_multi_batch_parameter_builder.py
> +                metric_precision: float = float(str(metric_values[0])[::-1].find("."))
@NathanFarmer This does not feel right -- I actually suspect that `Expectation` is being too strict instead of doing the "near" comparison.

2022-06-11 02:07 UTC, alexsherstinsky commented on tests/cli/test_suite.py
> +    #     "round_decimals": None,   # parameters will be rounded to the maximum number of decimal places for metrics that increase precision
@NathanFarmer No, please let us leave it at 4 -- that was a good approach, meaningful for high precision.  Thank you.

2022-06-11 02:07 UTC, alexsherstinsky commented on tests/cli/test_suite.py
> +    #     "round_decimals": None,   # parameters will be rounded to the maximum number of decimal places for metrics that increase precision
@NathanFarmer No, please let us leave it at 4 -- that was a good approach, meaningful for high precision.  Thank you.

2022-06-11 02:07 UTC, alexsherstinsky commented on tests/render/renderer/v3/test_suite_profile_notebook_renderer.py
> +    #     "round_decimals": None,   # parameters will be rounded to the maximum number of decimal places for metrics that increase precision
@NathanFarmer No, please let us leave it at 4 -- that was a good approach, meaningful for high precision.  Thank you.

2022-06-11 02:07 UTC, alexsherstinsky commented on tests/rule_based_profiler/data_assistant/test_onboarding_data_assistant.py
> +            "round_decimals": None,
@NathanFarmer No, please let us leave it at 4 -- that was a good approach, meaningful for high precision.  Thank you.

2022-06-11 02:09 UTC, alexsherstinsky requested changes
@NathanFarmer I feel that this work was very helpful, even if I would like to recommend for the present pull request to be ultimately closed.  Could you please not merge it yet, even if/when the Azure checks pass.  I would like to approach a different avenue, which, if succeeds, will be simpler -- and then we can close this pull request (I will keep you posted).  Thank you! /cc @Rachel-Reverie @donaldheppner

2022-06-13 16:27 UTC, NathanFarmer commented
This was addressed by: #5296

2022-06-13 16:27 UTC, closed without merging