[DOCS] DOC-286 how to add support for the auto initializing framework to a custom expectation
fivetran/great_expectations pull request #5300
Opened 2022-06-13 12:47 UTC by Rachel-Reverie

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- Adds a new how-to guide detailing how to add support for auto-initializing framework to a custom expectation by copying and modifying an existing RBP configuration.
- Adds the new how-to guide to the ToC

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [X] I have made corresponding changes to the documentation

Thank you for submitting!

2022-06-13 17:02 UTC, rdodev approved these changes

2022-06-16 12:39 UTC, donaldheppner approved these changes

2022-06-16 12:43 UTC, donaldheppner requested changes
we need to hold on this since the code is "self initializing" and the docs are "auto-initializing"; I'd like to change the code, issue a release, and then publish the docs

2022-06-16 14:30 UTC, Rachel-Reverie commented
> we need to hold on this since the code is "self initializing" and the docs are "auto-initializing"; I'd like to change the code, issue a release, and then publish the docs

Sounds good, consistency is important.  I think the same logic applies to [PR 525](https://github.com/great-expectations/great_expectations/pull/5205), then, so I'll put it on hold as well.

2023-01-27 14:28 UTC, donaldheppner approved these changes

2023-01-30 14:20 UTC, merged