[DOCS] revert getting started tutorial to RBP process
fivetran/great_expectations pull request #5307
Opened 2022-06-14 13:01 UTC by Rachel-Reverie

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- copies the data assistant version of the create expectations tutorial page to the docs_pending folder (so it can be restored once the Onboarding Assistant and Data Assistant docs are in place/APIs are stable)
- reverts the guidance on the "Create Expectations" tutorial page to give instructions for working with a RBP. (Leaves the updates on the "Connect to data" tutorial page in place; they should reflect the updated code to remove the prior deprecation warnings).

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [X] I have made corresponding changes to the documentation

Thank you for submitting!

2022-06-14 13:02 UTC, ghost commented
<details>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=5307&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations">Click on the image</a> for a new way to code review</b>
</summary>

  - Make big changes easier — review code in small groups of related files
  - Know where to start — see the whole change at a glance
  - Take a code tour — explore the change with an interactive tour
  - Make comments and review — all fully sync’ed with github

    [Try it now!](https://app.codesee.io/r/reviews?pr=5307&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations)
</details>

[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/great-expectations/great_expectations/5307/d63c9437/3241a6f3fe1ad24f3aaf7ccbb0db0ff745dc00cb.svg)](https://app.codesee.io/r/reviews?pr=5307&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2022-06-14 13:51 UTC, kenwade4 approved these changes

2022-06-14 13:58 UTC, rdodev approved these changes

2022-06-14 17:00 UTC, anthonyburdi requested changes
Just a few small changes requested to the image

2022-06-14 17:00 UTC, anthonyburdi commented on docs/tutorials/getting_started/tutorial_create_expectations.md
> +![Cell3](../../images/getting_started_tutorial/tutorial_create_expectations_cell3.png)
@Rachel-Reverie I just noticed a few items to change in this image, see my friction log for more details.

2022-06-15 17:12 UTC, anthonyburdi approved these changes
LGTM!

2022-06-15 17:28 UTC, Rachel-Reverie commented on docs/tutorials/getting_started/tutorial_create_expectations.md
> +![Cell3](../../images/getting_started_tutorial/tutorial_create_expectations_cell3.png)
Fixed with update to png for that cell.

2022-06-15 23:18 UTC, merged