[FEATURE][MAINTENANCE] Revamped expect_profile_numeric_columns_diff_between_exclusive_threshold_range
fivetran/great_expectations pull request #5493
Opened 2022-07-13 14:44 UTC by stevensecreti

Changes proposed in this pull request:
- Renamed  expect_profile_numeric_columns_diff_between_threshold_range to expect_profile_numeric_columns_diff_between_exclusive_threshold_range
- Moved the custom metrics and metric provider out of this custom expectation and into their own custom metric files
- Moved a large majority of the _validate logic in this custom expectation into the top level metric written in this custom expectation file. (Top level metric makes use of _get_evaluation_dependencies() to call other custom metrics)
- Restructured capitalone_dataprofiler_expectations contrib package directory structure to match great_expectation's core expectations directory structure in order to make use of custom metrics within our custom expectations (Move sibling directory metrics into expectations directory)

Previous Design Review notes:
- History on Revamped Expectation: #5467 

### Definition of Done

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas

2022-07-13 14:46 UTC, stevensecreti commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/metrics/__init__.py
> +# Make sure to include any Metrics your want exported below!
@talagluck @austiezr Just want to make sure changing this directory structure (moving metrics directory into expectations) is okay. Thanks!

2022-07-14 16:04 UTC, taylorfturner commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/metrics/__init__.py
> +# Make sure to include any Metrics your want exported below!
bump @austiezr

2022-07-14 19:02 UTC, austiezr requested changes
Hey @stevensecreti (& @taylorfturner )! Just a couple of notes here; love seeing this motion! 🚀

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/metrics/__init__.py
> +# Make sure to include any Metrics your want exported below!
Hey @stevensecreti ! The preferred pattern here would be to maintain the original structure, with `metrics`, `expectations`, and `profilers` living at the same level, and making relevant imports *through* the actual installed `capitalone_dataprofiler_expectations` package.

This supports local usage & testing of the installed package, prevents unintended behavior for users that may have cloned code but not actually installed the package & dependencies, and better supports testing & display for our gallery.

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
> +)
```suggestion
)
from .expect_profile_numeric_columns_diff_less_than_threshold import (
    ExpectProfileNumericColumnsDiffLessThanThreshold
)
from .expect_profile_numeric_columns_diff_greater_than_threshold import (
    ExpectProfileNumericColumnsDiffGreaterThanThreshold
) 
```

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
>  )
```suggestion
```

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_exclusive_threshold_range.py
> +from util import is_value_between_bounds, replace_generic_operator_in_report_keys
```suggestion
from capitalone_dataprofiler_expectations.metrics.data_profiler_metrics.data_profiler_profile_metric_provider import (
    DataProfilerProfileMetricProvider,
)
from capitalone_dataprofiler_expectations.expectations.util import (
    is_value_between_bounds,
    replace_generic_operator_in_report_keys
)
```

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_greater_than_threshold.py
> +)
```suggestion
from capitalone_dataprofiler_expectations.metrics.data_profiler_metrics.data_profiler_profile_metric_provider import (
    DataProfilerProfileMetricProvider,
)
from capitalone_dataprofiler_expectations.expectations.util import (
    is_value_greater_than_threshold,
    replace_generic_operator_in_report_keys,
)
```

2022-07-14 19:02 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_less_than_threshold.py
> +from util import is_value_less_than_threshold, replace_generic_operator_in_report_keys
```suggestion
from capitalone_dataprofiler_expectations.metrics.data_profiler_metrics.data_profiler_profile_metric_provider import (
    DataProfilerProfileMetricProvider,
)
from capitalone_dataprofiler_expectations.expectations.util import (
    is_value_less_than_threshold, 
    replace_generic_operator_in_report_keys,
)
```

2022-07-14 21:22 UTC, stevensecreti commented
Should be good to go. Thanks! @austiezr

2022-07-14 21:32 UTC, austiezr requested changes
Thanks @stevensecreti! A couple more quick fixes related to `expect_profile_numeric_columns_diff_between_inclusive_threshold_range` and then this should be good to merge.

2022-07-14 21:32 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/__init__.py
> +)
We'll want to import `expect_profile_numeric_columns_diff_between_inclusive_threshold_range` here as well:

```suggestion
) 
from .expect_profile_numeric_columns_diff_between_inclusive_threshold_range import (
    ExpectProfileNumericColumnsDiffBetweenInclusiveThresholdRange,
)
```

2022-07-14 21:32 UTC, austiezr commented on contrib/capitalone_dataprofiler_expectations/capitalone_dataprofiler_expectations/expectations/expect_profile_numeric_columns_diff_between_inclusive_threshold_range.py
> +from util import is_value_between_bounds, replace_generic_operator_in_report_keys
Same alteration needed here as previously:

```suggestion
from capitalone_dataprofiler_expectations.expectations.util import (
    is_value_between_bounds,
    replace_generic_operator_in_report_keys,
)
from capitalone_dataprofiler_expectations.metrics.data_profiler_metrics.data_profiler_profile_metric_provider import (
    DataProfilerProfileMetricProvider,
)
```

2022-07-15 14:18 UTC, stevensecreti commented
Can't believe I missed that one! Thanks @austiezr. Should be all set.

2022-07-15 16:07 UTC, austiezr approved these changes
LGTM! Thanks @stevensecreti ! 🚀

2022-07-15 17:06 UTC, merged