[CONTRIB] expect_column_pair_values_to_have_difference_of_custom_perc…
fivetran/great_expectations pull request #5661
Opened 2022-08-03 12:07 UTC by exteli

…entage

Expect two columns to have a row-wise difference less than custom percentage
* add the expectation expect_column_pair_values_to_have_difference_of_custom_percentage
* add the class ExpectColumnPairValuesToHaveDifferenceOfCustomPercentage
* add test (pandas and pyspark)

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-08-03 12:22 UTC, exteli commented
@cla-bot check

2022-08-03 14:51 UTC, austiezr commented
@cla-bot check

2022-08-03 14:54 UTC, austiezr requested changes
Hey @exteli ! Stoked to see this come in.

One quick fix in the code; additionally, it looks like we need a pass with our [linting tools](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style#tasks), and a double-check on the CLA.

2022-08-03 14:54 UTC, austiezr commented on contrib/experimental/great_expectations_experimental/expectations/expect_column_pair_values_to_have_difference_of_custom_percentage.py
> +    assert check["passed"] is True
This block can be removed; it is generally only included for integration testing on expectations referenced in certain documentation.

2022-08-04 08:45 UTC, exteli commented
@kyleaton I already signed the CLA (Superconductive: Individual Contributor License Agreement v1.0) but I keep having the same problem in the pull request.
verification/cla-signed — Missing cla for users {'exteli'}.
Could you help me, please.
Thanks in advance.

2022-08-04 11:30 UTC, exteli commented
> austiezr

Hi, @austiezr,  I already signed the CLA (Superconductive: Individual Contributor License Agreement v1.0) but I keep having the same problem in the pull request.
verification/cla-signed — Missing cla for users {'exteli'}.
Could you help me, please.
Thanks in advance.

2022-08-04 15:38 UTC, kyleaton commented
@cla-bot check

2022-08-04 15:41 UTC, austiezr approved these changes
LGTM! Thanks @exteli ! 🚀

2022-08-05 08:08 UTC, exteli commented
ee

2022-08-05 08:16 UTC, exteli commented
> LGTM! Thanks @exteli ! 🚀

Hi @austiezr.
The pull request went well but I can not see the changes in branch great-expectations:develop.
Do I have to do anything else? (I do not see merge button).

Thanks in advance.

2022-08-05 21:40 UTC, merged