Subject: Support to include ID/PK in validation result for each row t…
fivetran/great_expectations pull request #5876
Opened 2022-08-30 05:00 UTC by abekfenn

…hat failed an expectations

Ticket Number: #3195

Problem:

- No arguments available to configure column subset of unexpected_rows

Solution:

- Add args to subset unexpected_rows

Note:

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-08-31 16:40 UTC, austiezr requested changes
Hey @abekfenn! Thanks for the work here; love to see it! Looks like you're very close to having this functional; just a couple of small fixes and I think you'll be able to move ahead with this.

2022-08-31 16:40 UTC, austiezr commented on great_expectations/expectations/expectation.py
> +                f"{self.map_metric}.include_unexpected_index_columns",
```suggestion
                f"{self.map_metric}.unexpected_index_columns",
```

2022-08-31 16:40 UTC, austiezr commented on great_expectations/expectations/expectation.py
> +                f"{self.map_metric}.include_unexpected_index_columns"
```suggestion
                f"{self.map_metric}.unexpected_index_columns",
```

2022-08-31 16:40 UTC, austiezr commented on great_expectations/expectations/expectation.py
> +                metric_name=f"{self.map_metric}.include_unexpected_index_columns",
```suggestion
                f"{self.map_metric}.unexpected_index_columns",
```

2022-08-31 16:40 UTC, austiezr commented on tests/expectations/metrics/test_map_metric.py
> +    }
This assert will need a review once the above metric changes are in place.

2022-08-31 16:41 UTC, austiezr commented
Looks like we'll need a linting pass as well!

2022-09-01 02:27 UTC, abekfenn commented
Thanks @austiezr your feedback was very helpful. I'm definitely much closer now and was looking to add a test for an expectation that leverages the `SqlAlchemyExecutionEngine` but I don't see any existing tests or datasets that I could reference.
I assume they're out there, would you be able to point me to an example test or dataset that I could use to test an expectation with these args?

2022-09-01 17:16 UTC, austiezr commented
Hey @abekfenn ! Have you had an opportunity to check out [these tests](https://github.com/great-expectations/great_expectations/blob/develop/tests/execution_engine/test_sqlalchemy_execution_engine.py)?

2022-09-01 18:08 UTC, abekfenn commented
@austiezr I haven't seen those tests but I was looking for tests that test metric providers and the results that different configurations and providers produce. Such as those in `tests/expectations/metrics/test_map_metric.py`. I'll see if I can put something together from both test files, but surprised there are no tests that test the results produced by the metric providers for SQLAlchemy datasets.

2022-11-10 03:11 UTC, Shinnnyshinshin commented
Thank you very very much @abekfenn for getting the ball rolling, and all the work you put in. I was able to start where you left off, and have a PR for the Pandas implementation that is currently under review by the team. I'll post more updates here :)

2022-11-14 22:20 UTC, Shinnnyshinshin commented on great_expectations/expectations/metrics/map_metric_provider.py
> +        return unexpected_index_list[: result_format["partial_unexpected_count"]]
From #6329 

Added the filtering for `partial_unexpected_count` for both `unexpected_index_column` and just `unexpected_index` (existing behavior)

2022-11-14 22:21 UTC, Shinnnyshinshin commented on tests/expectations/metrics/test_map_metric.py
> +):
From #6329 

1st test for testing `partial_unexpected_count` limit

2022-11-14 22:21 UTC, Shinnnyshinshin commented on tests/expectations/metrics/test_map_metric.py
> +):
From https://github.com/great-expectations/great_expectations/pull/6329

2nd test for testing partial_unexpected_count limit

2022-11-14 22:29 UTC, anthonyburdi approved these changes
LGTM! Thank you for these changes 🙇

2022-11-14 22:31 UTC, austiezr approved these changes
❤️ 🚀 LGTM!

2022-11-14 23:08 UTC, abekfenn commented
Thanks a lot for wrapping up the changes on these @Shinnnyshinshin! 

I only see changes related to pandas but my understanding was that this feature (stemming from https://github.com/great-expectations/great_expectations/issues/3195#) is really needed in the SQL engine in order to support identification of the Pk/Id of a failed row.
This functionality already exists for pandas in GE but is not supported for SQL.
Just want to make sure that merging doesn't mean that this issue will be closed out and that we will continue work on this issue for the SQL engine implementation?

2022-11-14 23:12 UTC, Shinnnyshinshin commented
Hi @abekfenn thank you for the follow-up message 😄  Yes the next steps for us are to do the implementation for SQL and Spark (we'll be sure to do SQL first).  Wanting to thank you again for helping us get this far, and Ill be sure to update you once the SQL implementation has been implemented and merged.

2022-11-14 23:38 UTC, abekfenn commented
Awesome! Thanks so much @Shinnnyshinshin

2022-11-15 00:51 UTC, merged