[MAINTENANCE] Update aloglia scripts for new fields and replica indices
fivetran/great_expectations pull request #6049
Opened 2022-09-20 14:03 UTC by winrp17

Changes proposed in this pull request:
- Add new fields to upload to algolia exp_type, coverage_score
- Add support for replica indices for sorting
- Changes for reading .env files to load environment variables from file (for local development and testing)

- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2022-09-21 14:29 UTC, kenwade4 requested changes
Looks good. Just a typo fix needed.

2022-09-21 14:29 UTC, kenwade4 commented on assets/scripts/AlgoliaScripts/upload_s3_expectation_to_algolia.js
> +    console.log('Error ferching data from s3', error);
Typo for fetching

2022-09-22 07:25 UTC, winrp17 commented on assets/scripts/AlgoliaScripts/upload_s3_expectation_to_algolia.js
> +    console.log('Error ferching data from s3', error);
Done.

2022-09-27 15:11 UTC, kenwade4 approved these changes

2022-09-27 15:21 UTC, kyleaton commented
@cla-bot check

2022-09-27 16:49 UTC, kenwade4 approved these changes

2022-09-27 18:29 UTC, merged