Add msg
fivetran/great_expectations pull request #615
Opened 2019-08-14 19:41 UTC by abegong

2019-08-15 22:33 UTC, jcampbell approved these changes

2019-08-16 00:37 UTC, jcampbell requested changes
Py2 build issue

2019-08-16 23:45 UTC, jcampbell submitted a review, later dismissed

2019-08-16 23:52 UTC, abegong commented
This PR adds an informative error message to trap a known bug in the python 2 implementation of `safe_mmkdir`

2019-08-17 00:19 UTC, jcampbell approved these changes
LGTM

2019-08-17 11:02 UTC, merged