[MAINTENANCE] Migrate additional CRUD methods from `BaseDataContext` to `AbstractDataContext`
fivetran/great_expectations pull request #6395
Opened 2022-11-18 13:27 UTC by cdkini

- refactor: move profile_datasource
- refactor: move run_validation_operator
- refactor: port over build_data_docs
- chore: remove mention of ge_cloud_mode from abstract
- chore: add docstring
- refactor: point to cloud mode
- refactor: move list methods

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2022-11-18 15:19 UTC, cdkini commented on great_expectations/data_context/data_context/base_data_context.py
> +        return self._data_context.list_checkpoints()
This pattern for checkpoints and RBP is necessary due to how we use `self._data_context`.

This will be cleaned up in a subsequent ticket such that we use `__getattr__` and/or `__getattribute__` to dynamically pass calls to the underlying `self._data_context`. This will remove the need for redefining functions like this.

2022-11-18 15:19 UTC, cdkini commented on great_expectations/data_context/store/checkpoint_store.py
> +        self, ge_cloud_mode: bool = False
We will eventually want to refactor out `ge_cloud_mode` - for now, I've opted to add a default value (as 99% of usecases will not leverage this flag).

2022-11-18 15:20 UTC, cdkini commented on tests/data_context/test_data_context_profilers.py
> -
Deleted this test as it was duplicatively testing the `self.profiler_store` property

2022-11-18 16:50 UTC, cdkini commented on great_expectations/data_context/data_context/base_data_context.py
> -    def build_data_docs(
This was migrated last PR but I forgot to delete the `BaseDataContext` impl

2022-11-18 19:43 UTC, Shinnnyshinshin commented on great_expectations/data_context/data_context/abstract_data_context.py
> +    def escape_all_config_variables(
oo this is nice :)

2022-11-18 19:44 UTC, Shinnnyshinshin commented on great_expectations/data_context/data_context/cloud_data_context.py
> +        The only difference here is the creation of a Cloud-specific `GXCloudIdentifier`
:heart:

2022-11-18 19:45 UTC, Shinnnyshinshin commented on great_expectations/data_context/store/checkpoint_store.py
>      ) -> Union[List[str], List[ConfigurationIdentifier]]:
:heart:

2022-11-18 19:46 UTC, Shinnnyshinshin approved these changes
LGTM. We're getting close!

2022-11-18 19:59 UTC, Kilo59 commented on great_expectations/data_context/data_context/abstract_data_context.py
> +    ) -> Union[str, dict, list]:
Should use a `TypeVar` here.
Let me double check this is the right syntax....

```python
from typing import TypeVar

T = TypeVar("T", str, dict, list)

 def escape_all_config_variables(
        self,
        value: T,
        dollar_sign_escape_string: str = DOLLAR_SIGN_ESCAPE_STRING,
        skip_if_substitution_variable: bool = True,
    ) -> T:
...

```

2022-11-18 20:00 UTC, Kilo59 requested changes
LGTM 1 small detail.

We should use a `TypeVar` for `escape_all_config_variables`

2022-11-19 19:29 UTC, Kilo59 reviewed
Using `T = TypeVar("T", bound=Union[dict, list, str])` is more or less the same as `Union[dict, list, str]` without the `TypeVar`. I've proposed 2 different solutions in the comments below. Both are fully implemented and can be copy pasted.

Sorry, I know this may seem like a minor point but I think we should use this opportunity to do better type narrowing. Also excited to see you take this and run. I'm sure you'll find all sorts of places where we can use these techniques.

2022-11-19 19:29 UTC, Kilo59 commented on great_expectations/data_context/data_context/abstract_data_context.py
> +T = TypeVar("T", bound=Union[dict, list, str])
```
great_expectations/data_context/data_context/abstract_data_context.py:3705: error:
Incompatible return value type (got "Dict[Any, Any]", expected "str") 
[return-value]
                return {
```
https://github.com/great-expectations/great_expectations/pull/6395/commits/88d2196ac74b0730eef634c2de8783d617b7df81
@cdkini This type warning was from your previous commit.
I didn't realize this was a recursive method. That complicates things a bit.

The point of the `TypeVar` in this case is to give a narrower return type than the union.
If I call `escape_all_config_variables` with a `dict` it will tell the type system that a `dict` will be returned rather than a `dict` or  `str` or `list`.
Making the `TypeVar` a `Union` defeats the purpose of using a `TypeVar` to begin with.

I would drop/revert the `chore: update typevar usage` commit.

There are 2 solutions here to deal with this.
1. Use the original `TypeVar` (sans `union`) and ignore the internal `return-type` warning.
2. Use a `typing.overload` instead

-------

### Use `TypeVar("T", dict, list, str)`

For `#1` I think the reason we have to do this is because of when the `TypeVar` is bound/re-bound, the type is bound to `X` type but then when the function calls itself again the type is `Y` and this causes issues. Regardless I think the most important thing is the type being returned when the stack terminates, and less so the "correctness" of the function body. So I think a single comment `# type ignore[retun-value] # recursive call expects str here` is the best approach (if the solution is still to use a `TypeVar`).

```python
# change back to T = TypeVar("T", dict, list, str)
# and just ignore the type warning on this line

        if isinstance(value, dict) or isinstance(value, OrderedDict):
            return {   # type ignore[retun-value] # recursive call expects str here
                k: self.escape_all_config_variables(
                    v, dollar_sign_escape_string, skip_if_substitution_variable
                )
```

--------

## Use `@overload`

`#2` is more "correct" in that it still retains the narrowness of the return type and shouldn't lead to any issues in the function body either. But it's a lot more work than adding `1` type ignore comment. Thankfully there's only 3 overloads to define.
We declare additional function signatures for all of the possible values and their expected return types.

https://mypy.readthedocs.io/en/stable/more_types.html#function-overloading

Note the example below can be used as is. NOTE: the `...` are part of the syntax, they are not placeholders meant to be filled in.
```python
# assume -> from typing import overload

    @overload
    def escape_all_config_variables(
        self,
        value: Union[dict, OrderedDict],
        dollar_sign_escape_string: str = ...,
        skip_if_substitution_variable: bool = ...,
    ) -> dict:
        ...

    @overload
    def escape_all_config_variables(
        self,
        value: list,
        dollar_sign_escape_string: str = ...,
        skip_if_substitution_variable: bool = ...,
    ) -> list:
        ...

    @overload
    def escape_all_config_variables(
        self,
        value: str,
        dollar_sign_escape_string: str = ...,
        skip_if_substitution_variable: bool = ...,
    ) -> str:
        ...

    def escape_all_config_variables(
        self,
        value: Union[dict, OrderedDict, list, str],
        dollar_sign_escape_string: str = DOLLAR_SIGN_ESCAPE_STRING,
        skip_if_substitution_variable: bool = True,
    ) -> Union[dict, list, str]:
```

2022-11-19 19:29 UTC, Kilo59 commented on great_expectations/data_context/data_context/abstract_data_context.py
> +                        value=v,
We shouldn't use `TypeVar`'s this way.

2022-11-20 16:20 UTC, Kilo59 approved these changes
🚀

2022-11-20 16:22 UTC, Kilo59 commented on great_expectations/data_context/data_context/abstract_data_context.py
> +            return {  # type: ignore[return-value] recursive call expects str
```suggestion
            return {  # type: ignore[return-value] # recursive call expects str
```

2022-11-20 17:37 UTC, merged