[DOCS] - fixed code reference in documentation
fivetran/great_expectations pull request #6732
Opened 2023-01-08 05:57 UTC by tmilitino

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-  fixed code reference in documentation
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-01-10 04:47 UTC, kenwade4 requested changes
Thanks for these doc reference fixes @tmilitino! Just have one tiny change and it will get merged in

2023-01-10 04:47 UTC, kenwade4 commented on docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
> +```python file=../../../../tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py#L195-L231
Can you change the last part to L230

2023-01-11 03:05 UTC, tmilitino commented on docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_aggregate_expectations.md
> +```python file=../../../../tests/integration/docusaurus/expectations/creating_custom_expectations/expect_column_max_to_be_between_custom.py#L195-L231
Okay

2023-01-11 18:57 UTC, kenwade4 approved these changes

2023-01-11 19:17 UTC, merged