[MAINTENANCE] Unset cloud vars if not running on a cloud instance
fivetran/great_expectations pull request #6747
Opened 2023-01-10 03:54 UTC by kenwade4

2023-01-10 06:27 UTC, alexsherstinsky commented on tests/__init__.py
> +import os
@cdkini @anthonyburdi @billdirks @Kilo59 -- Something tells me that OSS should not have any mentions of `GE_CLOUD` or other non-OSS type branding (similar sentiment as not including internal JIRA ticket links in the OSS code), but wanted to know what you think.  Thanks. /cc @Shinnnyshinshin

2023-01-10 13:53 UTC, cdkini requested changes

2023-01-10 13:53 UTC, cdkini commented on tests/__init__.py
> +        del os.environ[var_name]
I think we should probably discuss this a bit more before implementing.

We've got both `GE_` and `GX_` env vars to consider

2023-01-10 18:15 UTC, cdkini commented on tests/__init__.py
> +    cloud_vars = [k for k in os.environ if k[:8] in ("GX_CLOUD", "GE_CLOUD")]
Could we instead use the `GXEnvironmentVariable` enum as a check here?

2023-01-10 19:55 UTC, cdkini commented on tests/__init__.py
> +            del os.environ[var_name]
```suggestion
if sys.platform == "darwin":
    for var in GXCloudEnvironmentVariable:
        if var in os.environ:
            logger.info(...) # or print
            os.environ.pop(var)
```

2023-01-11 17:29 UTC, cdkini approved these changes

2023-01-11 18:14 UTC, merged