[DOCS] DOC-417 How to use GX with AWS using Athena
fivetran/great_expectations pull request #6828
Opened 2023-01-18 18:29 UTC by Rachel-Reverie

Changes proposed in this pull request:
- Partitions some of the existing guides so that content doesn't exist in duplicate files.
- Adds test script for python configuration of an Athena datasource.
- Copies the AWS and S3/Pandas guide and swaps in the components for Athena to create a new guide.

### Definition of Done

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-01-18 18:33 UTC, ghost commented
<details>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=6828&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations">Click on the image</a> for a new way to code review</b>
</summary>

  - Make big changes easier — review code in small groups of related files
  - Know where to start — see the whole change at a glance
  - Take a code tour — explore the change with an interactive tour
  - Make comments and review — all fully sync’ed with github

    [Try it now!](https://app.codesee.io/r/reviews?pr=6828&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations)
</details>

[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/great-expectations/great_expectations/6828/3011e873/de31746d3c882ecf3f6b5851203b1b952b724ab9.svg)](https://app.codesee.io/r/reviews?pr=6828&src=https%3A%2F%2Fgithub.com%2Fgreat-expectations%2Fgreat_expectations)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2023-01-23 23:39 UTC, Shinnnyshinshin commented on tests/integration/test_script_runner.py
> +    ),
Just wanting to double-check. Is this a new integration test?

2023-01-23 23:41 UTC, Shinnnyshinshin commented on tests/integration/test_script_runner.py
> +    ),
Actually, I re-read the PR description, and you answered this question :)

2023-01-23 23:41 UTC, Shinnnyshinshin approved these changes
This looks great @Rachel-Reverie. Thank you very very much.

2023-01-23 23:44 UTC, Shinnnyshinshin requested changes
Looks really close, I'm seeing some `link_checker` errors and `lint` errors. 

You don't have to worry about the `docusaurus` tests, as they are not related to AWS.

2023-01-24 22:07 UTC, Shinnnyshinshin approved these changes
Looks great :)

2023-01-24 22:07 UTC, Shinnnyshinshin commented
@donaldheppner I think we need your stamp for `sidebar.js` :)

2023-01-25 20:40 UTC, donaldheppner approved these changes

2023-01-26 02:12 UTC, merged