[DOCS] Add public API docstring for `expect_column_values_to_be_between` `validate_configuration`
fivetran/great_expectations pull request #6858
Opened 2023-01-20 18:34 UTC by NathanFarmer

Changes proposed in this pull request:
- DX-237
- Add docstring

### Definition of Done
- [X] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [X] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [X] I have run any local integration tests and made sure that nothing is broken.

2023-01-20 21:17 UTC, Shinnnyshinshin commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> +              dictionary keys must be `$PARAMETER`.
A small nit, but I think the rendering will be more consistent with other files if it was un-tabbed to be in line with the `For`. 

![Screen Shot 2023-01-20 at 1 17 13 PM](https://user-images.githubusercontent.com/25670697/213806896-9c0cf7b1-9d67-46d0-8af8-852ae6bec2d0.png)

Looks like [this](https://docs.greatexpectations.io/docs/reference/api/great_expectations/util/)

2023-01-20 23:21 UTC, Shinnnyshinshin requested changes
Requesting a very small change with the list formatting

2023-01-23 14:41 UTC, NathanFarmer commented on great_expectations/expectations/core/expect_column_values_to_be_between.py
> +              dictionary keys must be `$PARAMETER`.
✅

2023-01-25 22:26 UTC, anthonyburdi approved these changes
Nice! Like the better error.

2023-01-25 22:27 UTC, merged