[CONTRIB] - Add athena credential suport
fivetran/great_expectations pull request #7063
Opened 2023-02-07 11:46 UTC by tmilitino

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE], [DOCS], [MAINTENANCE], or [CONTRIB]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
-
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in GitHub issues or Slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [ ] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-02-07 13:18 UTC, tmilitino commented
if the core team is also working on something similar let me know

2023-02-08 14:43 UTC, anthonyburdi approved these changes
Thank you for this contribution!

2023-02-08 14:43 UTC, anthonyburdi commented on great_expectations/cli/datasource.py
> +        # to use another driver, they must use a sqlalchemy connection string.
```suggestion
```

2023-02-08 14:47 UTC, anthonyburdi requested changes
Apologies - approved too fast. There is a failing test to address first, I also see this is marked as `draft`, and also please see my suggestion to remove the extraneous comment. But otherwise it does look good! This is the failing test: `test_cli_datasource_new_connection_string` (here is the CI log: https://dev.azure.com/great-expectations/great_expectations/_build/results?buildId=193049&view=logs&j=a5c71d55-c32d-50bf-9200-1f4fdc7a9682&t=68b39377-4f12-5f97-f5c6-79d1a0b1943b&l=820)

2023-02-09 12:42 UTC, tmilitino commented
@anthonyburdi mMy apologies for the inconvenience. I sent this pr to check with the core team if they are working on a similar issue. I'll consider your comments and add some more unit tests. Thank you very much.

2023-02-17 04:39 UTC, tmilitino commented on great_expectations/cli/datasource.py
> +        # to use another driver, they must use a sqlalchemy connection string.
done

2023-02-21 01:46 UTC, closed without merging