[Bugfix] Adding exception logging to store-related failures
fivetran/great_expectations pull request #7202
Opened 2023-02-22 17:29 UTC by ciguaran

Changes proposed in this pull request:

If an exception is thrown while, for example, gx.get_context() is creating the stores, only 
`Please check the configuration of your TupleS3StoreBackend named <>` is showned.
Adding logging of the exception to aid troubleshooting.

- [Y] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [Y] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code

2023-02-23 16:46 UTC, anthonyburdi approved these changes

2023-02-23 16:47 UTC, anthonyburdi requested changes
Hi @ciguaran! I was too quick to approve. Looks like you'll need to sign the CLA and there are a few tests that are failing that will need to be fixed before we can merge.

2023-02-24 18:58 UTC, ciguaran commented
@cla-bot check

2023-02-27 18:58 UTC, anthonyburdi approved these changes
Thank you for fixing that test! 🙇

2023-02-28 02:05 UTC, merged