[MAINTENANCE] Refactor to utilize common DataConnector instantiation and Connection Test Error Message templates for New FilePath Datasources
fivetran/great_expectations pull request #7268
Opened 2023-03-01 21:38 UTC by alexsherstinsky

### Scope
Instantiation of `DataConnector` classes and formatting Connection Test Error Message  templates is now done as implementations of interface `DataConnector` class-level methods.  This results in significant reduction in code duplication.

Please annotate your PR title to describe what the PR does, then give a brief bulleted description of your PR below. PR titles should begin with [BUGFIX], [FEATURE],  [DOCS], or [MAINTENANCE]. If a new feature introduces breaking changes for the Great Expectations API or configuration files, please also add [BREAKING]. You can read about the tags in our [contributor checklist](https://docs.greatexpectations.io/docs/contributing/contributing_checklist).

Changes proposed in this pull request:
- JIRA: GREAT-1462/GREAT-1692/GREAT-1690/GREAT-1691/GREAT-1619
-
-

After submitting your PR, CI checks will run and @cla-bot will check for your CLA signature.

For a PR with nontrivial changes, we review with both design-centric and code-centric lenses.

In a design review, we aim to ensure that the PR is consistent with our relationship to the open source community, with our software architecture and abstractions, and with our users' needs and expectations. That review often starts well before a PR, for example in github issues or slack, so please link to relevant conversations in notes below to help reviewers understand and approve your PR more quickly (e.g. `closes #123`).

Previous Design Review notes:
-
-
-

### Definition of Done
Please delete options that are not relevant.

- [x] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [x] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added [unit tests](https://docs.greatexpectations.io/docs/contributing/contributing_test#writing-unit-and-integration-tests) where applicable and made sure that new and existing tests are passing.
- [x] I have run any local integration tests and made sure that nothing is broken.

Thank you for submitting!

2023-03-01 23:10 UTC, donaldheppner requested changes

2023-03-01 23:10 UTC, donaldheppner commented on great_expectations/experimental/datasources/data_asset/data_connector/azure_blob_storage_data_connector.py
> +    @classmethod
these class methods are only directly invoked on the class for which they are defined. We do not need the indirection afforded by the kwargs, nor does this method need to be defined as `pass` at the data connector level.

2023-03-01 23:10 UTC, donaldheppner commented on great_expectations/experimental/datasources/data_asset/data_connector/azure_blob_storage_data_connector.py
> +    @classmethod
in short, please make the parameters explicit, and remove any empty implementations

2023-03-01 23:12 UTC, alexsherstinsky commented on great_expectations/experimental/datasources/data_asset/data_connector/azure_blob_storage_data_connector.py
> +    @classmethod
@donaldheppner If we do that, we lose the generality afforded by enabling it at the interface level.

2023-03-02 00:24 UTC, alexsherstinsky commented on great_expectations/experimental/datasources/data_asset/data_connector/azure_blob_storage_data_connector.py
> +    @classmethod
@donaldheppner -- change affected.  Thanks.

2023-03-02 02:02 UTC, Kilo59 commented on great_expectations/checkpoint/checkpoint.py
> +    instantiated directly (only its descendants, such as "Checkpoint" and "SimpleCheckpoint", should be instantiated).
This doesn't seem like a change that belongs in this PR.
Can you revert the changes in this file?
```
git checkout origin/develop great_expectations/checkpoint/checkpoint.py
```

2023-03-02 02:02 UTC, Kilo59 commented on great_expectations/experimental/datasources/pandas_filesystem_datasource.py
> +        asset._data_connector = FilesystemDataConnector.build_data_connector(
`non-blocking`
We still need to sync on how we can make this work for the dynamically defined `.add_<ASSET_TYPE>()` methods.

It should be doable, maybe anything that's in the `_EXCLUDE_FROM_READER_OPTIONS` could be passed the `build_data_connector()`. But we may also need to declare the needed `DataConnector` class.

2023-03-02 02:38 UTC, donaldheppner approved these changes

2023-03-02 03:01 UTC, alexsherstinsky commented on great_expectations/checkpoint/checkpoint.py
> +    instantiated directly (only its descendants, such as "Checkpoint" and "SimpleCheckpoint", should be instantiated).
Deleted (accidental merge).  Thanks.

2023-03-02 03:49 UTC, merged