[BUGFIX] AssertError Duing Great Expectations Installation
fivetran/great_expectations pull request #7285
Opened 2023-03-04 19:13 UTC by richardohara

This PR is submitted to resolve issue 7239.

While installing Great Expectations on a machine with Windows OS, the following AssertError is raised:

The extras requirements dir (req) contains files that do not adhere to the following format: requirements-dev-*.txt

Investigation revealed the the use of forward slashes ("/") do not work on Windows without the use of Path() from pathlib.

Changes proposed in this pull request:
- Wrap variables that contain a "/" with Path()
- Change several variable names to eliminate issues raised by PEP.

- [ ] My code follows the Great Expectations [style guide](https://docs.greatexpectations.io/docs/contributing/style_guides/code_style)
- [ ] I have performed a [self-review](https://docs.greatexpectations.io/docs/contributing/contributing_checklist) of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas

2023-03-06 16:56 UTC, anthonyburdi requested changes
Hi @richardohara! Thank you so much for the contribution! Thank you for helping our Windows users :) The changes in setup.py look great though it looks like a few unrelated changes creeped in related to Athena, would you mind merging develop into your branch and handling the conflicts?

2023-03-06 16:56 UTC, anthonyburdi commented on setup.py
> +setup(**config)
Let's make sure to leave the newline at the end of the file.

2023-03-06 18:06 UTC, Kilo59 commented on setup.py
> +    for glob_file_name in glob(f"{glob_path}"):
If we are switching to using `pathlib` for this (which I strongly agree with 😄 ), we do the `glob` operation directly from the `pathlib.Path` object.
https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob

2023-03-09 16:08 UTC, anthonyburdi approved these changes
Thanks again for this contribution! Our Windows users will thank you 🙇  I just updated this PR with our develop branch and fixed the newline issue. Let's merge this but I agree with @Kilo59's suggestion to use pathlib glob if you'd like to include that in a follow up contribution it would be very welcome!

2023-03-09 17:12 UTC, merged

2023-03-09 21:24 UTC, richardohara commented
Sorry for the delay in finishing this, but I took a few days off for some interview prep. 😊

I have a code change ready to commit ready that incorporates the change suggested by @Kilo59.