Changed the result object returned by ActionListValidationOperator - added a top level success key
fivetran/great_expectations pull request #769
Opened 2019-10-08 20:12 UTC by eugmandel

2019-10-08 20:12 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.

* In the file [`great_expectations/validation_operators/validation_operators.py`](https://github.com/great-expectations/great_expectations/blob/704b26005e30484bcf6339ffc1d927ae635e7402/great_expectations/validation_operators/validation_operators.py):

> [Line 141:121](https://github.com/great-expectations/great_expectations/blob/704b26005e30484bcf6339ffc1d927ae635e7402/great_expectations/validation_operators/validation_operators.py#L141): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2019-10-08 20:19 UTC, jcampbell requested changes
Two thoughts here:
1. Can this trigger a change to the current siteindexbuilder to use the success from here rather than the hard-coded expectations_store name it currently uses? (I assume that's the goal?)
2. How can we pass additional information between actions. Specifically, the slack action should be able to consume a URL of index page generated by the build docs action.

Is that the intent behind `details`?

2019-10-08 20:26 UTC, eugmandel commented
> Two thoughts here:
> 
> 1. Can this trigger a change to the current siteindexbuilder to use the success from here rather than the hard-coded expectations_store name it currently uses? (I assume that's the goal?)
> 2. How can we pass additional information between actions. Specifically, the slack action should be able to consume a URL of index page generated by the build docs action.
> 
> Is that the intent behind `details`?

@jcampbell ,
This PR's intent is much more modest - the result object did not have a top level "success" key, so the user had to go over the individual validation results to decide if the operator succeeded. 

I think we should address your comments in separate PRs. Please approve if you agree.

2019-10-09 13:37 UTC, jcampbell approved these changes

2019-10-09 13:37 UTC, jcampbell commented
Got it -- I was thinking of the bug of the explicit expectation_store name

2019-10-09 19:51 UTC, merged