Feature/data docs/table level expectations
fivetran/great_expectations pull request #782
Opened 2019-10-10 20:37 UTC by roblim

Add table-level expectations to validation page

2019-10-10 20:37 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.

* In the file [`great_expectations/render/renderer/column_section_renderer.py`](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/column_section_renderer.py):

> [Line 595:1](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/column_section_renderer.py#L595): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

* In the file [`great_expectations/render/renderer/content_block/expectation_string.py`](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/content_block/expectation_string.py):

> [Line 308:1](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/content_block/expectation_string.py#L308): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 310:1](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/content_block/expectation_string.py#L310): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 326:1](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/content_block/expectation_string.py#L326): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 336:1](https://github.com/great-expectations/great_expectations/blob/483bc0ab382422d27c16c112d5e10d72445443ee/great_expectations/render/renderer/content_block/expectation_string.py#L336): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2019-10-10 20:52 UTC, jcampbell requested changes
Can you add a test for the existence of a table-level expectation in some rendered output?

I'm thinking along the following lines:
1. Build the site as we do now in output.
2. Open up an html file and just look for the strings "table-level expectations" and "row count"
3. Put said test in a new tests/render/renderer/test_page_renderer.py file

2019-10-10 20:52 UTC, jcampbell commented on great_expectations/render/renderer/content_block/expectation_string.py
> +
```suggestion

```

2019-10-10 20:52 UTC, jcampbell commented on great_expectations/render/renderer/content_block/expectation_string.py
> +
```suggestion

```

2019-10-10 20:52 UTC, jcampbell commented on great_expectations/render/renderer/content_block/expectation_string.py
> +
```suggestion

```

2019-10-10 20:52 UTC, jcampbell commented on great_expectations/render/renderer/content_block/expectation_string.py
> +
```suggestion

```

2019-10-10 20:52 UTC, jcampbell commented on great_expectations/render/renderer/column_section_renderer.py
> +
```suggestion

```

2019-10-11 21:05 UTC, Aylr approved these changes
lgtm I'm stoked about these little graphs!

2019-10-11 21:05 UTC, Aylr commented on great_expectations/render/renderer/content_block/expectation_string.py
> +            template_str = "Column can match any distribution."
nice

2019-10-11 21:05 UTC, Aylr commented on tests/actions/test_validation_operators.py
> +    print(slack_query)
```suggestion
```

2019-10-11 23:12 UTC, merged