Scale output weights in expect_column_chisquare_test_p_value_to_be_gr…
fivetran/great_expectations pull request #819
Opened 2019-10-21 20:51 UTC by louispotok

…eater_than.

Fixes GH653: https://github.com/great-expectations/great_expectations/issues/653

2019-10-21 21:10 UTC, jcampbell commented
@cla-bot check

2019-10-21 21:14 UTC, jcampbell requested changes
Thank you! This looks outstanding; I suggest a small change in wording to clarify that the data *are* scaled for the test statistic itself (since that loses some information about the sample size), but rescaled upon return.

2019-10-21 21:14 UTC, jcampbell commented on docs/reference/distributional_expectations.rst
> +For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test.
```suggestion
For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test. The provided weights are scaled to the size of the data in the tested column at the time of the test, then rescaled to a probability distribution to return a valid partition object.
```

2019-10-21 21:21 UTC, louispotok commented
Thanks for the quick review! I actually misread the existing documentation
-- will add a more full explanation.

On Mon, Oct 21, 2019, 17:14 jcampbell <notifications@github.com> wrote:

> *@jcampbell* requested changes on this pull request.
>
> Thank you! This looks outstanding; I suggest a small change in wording to
> clarify that the data *are* scaled for the test statistic itself (since
> that loses some information about the sample size), but rescaled upon
> return.
> ------------------------------
>
> In docs/reference/distributional_expectations.rst
> <https://github.com/great-expectations/great_expectations/pull/819#discussion_r337242566>
> :
>
> > @@ -97,7 +97,7 @@ For continuous data, the expect_column_bootstrapped_ks_test_p_value_to_be_greate
>
>
>
>  * :func:`expect_column_bootstrapped_ks_test_p_value_to_be_greater_than <great_expectations.dataset.dataset.Dataset.expect_column_bootstrapped_ks_test_p_value_to_be_greater_than>`
>
>
>
> -For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test. The provided weights are scaled to the size of the data in the tested column at the time of the test.
>
> +For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test.
>
>
> ⬇️ Suggested change
>
> -For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test.
>
> +For categorical data, the expect_column_chisquare_test_p_value_to_be_greater_than expectation uses the Chi-Squared test. The provided weights are scaled to the size of the data in the tested column at the time of the test, then rescaled to a probability distribution to return a valid partition object.
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/great-expectations/great_expectations/pull/819?email_source=notifications&email_token=ABJJVLGJO57O5GDCW5PMWQLQPYLSLA5CNFSM4JDE7FX2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCIV3NFY#pullrequestreview-304854679>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJJVLHSR6GHGUGZJBIOI4DQPYLSLANCNFSM4JDE7FXQ>
> .
>

2019-10-22 14:50 UTC, louispotok commented
Here goes! I also noticed that the docstring for this function is wrong - it mentions the params `result_format`, `include_config`, `catch_exceptions`, and `meta`, none of which are used in the function body. Do they need to be kept for consistency with other expectations? If so, I can update the docstring so it's not misleading. WDYT?

2019-10-22 16:59 UTC, jcampbell commented
This update looks great. Since we use the `@docinherit` decorator, this docstring gets attached to the base expectation which *does* process all those parameters, so I think we ought to leave them in the docstring.

In the future, we're likely to refactor the way the decorators work to make authoring and updating expectations much clearer -- it's a good call to flag.

2019-10-22 16:59 UTC, jcampbell approved these changes

2019-10-22 16:59 UTC, merged