WIP prototype a far less wordy init flow
fivetran/great_expectations pull request #861
Opened 2019-11-11 20:44 UTC by Aylr

## What this (mostly) looks like

- Note there is a bit of post-production magic to make the welcome message appear faster.

![render1573504495954](https://user-images.githubusercontent.com/928247/68619718-3b4aa600-0489-11ea-9d1a-4223268f2d7a.gif)

2019-11-11 20:44 UTC, pep8speaks commented
Thank you for submitting to Great Expectations! This comment will be updated with subsequent commits.





* In the file [`great_expectations/cli/init_messages.py`](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py):

> [Line 7:61](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L7): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 9:29](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L9): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 9:31](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L9): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 9:38](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L9): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\/'
> [Line 9:65](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L9): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 9:69](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L9): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\('
> [Line 10:2](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:10](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:14](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:20](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:31](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:33](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 10:39](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:43](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:47](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:50](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:56](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 10:61](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L10): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\_'
> [Line 11:36](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L11): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 12:59](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L12): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 15:121](https://github.com/great-expectations/great_expectations/blob/a4b08c217787fd153252f22da640e10ededa4432/great_expectations/cli/init_messages.py#L15): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (129 > 120 characters)

2019-11-12 15:57 UTC, jcampbell requested changes
Looks awesome; one small change to address the warning about a missing class_name.

2019-11-12 15:57 UTC, jcampbell commented on great_expectations/data_context/util.py
> -        logger.warning("Instantiating class from config without an explicit class_name is dangerous. Consider adding "
I agree this should definitely not show up during init, but I believe this should indeed be a warning. It appears that the addition of the CTA config option didn't include a class_name, which is triggering the warning newly. I think this line stays the same, and `templates.py` in data context needs to change from:

```
...
    site_index_builder:
        show_cta_footer: True
```

to

```
...
    site_index_builder:
        class_name: DefaultSiteIndexBuilder
        show_cta_footer: True
```

2019-11-13 22:16 UTC, jcampbell requested changes
One line-in change now noted, since a separate PR addresses the issue that was causing the warning.

2019-11-13 22:16 UTC, jcampbell commented on great_expectations/data_context/util.py
> +        logger.debug("Instantiating class from config without an explicit class_name is dangerous. Consider adding "
A separate PR now adds the class_name default

```suggestion
        logger.warning("Instantiating class from config without an explicit class_name is dangerous. Consider adding "
```

2019-11-13 23:54 UTC, eugmandel approved these changes

2019-11-14 00:01 UTC, merged