Tiny PR: simplified tree outputs in a few places
fivetran/great_expectations pull request #869
Opened 2019-11-15 17:44 UTC by Aylr

2019-11-15 17:44 UTC, eugmandel submitted a review, later dismissed

2019-11-18 14:47 UTC, jcampbell requested changes
Two small additional corrections to the implemented expectations table.

2019-11-18 14:47 UTC, jcampbell commented on docs/reference/implemented_expectations.rst
>  |`expect_column_values_to_not_match_regex`                                          | True     | False    | True     |
```suggestion
 |`expect_column_values_to_not_match_regex`                                          | True     | True     | True     |
```

2019-11-18 14:47 UTC, jcampbell commented on docs/reference/implemented_expectations.rst
>  |`expect_column_values_to_not_match_regex_list`                                     | True     | False    | False    |
```suggestion
 |`expect_column_values_to_not_match_regex_list`                                     | True     | True     | False    |
```

2019-11-18 14:48 UTC, jcampbell submitted a review, later dismissed

2019-11-18 14:49 UTC, jcampbell commented on docs/reference/implemented_expectations.rst
> + |`expect_column_values_to_not_match_regex`                                          | True     | True     | True     |
```suggestion
|`expect_column_values_to_not_match_regex`                                          | True     | True     | True     |
```

2019-11-18 14:50 UTC, jcampbell commented on docs/reference/implemented_expectations.rst
> + |`expect_column_values_to_not_match_regex_list`                                     | True     | True     | False    |
```suggestion
|`expect_column_values_to_not_match_regex_list`                                     | True     | True     | False    |
```

2019-11-18 14:51 UTC, jcampbell approved these changes

2019-11-18 15:38 UTC, merged