Add reader_method to GlobReaderGenerator (#914)
fivetran/great_expectations pull request #915
Opened 2019-12-05 14:12 UTC by cwerner

This is my attempt to add the optional reader_method argument from SubdirReaderGenerator to GlobReaderGenerator.

This should close issei's #914.

2019-12-05 15:08 UTC, kyleaton commented
@clabot check

2019-12-05 15:11 UTC, kyleaton commented
@cla-bot check

2019-12-05 21:30 UTC, jcampbell requested changes
This looks great, really excited to merge it! Three very small requests:

1. Could you also allow the reader_method to be configured on a per-asset-glob basis, with the logic being that the base generator definition is overridden with a per-asset configuration if one is present?

2. Would you add a reader_method key to the example configuration in the docstring?

3. Would you add a reader_method to the tested config in the test_glob_reader_generator method of the test_batch_generators file?

2019-12-09 15:00 UTC, pep8speaks commented
Thank you for submitting to Great Expectations!

* In the file [`great_expectations/datasource/generator/glob_reader_generator.py`](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py):

> [Line 130:121](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py#L130): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 167:121](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py#L167): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 169:121](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py#L169): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)
> [Line 171:121](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py#L171): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (135 > 120 characters)
> [Line 202:1](https://github.com/great-expectations/great_expectations/blob/c4678d255655d99f96b642bfe54f59d4c89e4106/great_expectations/datasource/generator/glob_reader_generator.py#L202): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

This linter comment has been updated based on the most recent commit.

2019-12-09 15:03 UTC, cwerner commented
Hi

Regarding your comments:
1: I tried that but I got lost in the hierarchy of function calls. I'm not sure where the args are actually extracted? I tried to trace it down but failed.
2: Done (maybe the per-asset line is confusing and should be explained (reads like a duplicate to the global setting, but I did not want to introduce explanatory text either...)
3: here, I'd also need some more pointers/ help. not sure how/ where to do this.

2019-12-09 15:22 UTC, jcampbell requested changes
This looks great, really excited to merge it! Three very small requests:

1. Could you also allow the reader_method to be configured on a per-asset-glob basis, with the logic being that the base generator definition is overridden with a per-asset configuration if one is present?

2. Would you add a reader_method key to the example configuration in the docstring?

3. Would you add a reader_method to the tested config in the test_glob_reader_generator method of the test_batch_generators file?

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +                                                          limit=limit, reader_method=reader_method, partition_id=partition_id)
```suggestion
                                                          limit=limit, partition_id=partition_id)
```

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +                                                          limit=limit, reader_method=reader_method, partition_id=partition_id)
I think between `self.reader_method` and `glob_config`, you've already got the relevant info here.

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +    def _build_batch_kwargs_path_iter(self, path_list, glob_config, reader_options=None, limit=None, reader_method=None):
```suggestion
    def _build_batch_kwargs_path_iter(self, path_list, glob_config, reader_options=None, limit=None):
```

I think between `self.reader_method` and `glob_config`, you've already got the relevant info here.

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +            yield self._build_batch_kwargs_from_path(path, glob_config, reader_options=reader_options, limit=limit, reader_method=None)
I think between `self.reader_method` and `glob_config`, you've already got the relevant info here.
```suggestion
            yield self._build_batch_kwargs_from_path(path, glob_config, reader_options=reader_options, limit=limit)
```

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +    def _build_batch_kwargs_from_path(self, path, glob_config, reader_options=None, limit=None, reader_method=None, partition_id=None):
```suggestion
    def _build_batch_kwargs_from_path(self, path, glob_config, reader_options=None, limit=None, partition_id=None):
```
ditto above

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +            batch_kwargs['reader_method'].update(reader_method)
```suggestion
        if glob_config.get("reader_method"):
                batch_kwargs['reader_method'] = glob_config.get("reader_method")
```

2019-12-09 15:22 UTC, jcampbell commented on great_expectations/datasource/generator/glob_reader_generator.py
> +            batch_kwargs['reader_method'].update(reader_method)
Not sure a multiline suggestion worked there...

2019-12-09 15:24 UTC, jcampbell commented
I think my comment may have made it seem more complicated, but I added a snippet in the comment that I think will use the glob_config to override the the global config if present.

2019-12-09 15:27 UTC, jcampbell commented
For the third comment:

In the file `tests/datasource/generator/test_glob_reader_generator.py` there's a method called `test_glob_reader_generator_partitioning`...there is both a GlobReaderGenerator configuration and several asset configurations there; could you add reader_method to one of the asset configurations and also to the top-level configuration, and then add an assertion about the correctness of the resulting batch_kwargs?

2019-12-10 15:55 UTC, jcampbell approved these changes

2019-12-10 15:56 UTC, merged